### PR TITLE
docs: Move task sidebar blocks into main column [#7449]

### LINKED ISSUE #7449: Sidebar task decorators are difficult to read
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

# Description

Looking over the docs around `shared_task` I found the section intended for a sidebar didn't really work in the current layout of the docs.

Screenshot 2022-04-11 at 11 38 39

This displays as though it's a note or sidebar related to "bound tasks" when in fact it's part of the previous section. The layout of the page is essentially a single column, so these sidebar sections should really display as part of the main body 

# Suggestions

I'd suggest a layout something like this; 
Screenshot 2022-04-11 at 16 08 27

This includes a tweak to the first title because it doesn't actually detail what an app is.

Happy to raise a PR for this, and fix some of, if not all the errors coming out of the docs build.

### PR DESCRIPTION
**Pull request by marksweb**
## Description

This addresses the issue of the sidebar blocks on the tasks page being difficult to read and moves them into the main content column. (fixes #7449)

### CODE REVIEW

**Comment by auvipy** [comment]
can you share the current output?

**Comment by marksweb** [comment]
@auvipy screenshots before & after are in my linked issue. Is that what you're looking for?

**Comment by auvipy** [comment]
eaxcatly

**Review by auvipy — APPROVED** [review]

**Comment by auvipy** [comment]
thanks

**Pull request merged**
