### PR TITLE
Reference Gopher Celery in README

### PR DESCRIPTION
**Pull request by marselester**
## Description

Please consider adding https://github.com/marselester/gopher-celery to a list of protocol implementations.

### CODE REVIEW

**Comment by marselester** [comment]
Yes, it's been used on production for half a year.

**Comment by Nusnus** [comment]
Based on GitHub alone, the project does not seems mature, but compared to the alternative the doc suggests, this seems better.

LGTM then, approved CI for now.

@marselester - Any timeline for v1.0.0 release?

**Comment by marselester** [comment]
@Nusnus thank you for reviewing it. I am satisfied with the current state of its API, so I will cut v1.0.0 release next week.

**Comment by Nusnus** [comment]
> @Nusnus thank you for reviewing it. I am satisfied with the current state of its API, so I will cut v1.0.0 release next week.

Sounds great!

@auvipy - any objections merging it?
If not, you got my ok.

**Review by auvipy — APPROVED** [review]

**Pull request merged**
