### PR TITLE
Fixed a bug where replacing a stamped task and stamping it again

### PR DESCRIPTION
**Pull request by Nusnus**
Fixing the new stamping tutorial/example has found a new bug.
This fixes and keeps the change in the example as it makes more sense.

### CODE REVIEW

**Review by auvipy — COMMENTED** [review]
seems integration tests are failing

**Comment by Nusnus** [comment]
changed `get(timeout=10)` to `timeout=TIMEOUT`, I think that's the reason it failed (🙏)

**Comment by Nusnus** [comment]
Nope, still breaks... let me see

**Comment by Nusnus** [comment]
Ok now it should work

**Comment by Nusnus** [comment]
Yup, all tests passes now :) @auvipy

**Review by auvipy — APPROVED** [review]

**Pull request merged**
