### PR TITLE
Issue 3426. Fix to keep the kwargs in a group.

### PR DESCRIPTION
**Pull request by Mulugruntz**
This is a fix for issue #3426.

When I added the unit tests, a side effect with chords showed up, where body was treaded as a kwargs. So I had to do 2 extra changes to fix it.

Regards

### CODE REVIEW

**Comment by auvipy** [comment]
could you please add a changelog too?

**Comment by Mulugruntz** [comment]
Sure, where should I write it?

**Comment by auvipy** [comment]
why you made the change thats all. see the older changelogs

**Comment by ask** [comment]
Currently the changes are going into docs/whatsnew-4.0.rst, but that's just because we are preparing for a major release.  Usually change history goes in Changelog.  I wrote an entry for it.

**Comment by ask** [comment]
Can you please add your name to https://github.com/celery/celery/edit/master/CONTRIBUTORS.txt ?

**Comment by Mulugruntz** [comment]
Hi, I've added my name to the contributor list.
Please check everything is in order.

**Comment by auvipy** [comment]
please rebase and squash commits into 1

**Comment by thedrow** [comment]
@Mulugruntz We'll be more than happy to review this change if you'll rebase this properly.

**Pull request closed without merging**
