### PR TITLE
prevent consuming queue before ready on startup

### LINKED ISSUE #3620: Celery Worker crashing after first task with TypeError: 'NoneType' object is not callable
## Checklist

- [X] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
```
software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:3.4.3
            billiard:3.5.0.2 py-amqp:2.1.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled
```
- [X] I have verified that the issue exists against the `master` branch of Celery.
Yes I've tested and it behaves the same using master.

## Steps to reproduce
Not exactly sure, because other machines with the same specs and requirements are working.

## Expected behavior
Should consume tasks.

## Actual behavior
A task is accepted, then a traceback is logged, then the worker reconnects to the broker for some reason. This repeats forever:

```
[2016-11-23 23:09:00,468: INFO/MainProcess] Connected to amqp://user:**@10.136.131.6:5672//
[2016-11-23 23:09:00,484: INFO/MainProcess] mingle: searching for neighbors
[2016-11-23 23:09:01,921: INFO/MainProcess] mingle: sync with 1 nodes
[2016-11-23 23:09:01,922: INFO/MainProcess] mingle: sync complete
[2016-11-23 23:09:01,970: INFO/MainProcess] Received task: tasks.calculate_user_running_total[ddd103af-d527-4564-83f8-96b747767a0c]
[2016-11-23 23:09:01,972: CRITICAL/MainProcess] Unrecoverable error: TypeError("'NoneType' object is not callable",)
Traceback (most recent call last):
  File "./venv/lib/python3.4/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "./venv/lib/python3.4/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "./venv/lib/python3.4/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "./venv/lib/python3.4/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "./venv/lib/python3.4/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "./venv/lib/python3.4/site-packages/celery/worker/consumer/consumer.py", line 584, in start
    c.loop(*c.loop_args())
  File "./venv/lib/python3.4/site-packages/celery/worker/loops.py", line 47, in asynloop
    consumer.consume()
  File "./venv/lib/python3.4/site-packages/kombu/messaging.py", line 470, in consume
    self._basic_consume(T, no_ack=no_ack, nowait=False)
  File "./venv/lib/python3.4/site-packages/kombu/messaging.py", line 591, in _basic_consume
    no_ack=no_ack, nowait=nowait)
  File "./venv/lib/python3.4/site-packages/kombu/entity.py", line 737, in consume
    arguments=self.consumer_arguments)
  File "./venv/lib/python3.4/site-packages/amqp/channel.py", line 1578, in basic_consume
    wait=None if nowait else spec.Basic.ConsumeOk,
  File "./venv/lib/python3.4/site-packages/amqp/abstract_channel.py", line 73, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "./venv/lib/python3.4/site-packages/amqp/abstract_channel.py", line 93, in wait
    self.connection.drain_events(timeout=timeout)
  File "./venv/lib/python3.4/site-packages/amqp/connection.py", line 464, in drain_events
    return self.blocking_read(timeout)
  File "./venv/lib/python3.4/site-packages/amqp/connection.py", line 469, in blocking_read
    return self.on_inbound_frame(frame)
  File "./venv/lib/python3.4/site-packages/amqp/method_framing.py", line 88, in on_frame
    callback(channel, msg.frame_method, msg.frame_args, msg)
  File "./venv/lib/python3.4/site-packages/amqp/connection.py", line 473, in on_inbound_method
    method_sig, payload, content,
  File "./venv/lib/python3.4/site-packages/amqp/abstract_channel.py", line 142, in dispatch_method
    listener(*args)
  File "./venv/lib/python3.4/site-packages/amqp/channel.py", line 1613, in _on_basic_deliver
    fun(msg)
  File "./venv/lib/python3.4/site-packages/kombu/messaging.py", line 617, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "./venv/lib/python3.4/site-packages/celery/worker/consumer/consumer.py", line 558, in on_task_received
    callbacks,
  File "./venv/lib/python3.4/site-packages/celery/worker/strategy.py", line 145, in task_message_handler
    handle(req)
  File "./venv/lib/python3.4/site-packages/celery/worker/worker.py", line 221, in _process_task_sem
    return self._quick_acquire(self._process_task, req)
  File "./venv/lib/python3.4/site-packages/kombu/async/semaphore.py", line 62, in acquire
    callback(*partial_args, **partial_kwargs)
  File "./venv/lib/python3.4/site-packages/celery/worker/worker.py", line 226, in _process_task
    req.execute_using_pool(self.pool)
  File "./venv/lib/python3.4/site-packages/celery/worker/request.py", line 532, in execute_using_pool
    correlation_id=task_id,
  File "./venv/lib/python3.4/site-packages/celery/concurrency/base.py", line 155, in apply_async
    **options)
  File "./venv/lib/python3.4/site-packages/billiard/pool.py", line 1487, in apply_async
    self._quick_put((TASK, (result._job, None, func, args, kwds)))
TypeError: 'NoneType' object is not callable
```
The above lines are keep repeating every few seconds and no tasks are consumed from the queue.

### PR DESCRIPTION
**Pull request by alanhamlett**
Fixes #3620.

I want to still add a new test to cover this issue.

### CODE REVIEW

**Comment by auvipy** [comment]
yes plz do so

**Comment by michael-k** [comment]
@alanhamlett @auvipy Any hint on how to get started on those tests?  I'd like to see this in master.

**Comment by thedrow** [comment]
We need to reproduce this somehow in the integration suite and write a test that currently fails with master and does not fail with this PR.
We'd also like a unit test that enforces the order of calls to ensure we won't cause a regression.

**Comment by miraculixx** [comment]
@thedrow A test that will reproduce this behavior is 

1. start a beat scheduler that sends a task every 5 seconds. don't start any worker just yet
2. wait for 30 seconds so there are some pending messages on the queue
3. start the worker
=> the worker will invariably fail to start.

tested with celery 4.0.0, Python 2.7.12 and Python 3.5.2

Please note this is **critical** fix as it stops production deployment for any celery 4.x version. You can't have workers fail just because there are messages in the queue at start up time.

**Comment by fessoga5** [comment]
This work for me!
celery 4.0.2

Reproduce: I stopped celery and added  3 task for rabbitmq using celery library.

**Comment by thedrow** [comment]
I'm not happy about not having an integration test for this but I'm going to merge this anyway based on the feedback in this PR.

**Comment by kedare** [comment]
I'm still having the same issue on 4.0.2 if I have tasks waiting before starting the worker : 

```
root@e7b35306e4ff:/usr/src/app# /usr/local/bin/celery -A website_manager_service worker -l info -Q celery,website-manager-notify,website-manager-check,website-manager-acme,website-manager-setup -O fair --autoscale 2,6
DEBUG MODE ENABLED
/usr/local/lib/python3.5/site-packages/celery/platforms.py:793: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the -u option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,

 -------------- celery@e7b35306e4ff v4.0.2 (latentcall)
---- **** -----
--- * ***  * -- Linux-4.4.43-boot2docker-x86_64-with-debian-8.7 2017-02-16 13:33:49
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         website_manager_service:0x7f11414461d0
- ** ---------- .> transport:   amqp://guest:**@rabbitmq:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: {min=6, max=2} (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                .> website-manager-acme exchange=website-manager-acme(direct) key=website-manager-acme
                .> website-manager-check exchange=website-manager-check(direct) key=website-manager-check
                .> website-manager-notify exchange=website-manager-notify(direct) key=website-manager-notify
                .> website-manager-setup exchange=website-manager-setup(direct) key=website-manager-setup

[tasks]
  . certificate_manager.tasks.check_all_active_domains
  . certificate_manager.tasks.check_live_certificate
  . certificate_manager.tasks.delete_data
  . certificate_manager.tasks.domain_pre_check
  . certificate_manager.tasks.generate_account_private_key
  . certificate_manager.tasks.notify_slack
  . certificate_manager.tasks.prepare_owner_for_acme
  . certificate_manager.tasks.register_acme_account
  . certificate_manager.tasks.register_domain_workflow
  . certificate_manager.tasks.renew_acme_certificate
  . certificate_manager.tasks.renew_certificates_soon_expired
  . certificate_manager.tasks.request_new_acme_certificate
  . certificate_manager.tasks.revoke_acme_certificate
  . certificate_manager.tasks.synchronize_certificates_and_private_keys
  . certificate_manager.tasks.test
  . certificate_manager.tasks.unregister_domain_workflow
  . certificate_manager.tasks.weekly_reporting
  . redirect_manager.tasks.delete_data
  . redirect_manager.tasks.synchronize_redirects

[2017-02-16 13:33:50,240: INFO/MainProcess] Connected to amqp://guest:**@rabbitmq:5672//
[2017-02-16 13:33:50,260: INFO/MainProcess] mingle: searching for neighbors
[2017-02-16 13:33:50,620: ERROR/MainProcess] cannot send services: [Errno 111] Connection refused
[2017-02-16 13:33:51,289: INFO/MainProcess] mingle: all alone
[2017-02-16 13:33:51,332: INFO/MainProcess] Received task: certificate_manager.tasks.check_live_certificate[ead987f6-71d0-4ed1-be8b-ce4a3e134850]
[2017-02-16 13:33:51,334: CRITICAL/MainProcess] Unrecoverable error: TypeError("'NoneType' object is not callable",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/usr/local/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 594, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.5/site-packages/celery/worker/loops.py", line 47, in asynloop
    consumer.consume()
  File "/usr/local/lib/python3.5/site-packages/kombu/messaging.py", line 476, in consume
    self._basic_consume(T, no_ack=no_ack, nowait=False)
  File "/usr/local/lib/python3.5/site-packages/kombu/messaging.py", line 597, in _basic_consume
    no_ack=no_ack, nowait=nowait)
  File "/usr/local/lib/python3.5/site-packages/kombu/entity.py", line 737, in consume
    arguments=self.consumer_arguments)
  File "/usr/local/lib/python3.5/site-packages/amqp/channel.py", line 1578, in basic_consume
    wait=None if nowait else spec.Basic.ConsumeOk,
  File "/usr/local/lib/python3.5/site-packages/amqp/abstract_channel.py", line 73, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/usr/local/lib/python3.5/site-packages/amqp/abstract_channel.py", line 93, in wait
    self.connection.drain_events(timeout=timeout)
  File "/usr/local/lib/python3.5/site-packages/amqp/connection.py", line 464, in drain_events
    return self.blocking_read(timeout)
  File "/usr/local/lib/python3.5/site-packages/amqp/connection.py", line 469, in blocking_read
    return self.on_inbound_frame(frame)
  File "/usr/local/lib/python3.5/site-packages/amqp/method_framing.py", line 88, in on_frame
    callback(channel, msg.frame_method, msg.frame_args, msg)
  File "/usr/local/lib/python3.5/site-packages/amqp/connection.py", line 473, in on_inbound_method
    method_sig, payload, content,
  File "/usr/local/lib/python3.5/site-packages/amqp/abstract_channel.py", line 142, in dispatch_method
    listener(*args)
  File "/usr/local/lib/python3.5/site-packages/amqp/channel.py", line 1613, in _on_basic_deliver
    fun(msg)
  File "/usr/local/lib/python3.5/site-packages/kombu/messaging.py", line 623, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/usr/local/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 568, in on_task_received
    callbacks,
  File "/usr/local/lib/python3.5/site-packages/celery/worker/strategy.py", line 145, in task_message_handler
    handle(req)
  File "/usr/local/lib/python3.5/site-packages/celery/worker/worker.py", line 221, in _process_task_sem
    return self._quick_acquire(self._process_task, req)
  File "/usr/local/lib/python3.5/site-packages/kombu/async/semaphore.py", line 62, in acquire
    callback(*partial_args, **partial_kwargs)
  File "/usr/local/lib/python3.5/site-packages/celery/worker/worker.py", line 226, in _process_task
    req.execute_using_pool(self.pool)
  File "/usr/local/lib/python3.5/site-packages/celery/worker/request.py", line 531, in execute_using_pool
    correlation_id=task_id,
  File "/usr/local/lib/python3.5/site-packages/celery/concurrency/base.py", line 155, in apply_async
    **options)
  File "/usr/local/lib/python3.5/site-packages/billiard/pool.py", line 1487, in apply_async
    self._quick_put((TASK, (result._job, None, func, args, kwds)))
TypeError: 'NoneType' object is not callable
[2017-02-16 13:33:51,346: INFO/MainProcess] Received task: certificate_manager.tasks.check_live_certificate[4fde6119-e063-4d50-83ff-ddd731a9fe82]
[2017-02-16 13:33:51,348: WARNING/MainProcess] Rejecting message with delivery tag 3 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,348: WARNING/MainProcess] Rejecting message with delivery tag 4 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,350: WARNING/MainProcess] Rejecting message with delivery tag 5 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,350: WARNING/MainProcess] Rejecting message with delivery tag 6 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,351: WARNING/MainProcess] Rejecting message with delivery tag 7 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,354: WARNING/MainProcess] Rejecting message with delivery tag 8 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,355: WARNING/MainProcess] Rejecting message with delivery tag 9 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,357: WARNING/MainProcess] Rejecting message with delivery tag 10 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,358: WARNING/MainProcess] Rejecting message with delivery tag 11 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,358: WARNING/MainProcess] Rejecting message with delivery tag 12 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,359: WARNING/MainProcess] Rejecting message with delivery tag 13 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,361: WARNING/MainProcess] Rejecting message with delivery tag 14 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,362: WARNING/MainProcess] Rejecting message with delivery tag 15 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,363: WARNING/MainProcess] Rejecting message with delivery tag 16 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,367: WARNING/MainProcess] Rejecting message with delivery tag 17 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,368: WARNING/MainProcess] Rejecting message with delivery tag 18 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,370: WARNING/MainProcess] Rejecting message with delivery tag 19 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,371: WARNING/MainProcess] Rejecting message with delivery tag 20 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,373: WARNING/MainProcess] Rejecting message with delivery tag 21 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,374: WARNING/MainProcess] Rejecting message with delivery tag 22 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,376: WARNING/MainProcess] Rejecting message with delivery tag 23 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,377: WARNING/MainProcess] Rejecting message with delivery tag 24 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,378: WARNING/MainProcess] Rejecting message with delivery tag 25 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,380: WARNING/MainProcess] Rejecting message with delivery tag 26 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,381: WARNING/MainProcess] Rejecting message with delivery tag 27 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,383: WARNING/MainProcess] Rejecting message with delivery tag 28 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,384: WARNING/MainProcess] Rejecting message with delivery tag 29 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,384: WARNING/MainProcess] Rejecting message with delivery tag 30 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,386: WARNING/MainProcess] Rejecting message with delivery tag 31 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,386: WARNING/MainProcess] Rejecting message with delivery tag 32 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,387: WARNING/MainProcess] Rejecting message with delivery tag 33 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,389: WARNING/MainProcess] Rejecting message with delivery tag 34 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,392: WARNING/MainProcess] Rejecting message with delivery tag 35 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,394: WARNING/MainProcess] Rejecting message with delivery tag 36 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,395: WARNING/MainProcess] Rejecting message with delivery tag 37 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,399: WARNING/MainProcess] Rejecting message with delivery tag 38 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,399: WARNING/MainProcess] Rejecting message with delivery tag 39 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,401: WARNING/MainProcess] Rejecting message with delivery tag 40 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,402: WARNING/MainProcess] Rejecting message with delivery tag 41 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,403: WARNING/MainProcess] Rejecting message with delivery tag 42 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,404: WARNING/MainProcess] Rejecting message with delivery tag 43 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,406: WARNING/MainProcess] Rejecting message with delivery tag 44 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,410: WARNING/MainProcess] Rejecting message with delivery tag 45 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,410: WARNING/MainProcess] Rejecting message with delivery tag 46 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,411: WARNING/MainProcess] Rejecting message with delivery tag 47 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,412: WARNING/MainProcess] Rejecting message with delivery tag 48 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,412: WARNING/MainProcess] Rejecting message with delivery tag 49 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,416: WARNING/MainProcess] Rejecting message with delivery tag 50 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,417: WARNING/MainProcess] Rejecting message with delivery tag 51 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,418: WARNING/MainProcess] Rejecting message with delivery tag 52 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,419: WARNING/MainProcess] Rejecting message with delivery tag 53 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,419: WARNING/MainProcess] Rejecting message with delivery tag 54 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,422: WARNING/MainProcess] Rejecting message with delivery tag 55 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,422: WARNING/MainProcess] Rejecting message with delivery tag 56 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,423: WARNING/MainProcess] Rejecting message with delivery tag 57 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,424: WARNING/MainProcess] Rejecting message with delivery tag 58 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,425: WARNING/MainProcess] Rejecting message with delivery tag 59 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,425: WARNING/MainProcess] Rejecting message with delivery tag 60 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,427: WARNING/MainProcess] Rejecting message with delivery tag 61 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,429: WARNING/MainProcess] Rejecting message with delivery tag 62 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
[2017-02-16 13:33:51,431: WARNING/MainProcess] Rejecting message with delivery tag 63 for reason of having no callbacks.
consumer_tag='None8' exchange='' routing_key='website-manager-setup'.
root@e7b35306e4ff:/usr/src/app#
```

If I start with an empty queue, it's working fine

Should I open a new issue ?

**Comment by miraculixx** [comment]
@kedare can you confirm this is happening with celery installed using

```
pip install -U git+http://github.com/Eugeny/celery#egg=celery==4.0.2.1
```

see https://github.com/celery/celery/issues/3620#issuecomment-279749792

**Comment by kedare** [comment]
@miraculixx I confirm you it's fixing the problem :)

**Comment by michael-k** [comment]
> I'm still having the same issue on 4.0.2 if I have tasks waiting before starting the worker

@kedare This pull request got merged into master after the 4.0.2 release.
`git+https://github.com/celery/celery.git@4d63867c8281e94c74dcdf84fe2a441eaed6671b#egg=celery` should fix it too.

**Comment by alanhamlett** [comment]
@thedrow do you have some example integration tests? I could write a new test, just need an example to follow.

**Comment by michael-k** [comment]
The tests regarding `asynloop` are in https://github.com/celery/celery/blob/master/t/unit/worker/test_loops.py

I haven't figured out how to reproduce the issues in the tests. (I didn't spend much time looking into it.)

**Comment by thedrow** [comment]
I haven't given it much thought but I think it can be done by populating the queue and then starting the celery worker.
If the task does not execute or fails we fail the test.

**Comment by cp2587** [comment]
This solves a critical bug. When are you planning to release a new version with this PR merged ?

**Comment by thedrow** [comment]
@ask Can we release a new 4.x version?

**Comment by abrange** [comment]
This solved my issue that randomly my workers stop working after update to 4.0.2. Thanks

`pip install -U git+http://github.com/Eugeny/celery#egg=celery==4.0.2.1`

**Comment by rwillmer** [comment]
There's a lot of people waiting on this critical bug fix. What's stopping you doing a release?

**Comment by miraculixx** [comment]
@ask any ETA on a new release that includes this critical PR? Please note that any 4.x version is, in effect, not currently usable in production due to this.

**Comment by ChillarAnand** [comment]
@ask @mher Can you make a new release?

**Comment by ChillarAnand** [comment]
@thedrow How can I help?

**Comment by auvipy** [comment]
@ChillarAnand writing release notes

**Comment by Sigurs** [comment]
@aventurella Any ETA for the new release? Current 4.x is just too unstable for production use.

**Comment by auvipy** [comment]
@thedrow @ask

**Comment by silverfix** [comment]
@ask Any ETA for the new release? Current 4.0.2 is just too **unstable for production use**.

**Comment by thedrow** [comment]
I've written the release notes for py-amqp. Once it's out we'll release kombu and then celery.

**Comment by auvipy** [comment]
awesome

**Comment by galuszkak** [comment]
I will greatly appreciate new release 👍

**Comment by amit1rrr** [comment]
@thedrow any ETA on this release going live?

**Comment by thedrow** [comment]
Currently we're debating on a merged PR in py-amqp. It might have security issues we'd like to avoid. Once that is resolved we'll release py-amqp and start working on releasing kombu.

**Comment by amit1rrr** [comment]
@thedrow Is this released now?

**Comment by michael-k** [comment]
No, the current release is still 2.1.4 instead of 2.2.0
- https://pypi.python.org/pypi/amqp
- https://github.com/celery/py-amqp/releases
- https://github.com/celery/py-amqp/commits/master

**Comment by silverfix** [comment]
Sorry guys, but this is A SHAME! Celery IS NOT production-ready with that
HUGE bug.


*Andrea Rabbaglietti*Senior Software Engineer
https://github.com/silverfix



Mobile: +39 329 60 54 433
E-mail & Google Hangout: rabbagliettiandrea@gmail.com
Skype: rabbagliettiandrea
LinkedIn: *https://it.linkedin.com/in/andrearabbaglietti
<https://it.linkedin.com/in/andrearabbaglietti>*



2017-07-05 15:20 GMT+02:00 Michael <notifications@github.com>:

**Comment by galuszkak** [comment]
@silverfix please, be kind. Guys puts a lot of effort in that project. It's not their fault. Release manager is unavailable (for whatever reason), and we should be respectful about that. You can always use version from git if you have problem using version from PyPI. 

Please remember it's contributors time and we should be respectful about that. 

Thanks @ask and whole team for great work!

**Comment by michael-k** [comment]
See https://github.com/celery/celery/issues/4109#issuecomment-314367686 for news

**Comment by auvipy** [comment]
we are going to release new versions on pypi. keep in mind that we all work on our personal time. and not all of us have the release key's. but things are going to change now. thanks all for patience and support.

**Pull request merged**
