### PR TITLE
demo docstrings still linted in CI

### LINKED ISSUE #6278: Restore pydocstyle in CI
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same enhancement was already implemented in the
  master branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Brief Summary

I'm not sure when pydocstyle was removed from the build matrix but we I wasn't made aware of it.
We need this to ensure our documentation coverage and style are in check.

# Design

Just revert the commit which removed it.

## Architectural Considerations

None

## Proposed Behavior

N/A

## Proposed UI/UX

N/A

## Diagrams

N/A

## Alternatives

None

### PR DESCRIPTION
**Pull request by graingert**
fixes #6278

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

### CODE REVIEW

**Comment by graingert** [comment]
@thedrow ^

**Comment by graingert** [comment]
@thedrow https://travis-ci.org/github/celery/celery/jobs/714409042#L674-L677

**Comment by georgepsarakis** [comment]
@graingert you are probably right, however it seems that [pydocstyle](https://github.com/PyCQA/pydocstyle) is much more popular and up-to-date. Perhaps it would be better to use the tools that are more broadly used in the ecosystem, also because there is higher chance that contributors will have used them as well in other projects.

**Comment by graingert** [comment]
@geoffreybauduin flake8-docstrings is an official pycqa wrapper of pydocstyle in the same way flake8 wraps pycodestyle

**Pull request closed without merging**
