### PR TITLE
Upgrade AzureBlockBlob storage backend to use Azure blob storage library v12

### PR DESCRIPTION
**Pull request by JanusAsmussen**
*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description
This PR upgrades the AzureBlockBlob storage backend to use Azure blob storage library v12. This replaces the currently used SDK (Azure blob storage library v2.1) which is considered a legacy version by Microsoft.

### CODE REVIEW

**Comment by auvipy** [comment]
could you please check if there are any other things that need to be updated? integration test/tox etc?

**Comment by JanusAsmussen** [comment]
Hi,

Both unit & integration tests related to the AzureBlockBlob storage backend are passing when using the environment set up with Docker and docker-compose. However, I had to change the azurite docker image used when spinning up the environment (It is now using the official Microsoft image). I've committed this change to the remote branch.

Regarding tox: I do not believe anything should be changed.

**Review by auvipy — CHANGES_REQUESTED** [review]
can you check the following alerts?
This pull request introduces 17 alerts and fixes 3 when merging 0493f66 into 2c6f46d - view on LGTM.com

new alerts:

    12 for Wrong number of arguments in a call
    3 for Module is imported with 'import' and 'import from'
    1 for __eq__ not overridden when adding attributes
    1 for Use of the return value of a procedure

**Comment by JanusAsmussen** [comment]
Commit 0493f66 changes a single string in a yaml file. I would believe these warnings are caused by 2c6f46d?

**Review by matusvalo — APPROVED** [review]
LGTM for me.

**Comment by matusvalo** [comment]
@auvipy do you have still objections?

**Review by auvipy — APPROVED** [review]

**Pull request merged**
