### PR TITLE
doc: update event's result max size configuration.

### PR DESCRIPTION
**Pull request by laixintao**
Just add a document for a configuration.

see:

https://github.com/celery/celery/issues/2724#issuecomment-16401350

### CODE REVIEW

**Comment by thedrow** [comment]
I'm not sure the API was meant to be used that way.

**Comment by laixintao** [comment]
How about moving it to the configurations?

https://docs.celeryproject.org/en/latest/userguide/configuration.html#id12

**Comment by thedrow** [comment]
I guess it's possible to add a default value for result representation max size.

**Comment by jheld** [comment]
Are there docs around the args and kwargs reprs?

**Comment by thedrow** [comment]
I don't think so.

**Comment by jheld** [comment]
I would have appreciated more docs. I've found the code, but it took awhile.

**Comment by thedrow** [comment]
Well this is not the proper fix in my opinion.
Feel free to issue a new one.

**Pull request closed without merging**
