### PR TITLE
Inspect commands now accept arguments

### LINKED ISSUE #6705: Celery inspect expected extra argument
I am trying to inspect a task which I can see in my redis broker as `SUCCESS`, however, it was never logged by celery application.

I then tried inspecting it, but I am unable to do so, getting following error

image

Output of `celery report`

```
software -> celery:5.0.2 (singularity) kombu:5.0.2 py:3.6.9
            billiard:3.6.3.0 redis:3.5.3
platform -> system:Linux arch:64bit, ELF
            kernel version:5.4.0-1038-aws imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://redis.xyz.service:6379/0
```

### PR DESCRIPTION
**Pull request by thedrow**
*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

This was missing from #5718. We should backport it to 5.0.x as well in my opinion since there's no reason this will be malfunctioning if a user is still stuck on that version and can't upgrade.

Fixes #6705.

### CODE REVIEW

**Comment by thedrow** [comment]
@codeasashu Would you mind trying this patch?
I tested it myself. I think it should solve your issue.

**Comment by codeasashu** [comment]
@thedrow Sure, I'll test it tomorrow and let you know

**Review by auvipy — APPROVED** [review]

**Comment by codeasashu** [comment]
@thedrow Please go ahead. I can not verify it atm, due to catastrophic surge in covid-19 cases (india).

**Comment by thedrow** [comment]
@codeasashu I've heard. Stay safe and healthy :)

**Pull request merged**
