### PR TITLE
Bump PyPy version in build to 5.8.0

### PR DESCRIPTION
**Pull request by thedrow**
Let's see if we can make the build stay green :)

### CODE REVIEW

**Comment by auvipy** [comment]
good attempt

**Comment by georgepsarakis** [comment]
@thedrow sorry for the noise, I had to rebase.

**Comment by georgepsarakis** [comment]
@thedrow tests seem to be passing. Also, latest version of [amqp](https://travis-ci.org/celery/celery/jobs/253863883#L642) is used for the tests.

**Comment by thedrow** [comment]
Wonderful. Thank you.

**Pull request merged**
