### PR TITLE
ElasticSearch: Retry index if document was deleted between index and update

### PR DESCRIPTION
**Pull request by mchataigner**

### CODE REVIEW

**Comment by mchataigner** [comment]
Done.

**Comment by auvipy** [comment]
>       return super().exception_safe_to_retry(exc)

E       TypeError: super() takes at least 1 argument (0 given)

celery/backends/elasticsearch.py:100: TypeError

 on py27 matrix

**Comment by auvipy** [comment]
/home/travis/build/celery/celery$ /home/travis/build/celery/celery/.tox/flake8/bin/flake8 -j 2 celery t

celery/backends/elasticsearch.py:14:1: F401 '.base.Backend' imported but unused

**Comment by mchataigner** [comment]
Done.

**Pull request merged**
