### PR TITLE
Switch to Codecov for coverage reporting

### PR DESCRIPTION
**Pull request by stevepeak**
> Full disclosure I work for Codecov

Codecov uses Celery to handle all its backend delayed tasks. It would be an honor to have Celery use Codecov for its coverage product.

Some of our core features include:
- Seamless overlay of coverage reports in Github with our browser extensions. [Video](https://www.youtube.com/watch?v=d6wJKODB8_g)
- Awesome pull request comments. [Example](https://gist.github.com/codecov-io/ba612976215481e7f27c)
- Github commit status integration to ensure coverage meets minimum standards
- Automatic unified builds. See [pyca/cryptography](https://codecov.io/github/pyca/cryptography) for example
- Storing build environment variables.

Love all the feedback you have and I look forward to having Celery on Codecov :)

Cheers,
Steve

### CODE REVIEW

**Comment by stevepeak** [comment]
Looks like only reports for py2.7 are being uploaded on purpose. I would suggest uploading coverage for all builds to get the most accurate coverage reports on Codecov. It's is ready for coveragepy v4 which presents the branch arcs for properly merging branches. Thanks!

The report can be found here: https://codecov.io/github/celery/celery?ref=04a772e1446d5a42c5242bda403479dfed36be48

**Comment by malinoff** [comment]
@ask please take a look.

**Comment by thedrow** [comment]
@malinoff We use codecov at work. I wouldn't mind using it with celery as well.

**Comment by stevepeak** [comment]
@ask @malinoff Let me know if you have any questions about Codecov. I look forward to hosting Celery on Codecov. Thanks!

**Comment by ask** [comment]
Let's try it :)

**Pull request merged**
