### PR TITLE
Instead of yielding each item, yield from the entire consumed list first

### PR DESCRIPTION
**Pull request by thedrow**
*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

This addresses my code review comment in https://github.com/celery/celery/pull/6542#discussion_r542023631 which was not applied in #6589.

### CODE REVIEW

**Review by auvipy — APPROVED** [review]

**Comment by auvipy** [comment]
thanks

**Comment by thedrow** [comment]
@auvipy Why did you merge this PR before the build passed?
Is it still not working?

**Comment by auvipy** [comment]
> @auvipy Why did you merge this PR before the build passed?
> Is it still not working?

the build keeping building after running some integration tests. so we need to do something about that front. might run integration tests separately.

**Comment by auvipy** [comment]
image
 they were auto-canceled last night after several hours

**Pull request merged**
