### PR TITLE
Fix Exception marshalling with JSON serializer

### LINKED ISSUE #2518: CELERY_RESULT_SERIALIZER = 'json' breaks Exception marshaling
Setting `CELERY_RESULT_SERIALIZER = json` and raising an exception in the worker leads to this:

```
/path/to/lib/python2.7/site-packages/celery/result.py in get(self, timeout, propagate, interval, no_ack, follow_parents, EXCEPTION_STATES, PROPAGATE_STATES)
    173             status = meta['status']
    174             if status in PROPAGATE_STATES and propagate:
--> 175                 raise meta['result']
    176             return meta['result']
    177     wait = get  # deprecated alias to :meth:`get`.

TypeError: exceptions must be old-style classes or derived from BaseException, not dict
```

where the contents of `meta['result']` are (in my case):

```
{u'exc_message': u'unknown keys: nam', u'exc_type': u'ValueError'}
```

so it *looks* like celery could convert the dict to a real exception before raising, but it does not currently.  Changing back to `pickle` works as expected.

bug can be reproduced with the following:

```python
# jsonresults.py
from celery.app.base import Celery

CELERY_RESULT_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'amqp'

app = Celery(config_source=__name__)

@app.task
def hello():
    raise ValueError('go away')
```

worker:

```
# python -m celery --app=jsonresults:app worker
```

caller:

```python
import jsonresults
jsonresults.hello.delay().get()
```

### PR DESCRIPTION
**Pull request by allardhoeve**
When using the JSON serializer, exceptions get serialized as dicts. The code in `drain_events` in `amqp.py` naively then sets the result dict to such a dict without transforming the dict structure back into an actual Exception through `exception_to_python` [[1]](https://github.com/celery/celery/blob/6592ff64b6b024a4b68abcc53b151888fdf0dee3/celery/backends/amqp.py#L198).

When a task raises an exception, `AsyncResult.get` and `AsyncResult.maybe_reraise` try to raise the
exception [[2]](https://github.com/celery/celery/blob/6592ff64b6b024a4b68abcc53b151888fdf0dee3/celery/result.py#L890) [[3]](https://github.com/celery/celery/blob/6592ff64b6b024a4b68abcc53b151888fdf0dee3/celery/result.py#L273), which is actually still a dict and fail with:

```
TypeError: exceptions must be old-style classes or derived from
BaseException, not dict
```

This patch makes `drain_events` call `meta_from_decoded` which is
responsible for that, just like it is called in `get_many` [[4]](https://github.com/celery/celery/blob/33e72fdbc7b07fc26d13bcdc36fb6f42c8291b66/celery/backends/amqp.py#L255). Then,
raising the exception in `AsyncResult` works fine.

To reproduce, see the testcase in #2518. Then, apply the patch and see
stuff start to work again.

closes #2518

### CODE REVIEW

**Comment by allardhoeve** [comment]
Travis seems to fail on the pypy build, which has been failing consistently for all PRs. Other builds are fine.

**Comment by thedrow** [comment]
I'm not sure how the second commit fixed anything.
Is there any way to write a test for this bug fix to ensure it won't regress?

**Comment by allardhoeve** [comment]
So I tried to explain that in the commit message:

Attempt to pass Travis test on pypy …
- supress progress bar by pip when running pypy as this
  seems to crash the test on Travis:
  https://travis-ci.org/celery/celery/jobs/60549687

- this prevents dev.txt from being properly installed and the
  result is tests failing with import errors

**Comment by allardhoeve** [comment]
I don't see how we would write a test that checks this. It is a weird combination of outputting a progress bar with utf-8 characters into Travis's console. Locally, everything works, but not in Travis. This seemed like the smallest and quickest fix.

**Comment by thedrow** [comment]
Sorry I meant a test for the bug fix itself. Not the fact that pip is failing with PyPy3.

**Comment by allardhoeve** [comment]
like so?

**Comment by thedrow** [comment]
Yup.

**Comment by allardhoeve** [comment]
Any feedback on this PR?

**Comment by thedrow** [comment]
LGTM. @ask Please merge.

**Comment by allardhoeve** [comment]
bump @ask, @thedrow

**Comment by thedrow** [comment]
@PMickael Maybe you can take a look?

**Comment by PMickael** [comment]
Thanks, please add you're name to contributor if it's not already in.

**Comment by naggie** [comment]
I think this is still an issue -- running the development version from the snapshot repositories. I can reproduce it using any combination of redis/rabbitMQ and json/msgpack.

**Pull request merged**
