### PR TITLE
Fix for issue #5030 "Celery Result backend on Windows OS".

### PR DESCRIPTION
**Pull request by kdeyev**
*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

Fix for issue #5030 "Celery Result backend on Windows OS".
Filesystem result backend didn't work on Windows.

### CODE REVIEW

**Review by auvipy — COMMENTED** [review]
this looks good to me. but can you provide some test that this going to be OK? you can also share your local testing output. our windows CI is not good to check thsi so need some extra effort from you. I don't have access to windows as well

**Comment by auvipy** [comment]
also if you check  if this suggestion is helpful https://github.com/celery/celery/issues/5030#issuecomment-418676281 ?

**Comment by kdeyev** [comment]
@auvipy, Thank you for your answer. 
[#5030](https://github.com/celery/celery/issues/5030#issuecomment-418676281) is suggesting to use a "network path". But in my case, I'm trying to use a local Windows path, like C:\Temp.

The simplest task, which can show the problem:
```
import tempfile

from celery import Celery

temp = tempfile.mkdtemp()
print(f"{temp} directory will be used to filesystem backend")
app = Celery("tasks", broker="memory://", backend=f"file:///{temp}")

worker = app.Worker(
    hostname="hostname",
    pool_cls="threads",
)

worker.start()
```

This code will work nice on Linux, but crashed on Windows:
```
C:\Users\kostya\AppData\Local\Temp\tmpge9tnh4c directory will be used to filesystem backend
[2021-01-26 09:04:40,754: CRITICAL/MainProcess] Unrecoverable error: ImproperlyConfigured('The configured path for the file-system backend does not\nwork correctly, please make sure that it exists and has\nthe correct permissions.',)
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\kombu\utils\objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\celery\backends\filesystem.py", line 74, in _do_directory_test
    self.set(key, b"test value")
  File "C:\Python\lib\site-packages\celery\backends\filesystem.py", line 91, in set
    with self.open(self._filename(key), "wb") as outfile:
OSError: [Errno 22] Invalid argument: b'/C:\\Users\\kostya\\AppData\\Local\\Temp\\tmpge9tnh4c\\.fs-backend-f4cfc7c1-7df3-4fde-abec-561164ff5e86'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\celery\worker\worker.py", line 208, in start
    self.blueprint.start(self)
  File "C:\Python\lib\site-packages\celery\bootsteps.py", line 115, in start
    self.on_start()
  File "C:\Python\lib\site-packages\celery\apps\worker.py", line 140, in on_start
    self.emit_banner()
  File "C:\Python\lib\site-packages\celery\apps\worker.py", line 155, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File "C:\Python\lib\site-packages\celery\apps\worker.py", line 218, in startup_info
    results=self.app.backend.as_uri(),
  File "C:\Python\lib\site-packages\kombu\utils\objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "C:\Python\lib\site-packages\celery\app\base.py", line 1193, in backend
    return self._get_backend()
  File "C:\Python\lib\site-packages\celery\app\base.py", line 911, in _get_backend
    return backend(app=self, url=url)
  File "C:\Python\lib\site-packages\celery\backends\filesystem.py", line 57, in __init__
    self._do_directory_test(b".fs-backend-" + uuid().encode(encoding))
  File "C:\Python\lib\site-packages\celery\backends\filesystem.py", line 78, in _do_directory_test
    raise ImproperlyConfigured(E_PATH_INVALID)
celery.exceptions.ImproperlyConfigured: The configured path for the file-system backend does not
work correctly, please make sure that it exists and has
the correct permissions.
```
It happens because the path: /C:\\Users\\kostya\\AppData\\Local\\Temp\\tmpge9tnh4c\\.fs-backend-f4cfc7c1-7df3-4fde-abec-561164ff5e86 is not valid Windows path (there is an extra "/").
After the code patching the same code with produce:

```
C:\Users\kostya\AppData\Local\Temp\tmp3l95jvtj directory will be used to filesystem backend
 
 -------------- celery@hostname v4.4.7 (cliffs)
--- ***** -----
-- ******* ---- Windows-10-10.0.18362-SP0 2021-01-26 09:04:47
- *** --- * ---
- ** ---------- [config]
- ** ---------- .> app:         tasks:0x21e040fe630
- ** ---------- .> transport:   memory://localhost//
- ** ---------- .> results:     file:///C:\Users\kostya\AppData\Local\Temp\tmp3l95jvtj
- *** --- * --- .> concurrency: 12 (thread)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
```
So Celery worker was able to start on Windows with filesystem backend.

Please let me know if you want me to run any other test or provide more information.

Thank you and have a great day.
Kostya

**Review by auvipy — APPROVED** [review]

**Comment by auvipy** [comment]
would be great if you can also provide some unit test for the proposed change

**Pull request merged**
