### PR TITLE
Smoke tests

### PR DESCRIPTION
**Pull request by auvipy**

### CODE REVIEW

**Comment by Nusnus** [comment]
Hey friend - you've jumped the gun a bit.
This is a WIP work, and this PR is not needed as the work is far from ready to merge.
When the time comes, I will handle the smoke tests; please let me take the lead.

Also, the v5.4 topic is premature - I want to handle this release when the time comes due to the significant changes I am developing for it. I suggest closing it for now, thank you.

**Comment by auvipy** [comment]
I just tried to initiate the process. not to take your work. Also you can also be the RM for 5.4 if you want. we can discuss further, and if it seems premature we can close for now! no problem at all

**Comment by Nusnus** [comment]
> I just tried to initiate the process. not to take your work. Also you can also be the RM for 5.4 if you want. we can discuss further, and if it seems premature we can close for now! no problem at all

I hope my tone didn't sound offensive 🙏
I'm sure all is done professionally, I just wanted to point it out.

Thank you for everything bro ! 👑

**Comment by auvipy** [comment]
I thought it offended you so I tried to clarify and ask for apology! I'm with you fully in your next plans!

**Comment by Nusnus** [comment]
> I thought it offended you so I tried to clarify and ask for apology! I'm with you fully in your next plans!

All good 🙂
Closing the issues.

**Pull request closed without merging**
