### PR TITLE
Fix examples of starting a worker in comments

### PR DESCRIPTION
**Pull request by kigawas**
Gotcha: 
Now you have to use
```
celery --app=proj worker
```

### CODE REVIEW

**Comment by qiaocci** [comment]
These command was supported in celery 4.4.7.
Should we port it to celery 5.x?

**Comment by kigawas** [comment]
> These command was supported in celery 4.4.7.
> Should we port it to celery 5.x?

I don't think so since `--app=proj` does not belong to `celery worker` command

**Comment by thedrow** [comment]
> These command was supported in celery 4.4.7.
> Should we port it to celery 5.x?

This is indeed a breaking change. I haven't found a way to implement this behavior with Click without resorting to hacks.
I don't believe it is necessary anyway,

**Review by thedrow — APPROVED** [review]
Thank you for this.
I'm working on the documentation myself so this helps :)

**Review by georgepsarakis — APPROVED** [review]

**Pull request merged**
