### PR TITLE
Annotate `celery/states.py`

### PR DESCRIPTION
**Pull request by Kludex**
- Related to #7394

EDIT: I've included `celery/signals.py` on this PR, as there was no changes needed on it.

### CODE REVIEW

**Review by auvipy — APPROVED** [review]
is there any better ways to validate or verify type hints?

**Comment by Kludex** [comment]
> is there any better ways to validate or verify type hints?

I'm not sure if I get the question. Isn't mypy doing that for us already?

**Comment by auvipy** [comment]
also to avoid to much small PR, can you include small modules type hints in a single PR? with separate commits?

**Comment by Kludex** [comment]
Sure!

**Pull request merged**
