### PR TITLE
Windows Not Supported

### PR DESCRIPTION
**Pull request by W7PEA**
Its very misleading to say you can run RabbitMQ on Windows and then also at the same time not support Celery on Windows. This doc change helps the community head down the correct path in the beginning as opposed to wasting time trying things that won't work (liek I did).

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

Please describe your pull request.

NOTE: All patches should be made against master, not a maintenance branch like
3.1, 2.5, etc.  That is unless the bug is already fixed in master, but not in
that version series.

If it fixes a bug or resolves a feature request,
be sure to link to that issue via (Fixes #4412) for example.

### CODE REVIEW

**Comment by auvipy** [comment]
support was restored in 4.1

**Comment by thedrow** [comment]
We do not guarantee that Celery will work under Windows. The unit tests run and we accept pull requests to provide support but we do not develop Celery with Windows in mind.
Celery 4.0 was broken on Windows as far as I can recall but we fixed that.
If you want to help maintain Celery on Windows, we'll welcome it of course.

You can run RabbitMQ on Windows. If you can't, that's not something we can handle. That's something for RabbitMQ's developers to handle.
If you need to do so, run RabbitMQ on Windows and Celery on Linux and everything should work.

**Comment by thedrow** [comment]
@W7PEA Ping?

**Comment by W7PEA** [comment]
I'm going to close this. Thanks for the notes. I decided to go another direction.

Along the journey, I re-rememembered the Windows Subsystem for Linux exists now. Not yet fully supported but it should be a path forward for devs on Windows with technologies that need a Linux command not available on Windows (in this case Fork). 
WSL: https://docs.microsoft.com/en-us/windows/wsl/about
System Commands: https://blogs.msdn.microsoft.com/wsl/2016/06/08/wsl-system-calls/

**Pull request closed without merging**
