### PR TITLE
require django 1.11 LTS for celery 4.3

### PR DESCRIPTION
**Pull request by auvipy**
update minimal django version to django 1.11 for celery 4.3

### CODE REVIEW

**Comment by thedrow** [comment]
What's the motivation behind this change?

**Comment by auvipy** [comment]
Only support the supported versions of django and this change will affect only 4.3.x release of celery, when django 1.11 wil be the last supported LTS. moreover django-celery-beats and django-celery-results will also drop django versions less than 1.11 in the next release.

**Comment by gregflynn** [comment]
As a user not on Django 1.11 yet, this change made me sad today.

**Comment by thedrow** [comment]
You have to understand, we can't keep supporting versions which have reached EOL.
There are too many dependencies & versions in Celery as it is so we strive to keep the maintenance overhead as small as possible.

**Pull request merged**
