### PR TITLE
bugfix

### PR DESCRIPTION
**Pull request by Acey9**
In class ElasticsearchBackend
The function set(self, key) assign the document id to the "key”, But the function _index does not set the document id to the "key".
in the function get(self, key) assign the document id is the "key”, because the backend no document id is the "key" ,so I can not get the task result

### CODE REVIEW

**Comment by thedrow** [comment]
Can you explain what you fixed and why is it working better now?

**Comment by Acey9** [comment]
In class  ElasticsearchBackend
The function set(self, key) does not assign the document id  to the "key”, 
but the function get(self, key) assign the document id is the "key”, 
so I can not get the task result，because the backend no document id is the "key"

**Comment by thedrow** [comment]
I'll be happy to merge this as soon as you fix the build errors.

**Comment by thedrow** [comment]
Is this ready for merge? Are you going to add tests for this backend?

**Comment by Acey9** [comment]
yes, you can merge it, and I passed the test. forgive me for bad git use. i need create a new pull request or no?

**Comment by thedrow** [comment]
Yes, please do.

**Comment by Acey9** [comment]
hi, thedrow ,i create a new pr, merge it please

**Pull request closed without merging**
