### PR TITLE
Update request info inspect api for making pickle serialization compatibility

### PR DESCRIPTION
**Pull request by kitsuyui**
## Description

A proposal to fix https://github.com/celery/celery/issues/5890#issuecomment-751657642
Use argsrepr and kwargsrepr to make pickle serialization compatibility.
Inspections don't have to be passed args and kwargs directly.

### CODE REVIEW

**Comment by kitsuyui** [comment]
I think this changes breaks backward compatibility. But it should not be a big problem.
Because `request.info()` is mainly used for just inspection and monitoring, I think.

**Review by auvipy — CHANGES_REQUESTED** [review]
could you please add unit test for this? as you were able to reproduce it

**Comment by auvipy** [comment]
And the breaking change should be mentioned in the doc as well

**Comment by kitsuyui** [comment]
Okay, I will do it.
> could you please add unit test for this? as you were able to reproduce it

**Review by auvipy — APPROVED** [review]

**Comment by auvipy** [comment]
@ShaheedHaque would you mind checking this pr?

**Comment by ShaheedHaque** [comment]
@auvipy Just to confirm: I assume that trying to `inspect active` while a job is running in my setup is what you had in mind? Or is there some other config change I need?

**Comment by matusvalo** [comment]
Hi All. I will review the PR soon.

**Comment by matusvalo** [comment]
I have merged master and fixed integration tests.

**Review by matusvalo — APPROVED** [review]
LGTM. Documentation also needs updating? If yes please update also docs.

**Comment by thedrow** [comment]
> I think this changing breaks backward compatibility. But it should not be a big problem.
> Because `request.info()` is mainly used for just inspection and monitoring, I think.

This can break monitoring systems, possibly including flower.

**Review by thedrow — CHANGES_REQUESTED** [review]
We need to find a way to do this properly so it will work with json and pickle.

**Comment by matusvalo** [comment]
@thedrow problem is mostly following:
1. call/response of tasks serializer is configurable. Json is preferred bug pickle can be used.
2. inspect/control calls/responses are serialized as json and I am not aware of changing this behavior.

So the problem occurs when you are using pickle serializer for tasks and you pass objects which are not serializable via json. This will cause that sending tasks will be working but inspect/controll calls will be broken.

Possible solution is to use the same serializer for inspect/control as for tasks is used.

**Comment by thedrow** [comment]
Thank you for the contribution. We went ahead with another solution in #6757.
You are welcome to contribute again at any time :)

**Pull request closed without merging**
