### PR TITLE
Cross process tracebacks improvement

### PR DESCRIPTION
**Pull request by ionelmc**
This is a simpler improvement than https://github.com/celery/celery/pull/1823 and needs no billiard changes. 

Few notes:

* This PR is primarily for review - I don't expect it to be merged in 3.1. Should it?
* No tests yet (it was tested in my app's suite).
* It adds a new optional dependency: https://pypi.python.org/pypi/tblib. It needs to be at least 1.3.0. Is this feasible?

### CODE REVIEW

**Comment by thedrow** [comment]
I think that a new optional dependency is fine.
If we're at it, maybe we can add pygments as well to color the traceback?

**Comment by thedrow** [comment]
Oh nevermind. I thought you're trying to prettify the exception messages.
Out of scope for this PR.

**Comment by thedrow** [comment]
LGTM. It needs tests :)

**Comment by ask** [comment]
Using the tlib if available, definitely seems reasonable!

- Needs tests as @thedrow said
- Needs to be patched against master, not 3.1
- Should add a `celery[tlib]` extra requirement:
  http://docs.celeryproject.org/en/latest/contributing.html#contributing-features-requiring-additional-libraries
- `RAISE_FAKE_EXCEPTIONS` sounds awkward, maybe rename that to `task_pretty_exceptions`

**Comment by ionelmc** [comment]
Just throwing some more ideas here, how about `CELERY_PRECISE_TASK_TRACEBACKS` or `CELERY_PRECISE_TRACEBACKS`?

For the package extra, how about `celery[precise-tracebacks]`?

I will redo this on the master - just wanted some early feedback.

**Comment by thedrow** [comment]
@ionelmc Sounds better.

**Comment by ask** [comment]
Sounds good to me! Although "precise" doesn't immediately describe the feature to me, I can admit that "pretty" does not either.

**Comment by ionelmc** [comment]
How about `CELERY_REMOTE_TRACEBACKS`?

**Comment by ask** [comment]
That sounds decent!  Remember that you also need to add new configuration options to `docs/configuration.rst`

**Comment by ionelmc** [comment]
@ask are you interested in releasing this in 3.1 in any way? Let me know and then I can fix the pending issues here.

**Comment by ask** [comment]
Duplicate of #3139 

I don't want to introduce any new features into 3.1 at the moment, have to focus on 4 :)

**Pull request closed without merging**
