### PR TITLE
Run unit tests in parallel

### PR DESCRIPTION
**Pull request by thedrow**
The build is painfully slow right now. I'm checking if we can speed up the unit tests at the very least.

### CODE REVIEW

**Comment by orf** [comment]
I would set `-n` to `auto`, rather than hard-code it to `2`. `auto` will detect the number of cpus and use that number :+1:

**Comment by thedrow** [comment]
Not really since Travis uses a virtualized environment that doesn't expose the number of CPUs correctly.

**Comment by orf** [comment]
Also perhaps adding `--durations=N` as an option is a good idea, pytest will print out the slowest `N` tests.

**Comment by thedrow** [comment]
Right I remember that one of these tests failed.
The question is why though.

**Comment by orf** [comment]
I'm going to take a stab in the dark and say that the multiple test runners are all using the same queue settings: https://github.com/celery/celery/blob/master/t/unit/conftest.py#L48

I think they should be prefixed with the 'worker id', i.e ` 'task_default_queue': 'testcelery_' + WORKER_ID,` or some such.

**Comment by thedrow** [comment]
I don't think so since the broker is set to memory. I'll parametrize it anyway just to be on the safe side.

**Comment by georgepsarakis** [comment]
@thedrow , after the merge of #3785, the builds are significantly faster. If you check the specifications of the virtualization environments offered by [Travis](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments), you can find that the current environment is `SUDO-ENABLED`, since  `sudo: required` is specified in `.travis.yml`.

This virtualization environment uses a **maximum** of 2 CPUs, so running tests in parallel won't surely  give much performance gain. Also, the boot time ranges from 20s to 52s, which is comparable to the time that tests consume.

I think it would be more beneficial if the project reverted to container-based environment, if possible, rather than adding complexity for running tests in parallel.

**Comment by georgepsarakis** [comment]
Tried what I suggested above in #3829, the results were disappointing.

**Comment by georgepsarakis** [comment]
@thedrow I added some optimizations with #3867 .

**Comment by thedrow** [comment]
@georgepsarakis I think we need to resolve this somehow anyway. This failure indicates that one of our tests depends on another test.

**Comment by thedrow** [comment]
I just tried running with xdist again and everything seems to be in order. I'll create a new PR shortly.

**Comment by thedrow** [comment]
Ok so this is very strange. With 2 workers the test suite fails. With 8, it passes.

**Pull request closed without merging**
