### PR TITLE
Allow join in eager canvas application

### LINKED ISSUE #4576: Eager Application Synchronous Subtask Guard Blocks Canvas
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

```
celery -A minimal_eager_chain report

software -> celery:4.2.0 (latentcall) kombu:4.1.0 py:2.7.13
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

```

Minimal script to reproduce: https://gist.github.com/npilon/9f3c8469a615081fc8454359945eebd7

## Expected behavior

- No error occurs

## Actual behavior

- We trip the synchronous subtask alarm:

```
>>> test.delay().get()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/npilon/Documents/celery/celery/result.py", line 949, in get
    raise self.result
RuntimeError: Never call result.get() within a task!
See http://docs.celeryq.org/en/latest/userguide/tasks.html#task-synchronous-subtasks
```

### PR DESCRIPTION
**Pull request by npilon**
## Description

Permit async applied chains to join their results during eager application testing.

Fixes #4576

### CODE REVIEW

**Comment by thedrow** [comment]
We'd prefer to have both unit and integration tests for this PR.
If you can provide them, we'll gladly include it in our next release.

**Comment by npilon** [comment]
I'd love to provide unit tests, but the unit testing framework patches out the functionality that causes the bug I'm trying to fix: https://github.com/celery/celery/blob/master/t/unit/conftest.py#L139-L154

I'll see if I can provide integration tests.

**Comment by npilon** [comment]
Ah, no, I see that fixture keeps an `_orig` for un-doing itself. I've added tests.

**Comment by npilon** [comment]
What category should I use for the changelog entry?

**Comment by auvipy** [comment]
you can check here to have some hint https://github.com/celery/celery/commit/8047ca9e818db8151dc6c80814600797ab94f5bc

**Comment by npilon** [comment]
@auvipy I think I've adjusted the changelog files appropriately.

**Comment by thedrow** [comment]
Thank you very much :)

**Comment by courcelm** [comment]
Is this fix in 4.2rc2?

I have a test that run with CELERY_TASK_ALWAYS_EAGER = True
which call chord(header)(callback).

I get the following error:
RuntimeError: Never call result.get() within a task!

Without CELERY_TASK_ALWAYS_EAGER = True, this code runs fine.

**Comment by thedrow** [comment]
@courcelm The fix is in 4.2rc2. If you believe something is wrong, please file an issue with a detailed analysis of what you think is wrong and possibly how to fix this.

**Comment by jcushman** [comment]
As reported by @courcelm, this patch fixed the issue for `chain()` but not for `chord()`. I added a comment with a script to reproduce the problem on the original issue. I figured it might make sense to reopen the original issue instead of file a new one, since the issue is "Eager Application Synchronous Subtask Guard Blocks Canvas" and that covers the remaining problems. Let me know if you'd like a new issue filed instead.

**Pull request merged**
