### PR TITLE
fix: fix worker asyncloop

### PR DESCRIPTION
**Pull request by mlabo7**
*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryq.dev/en/main/contributing.html).

## Description
Fix for 
```
Traceback (most recent call last):
  File "/srv/dotcom/lib/python3.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/srv/dotcom/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/srv/dotcom/lib/python3.7/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/srv/dotcom/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 326, in start
    blueprint.start(self)
  File "/srv/dotcom/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/srv/dotcom/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 618, in start
    c.loop(*c.loop_args())
  File "/srv/dotcom/lib/python3.7/site-packages/celery/worker/loops.py", line 81, in asynloop
    next(loop)
  File "/srv/dotcom/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 301, in create_loop
    poll_timeout = fire_timers(propagate=propagate) if scheduled else 1
  File "/srv/dotcom/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 143, in fire_timers
    entry()
  File "/srv/dotcom/lib/python3.7/site-packages/kombu/asynchronous/timer.py", line 64, in __call__
    return self.fun(*self.args, **self.kwargs)
  File "/srv/dotcom/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 610, in verify_process_alive
    assert proc.outqR_fd in hub.readers
AssertionError
```

### CODE REVIEW

**Comment by auvipy** [comment]
why this only pass on python 3.10?

**Review by auvipy — CHANGES_REQUESTED** [review]
can you please make the CI green for all the python versions?

**Review by auvipy — CHANGES_REQUESTED** [review]
besides, this will need unit tests adjustment or new coverage

**Comment by thedrow** [comment]
Thank you for your contribution but we cannot accept it at this time.
We're not sure what problem you are fixing and the lack of test coverage doesn't allow us to analyze the problem to come up with an agreed solution.
If you change your mind and can come up with a reproducible test case, we'll reconsider this contribution.

**Pull request closed without merging**
