### PR TITLE
Add `security_key_password` option

### PR DESCRIPTION
**Pull request by tibotix**
## Description

This PR introduces the `security_key_password` option. This option allows to specify a passphrase that is used to decrypt the private key using the `serialization.load_pem_private_key` method. 

The `security_key_password` option can be specified as a config option, or as a keyword argument in the  `Celery.setup_security` method.

### CODE REVIEW

**Review by thedrow — CHANGES_REQUESTED** [review]
Just a minor fix.

**Review by auvipy — COMMENTED** [review]
I think the elasticsearch backend failures need to be addressed in another PR

**Review by thedrow — APPROVED** [review]

**Comment by thedrow** [comment]
> I think the elasticsearch backend failures need to be addressed in another PR

This is because of a dependency update issue. Please open a new issue about it.

**Comment by auvipy** [comment]
done https://github.com/celery/celery/issues/7316 . I wanted to release a point release to 5.2.x series, can we hold off 5.3 features merge until feb 28 please?

**Pull request merged**
