### PR TITLE
Add args to LOG_RECEIVED (fixes #6885)

### LINKED ISSUE #6885: Include args in Received (like Rejected)
- [X] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
- [X] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
- [X] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same enhancement was already implemented in the
  master branch.
- [X] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

## Related Issues and Possible Duplicates
None that I'm aware of

# Brief Summary
Logging `args` is really helpful, but it's currently only done with `Rejected` logs and it would be nice to also include in `Received` logs

See https://github.com/celery/celery/blob/f02d7c60051ce5202349fe7c795ebf5000d9526d/celery/app/trace.py#L259

# Design

## Architectural Considerations
If a task takes a lot of args or large args, then it could make logs large

## Proposed Behavior
Include `args` in `Received` logs

## Proposed UI/UX
On by default with a way to turn it off

## Diagrams
N/A

## Alternatives
Off by default with a way to turn it on

### PR DESCRIPTION
**Pull request by daveisfera**
## Description
Add `args` to the `context` that's logged with `LOG_RECEIVED` (like `LOG_REJECTED`)

Fixed #6885

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
please check the test failures

**Comment by daveisfera** [comment]
Are there instructions on how to run the tests locally?

**Comment by thedrow** [comment]
> 
> 
> Are there instructions on how to run the tests locally?

The unit tests can be run with tox. See Contributing.rst.

**Comment by thedrow** [comment]
Unfortunately, you've created this PR from your fork's master so I can't edit it.
The fix for the test failure is very simple.
You just need to add the new context data to the assertion. See https://github.com/celery/celery/pull/6898/checks?check_run_id=3264607890#step:8:3063.

**Comment by daveisfera** [comment]
Sorry for the delay. I still haven't fixed my local setup to work with the GitHub password changes, so I couldn't push changes and just ended up doing it through the web UI, so hopefully the tests will pass now.

**Comment by thedrow** [comment]
@daveisfera No worries.
In the future, please create a branch before opening a PR so we can complete the work ourselves if you are unavailable.
If you were not able to complete this PR, I'd have to close this one and create another which is a hassle.

**Review by thedrow — APPROVED** [review]

**Comment by amitoj9** [comment]
hey @daveisfera  is there a way to get rid of args n kwargs from getting logged ?

**Comment by daveisfera** [comment]
Should be possible by customizing the logger config. I haven't done that myself (because I wanted the `args` and `kwargs` to be logged), but it should be possible

**Comment by anitalaw** [comment]
@daveisfera (and all) - apologies if this is the wrong place to post this. In celery 4.x the "received" logs will show the task's ETA if available. Example:
`INFO Received task: exampleTaskName[8b68c9be-d3c3-4352-b3bc-8749ed5a5c0c] ETA:[2022-10-11 21:09:20.919008+00:00]`. However 5.x is no longer there. I'm seeing that you have to add `eta: req.eta` to the `context` dict, and also overwrite `LOG_RECEIVED` in my app. Is there another way? Should this be a request in the celery repo. Thanks for the help!

**Comment by auvipy** [comment]
> @daveisfera @thedrow @auvipy (and all) - apologies if this is the wrong place to post this. In celery 4.x the "received" logs will show the task's ETA if available. Example: `INFO Received task: exampleTaskName[8b68c9be-d3c3-4352-b3bc-8749ed5a5c0c] ETA:[2022-10-11 21:09:20.919008+00:00]`. However 5.x is no longer there. I'm seeing that you have to add `eta: req.eta` to the `context` dict, and also overwrite `LOG_RECEIVED` in my app. Is there another way? Should this be a request in the celery repo. Thanks for the help!

we got a new PR here https://github.com/celery/celery/pull/8301 please check

**Pull request merged**
