### PR TITLE
Fix redis connections leak

### PR DESCRIPTION
**Pull request by D0d0**
Tries to fix https://github.com/celery/celery/issues/6819

_Note_: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description
Tries to fix redis connections leak with caching backend https://github.com/celery/celery/issues/6819. Also should fix https://github.com/andymccurdy/redis-py/issues/1495#

### CODE REVIEW

**Comment by D0d0** [comment]
> btw tests are failing so you need to adjust them as well

yeah, working on it

**Comment by D0d0** [comment]
well, i run test on my PC and and failing tests finished almost instantly. Wasn't there any problem with machines? Because every test time out after 20 minutes. Is it possible to rerun tests?

```
========================================================================================== test session starts ===========================================================================================
platform darwin -- Python 3.9.2, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /Users/jozef/PycharmProjects/celery, configfile: setup.cfg
plugins: subtests-0.5.0, case-1.5.3, timeout-1.4.2, cov-3.0.0, celery-0.0.0
collected 100 items                                                                                                                                                                                      

t/unit/tasks/test_result.py ..................s.................................................................................                                                                   [100%]

===================================================================================== 99 passed, 1 skipped in 4.76s ======================================================================================
```

**Comment by thedrow** [comment]
@matusvalo Do we have the same problem with `cached_property` as https://github.com/celery/kombu/pull/1394?

**Comment by matusvalo** [comment]
> @D0d0 You'd have to explain why the connection leaks when we don't cache it.

I agree with it. This PR will fix problems with connections leaks but it will bring back Issue #6414 and all duplicates. We need to understand why leak is appearing. Was #6414 checked that is not introduced again with this PR?

**Comment by uuip** [comment]
https://github.com/redis/redis-py/blob/master/README.md#thread-safety
redis-py is thread-safety. One redis connection pool can be global, every thread has a pool make additional connections.

**Comment by D0d0** [comment]
> https://github.com/redis/redis-py/blob/master/README.md#thread-safety redis-py is thread-safety. One redis connection pool can be global, every thread has a pool make additional connections.
> 
> @matusvalo @D0d0
> 
> ```diff
> diff --git a/celery/app/base.py b/celery/app/base.py
> --- a/celery/app/base.py	(revision da871f89a0b15f56636848419e78c961522555c2)
> +++ b/celery/app/base.py	(revision 1940c9f9823076e9ce5f5e443df86bea294fb2e2)
> @@ -310,6 +310,7 @@
>  
>          self.on_init()
>          _register_app(self)
> +        self.redis_backend = None
>  
>      def _get_default_loader(self):
>          # the --loader command-line argument sets the environment variable.
> @@ -934,6 +935,11 @@
>          backend, url = backends.by_url(
>              self.backend_cls or self.conf.result_backend,
>              self.loader)
> +        # redis-py always use independent connection for every command, one pool instance is enough
> +        if url.startswith('redis'):
> +            if not self.redis_backend:
> +                self.redis_backend = backend(app=self, url=url)
> +            return self.redis_backend
>          return backend(app=self, url=url)
>  
>      def _finalize_pending_conf(self):
> ```

Tested it with gevent and connections do not leak anymore

**Comment by auvipy** [comment]
started the build

**Comment by uuip** [comment]
@D0d0 
```
if isinstance(url, str) and url.startswith('redis'):
```

**Comment by adrienyhuel** [comment]
I can confirm this is working.
I had a Celery app which was leaking Redis connections (it went up to hundreds of connections, making celery memory grow too).
I applied the patch manually on base.py file, now there is only one or two connections per worker thread (gevent) , and it doesn't grow.

**Pull request closed without merging**
