### PR TITLE
Patch for #5320

### PR DESCRIPTION
**Pull request by the-glu**
This is an ugly (but probably working) fix for issue described in #5320 .

This should probably not merged like this :)

### CODE REVIEW

**Comment by the-glu** [comment]
I tried, but I don't understand the threads_not_lingering error and how to fix it :(

**Comment by thedrow** [comment]
Can you please rebase?
There are commits which don't appear in the final diff so this PR is hard to review.

**Comment by auvipy** [comment]
@the-glu can you revisit this?

**Comment by the-glu** [comment]
Hello,

Sorry but I don't have a lot of time thoses days :/

I can try but it will be delayed a bit more. If someone takeover and redo a nice patch it will probably be faster :)

Sorry :/

**Comment by auvipy** [comment]
hey, can you check if https://github.com/celery/celery/pull/6416 fix your issue?

**Comment by thedrow** [comment]
I think we can close this PR if no one is going to work on it.
@celery/core-developers Does anyone have some time to work on this?

**Pull request closed without merging**
