### PR TITLE
changed x-ha-policy to ha-mode for rabbitmq 3 changes

### PR DESCRIPTION
**Pull request by auvipy**
to fix https://github.com/celery/celery/issues/4896

### CODE REVIEW

**Comment by auvipy** [comment]
definitely, I will. you could check the blog post on the reported issue

**Comment by joekohlsdorf** [comment]
In Travis no version of RabbitMQ is specified so it will use the latest image for integration testing.
The change in RabbitMQ was introduced with 3.0 and the last 2.x release was in 2012, I doubt anybody is using it in combination with the latest releases of Celery.

**Comment by auvipy** [comment]
this will affect 3.x versions of rabbit

**Comment by thedrow** [comment]
We will make note of this in the release notes.

**Pull request merged**
