### PR TITLE
Support Python 3.7

### PR DESCRIPTION
**Pull request by noirbizarre**
## Description

This pull-request adds support for Python 3.7 in build tools:
- test on Python 3.7 in Travis CI
- test on Python 3.7 in Tox
- add Python 3.7 to Dockerfile/pyenv

### CODE REVIEW

**Comment by rgreinho** [comment]
#4859 also attempted to solve this problem.

**Comment by noirbizarre** [comment]
@rgreinho Sorry, I saw this PR after. Should I close this PR ?

NB: build is working but there is still some issue with Python 3.7:
- The rabbitmq integration tests are freezing at launch (same issue on my laptop with Python 3.7 so not TravisCI related)
- Riak driver syntax is not compatible with Python 3.7 (the github repository only talk about Python 3.5 support)
- The redis timeout seems to be random on Travis CI (I don't reproduce it on my computer)

**Comment by noirbizarre** [comment]
Fixed rabbitmq, it wasn't installed in xenial.
There is still redis timeout and riak syntax error to fix

**Comment by rgreinho** [comment]
@noirbizarre The PR I mentioned is not mine, but it does look like a duplicate of yours.

I am just trying to follow all the issues/PRs related to Celery and python 3.7 as we upgraded our infrastructure, but had to put our Celery updates/modifications on hold as it does not work on 3.7.

**Comment by dvf** [comment]
I'm not sure why Python 3.7 was added as a classifier to Celery 4.2.1. Right now, I'm seeing what certainly looks like an `amqp` issue related to 3.7:

```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'producer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/apps/beat.py", line 109, in start_scheduler
    service.start()
  File "/usr/local/lib/python3.7/site-packages/celery/beat.py", line 588, in start
    interval = self.scheduler.tick()
  File "/usr/local/lib/python3.7/site-packages/celery/beat.py", line 307, in tick
    self.apply_entry(entry, producer=self.producer)
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/python3.7/site-packages/celery/beat.py", line 441, in producer
    return self.Producer(self._ensure_connected(), auto_declare=False)
  File "/usr/local/lib/python3.7/site-packages/celery/beat.py", line 425, in _ensure_connected
    _error_handler, self.app.conf.broker_connection_max_retries
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 405, in ensure_connection
    callback)
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/functional.py", line 332, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 261, in connect
    return self.connection
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 802, in connection
    self._connection = self._establish_connection()
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/amqp/connection.py", line 302, in connect
    self.transport.connect()
  File "/usr/local/lib/python3.7/site-packages/amqp/transport.py", line 81, in connect
    self.socket_settings, self.read_timeout, self.write_timeout,
  File "/usr/local/lib/python3.7/site-packages/amqp/transport.py", line 176, in _init_socket
    self._setup_transport()
  File "/usr/local/lib/python3.7/site-packages/amqp/transport.py", line 295, in _setup_transport
    self.sock = self._wrap_socket(self.sock, **self.sslopts)
  File "/usr/local/lib/python3.7/site-packages/amqp/transport.py", line 302, in _wrap_socket
    return self._wrap_socket_sni(sock, **sslopts)
  File "/usr/local/lib/python3.7/site-packages/amqp/transport.py", line 341, in _wrap_socket_sni
    sock = ssl.SSLSocket(**opts)
  File "/usr/local/lib/python3.7/ssl.py", line 788, in __init__
    f"{self.__class__.__name__} does not have a public "
TypeError: SSLSocket does not have a public constructor. Instances are returned by SSLContext.wrap_socket().
```

**Comment by noirbizarre** [comment]
@dvf  This is why I submitted this PR: to ensure the Python 3.7 compatibility is really tested. It seems the error you reported is not covered by any test (or maybe the `-x` option hide errors not yet reached).
If not,maybe this is the right time to add a test covering this issue.

**Comment by rgreinho** [comment]
Hi There! Any update on this PR? Python 3.7 is **really** important!

**Comment by thedrow** [comment]
Thank you for your contribution.
We have already merged such a PR.
I've completed the updates to the Dockerfile and scripts that were required and will push them shortly.

**Pull request closed without merging**
