### PR TITLE
Python 3.7 compat issues

### PR DESCRIPTION
**Pull request by auvipy**
Another pass to fix compatibility issues with python 3.7

### CODE REVIEW

**Comment by thedrow** [comment]
Can you please fix the documentation problem we got?

**Comment by AlexSwensen** [comment]
#4500 
linking for documentation

**Comment by auvipy** [comment]
@thedrow need you suggestion to fix doc errors, where should I change? I am not sure where to change

**Comment by thedrow** [comment]
@auvipy You need to rename https://github.com/celery/celery/blob/fff12f08af8539c3e2e3c73733e69ce26e98194a/docs/internals/reference/celery.backends.async.rst and edit the contents to match the rename of the module to `celery.backends.asynchronous`.

**Comment by auvipy** [comment]
thanks i will

**Comment by thedrow** [comment]
I thought we disabled landscape :(
Anyway, this is LGTM.
Is there anything else we need to do here?

**Pull request merged**
