### PR TITLE
Add Maintainers to README

### PR DESCRIPTION
**Pull request by rattrayalex**
See https://github.com/celery/celery/issues/2534

### CODE REVIEW

**Comment by rattrayalex** [comment]
I really don't know who's a maintainer and who's not - I don't mean to be opinionated here, just create a building point for the real maintainers to say what is and what isn't :-)

**Comment by raghuramos1987** [comment]
i dont know if i'm well versed enough to be listed as a maintainer since i very recently started looking into celery. you could add me later?

**Comment by rattrayalex** [comment]
cool, done @raghuramos1987

**Comment by malinoff** [comment]
@rattrayalex please make all @username-s clickable and I'll merge it.

**Comment by rattrayalex** [comment]
done @malinoff - thanks!

**Comment by malinoff** [comment]
Thanks!

**Comment by ask** [comment]
@rattrayalex Hey! Thank you for this patch.  The README.rst file is actually automatically generated from `docs/include/*` by running `make readme`†

The document http://docs.celeryproject.org/en/master/contributing.html mentions this in some places, but no specific section about editing the README.

† or `paver readme` in 3.1, need to install `pip install -r requirements/pkgutils.txt` first.

**Comment by rattrayalex** [comment]
Ah, whoops! Would one of those shiny new maintainers be willing to take that up? I don't even have celery installed or the repo downloaded...

**Pull request merged**
