### PR TITLE
Add typing to Celery

### PR DESCRIPTION
**Pull request by atombrella**
This is a simple bootstrap of the process, adding some types to a
few selected functions, based on comment annotations. MyPy is chosen as the
default static analyzer for the types.

It's an attempt to solve #7258 Note that the work is quite demanding.

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
thanks for taking this stub, can you check the lint failures please?

**Comment by atombrella** [comment]
> thanks for taking this stub, can you check the lint failures please?

Yes. I'm working on it. Have some patience ;)

**Comment by Kludex** [comment]
Is the idea here to incrementally increase typing on Celery?

If yes, wouldn't it be interesting to support file by file? We did this on uvicorn: https://github.com/encode/uvicorn/blob/8585051189f0530165e901e0c5fab57998648943/setup.cfg#L5-L43

**Comment by Kludex** [comment]
Do @atombrella you mind if I tackle the needed fixes here?

**Comment by atombrella** [comment]
> Do @atombrella you mind if I tackle the needed fixes here?

Please do :) I'm currently a bit caught up on other things.

**Comment by Kludex** [comment]
I've created #7383

**Pull request closed without merging**
