### PR TITLE
isort checks fixed

### PR DESCRIPTION
**Pull request by auvipy**

### CODE REVIEW

**Comment by auvipy** [comment]
in my dev machine latest isort fixed them but after the pr it seems to be opposite. not sure why that's behaving

**Comment by thedrow** [comment]
@auvipy Shell we close this? Let's open an issue about it instead and give it some investigation later.

**Comment by auvipy** [comment]
ok

**Comment by auvipy** [comment]
plz open one

**Comment by auvipy** [comment]
actually, it seems to be an isort issue in travis!

**Pull request closed without merging**
