### PR TITLE
Crontab string representation does not match UNIX crontab expression

### PR DESCRIPTION
**Pull request by espoirMur**
This is similar to this issue in the, I am attempting to fix in the celery global repos.

I will give more info later.

https://github.com/celery/django-celery-beat/issues/73

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

### CODE REVIEW

**Comment by auvipy** [comment]
you are trying to align with this right https://github.com/celery/django-celery-beat/pull/318/files

**Review by auvipy — CHANGES_REQUESTED** [review]
can you provide some unit tests for the change please?

**Comment by espoirMur** [comment]
Yeah.. @auvipy

I am trying to align this with it.

I will write test somewhere in the weekend once I get time.

But you can review it and let me know it is working.

**Comment by auvipy** [comment]
did you get the time?

**Comment by thedrow** [comment]
@espoirMur How can I help?

**Comment by espoirMur** [comment]
> can you provide some unit tests for the change, please?

@thedrow, basically I want to unit test these changes. If you can help in that area.

**Review by auvipy — APPROVED** [review]

**Pull request merged**
