### PR TITLE
Added proper error messages in cases where app cannot be loaded

### PR DESCRIPTION
**Pull request by thedrow**
Previously we'd simply crash with an exception.
Now a proper error message is displayed.

### CODE REVIEW

**Comment by auvipy** [comment]
I remember there is a related issue

**Comment by thedrow** [comment]
I was waiting for a code review.
Do you mind testing this manually?

**Comment by thedrow** [comment]
@auvipy Ping?

**Comment by auvipy** [comment]
please wait till tomorrow! I am quite busy today. sorry!

**Pull request merged**
