### PR TITLE
 Use importlib instead of discouraged pkg_resources

### PR DESCRIPTION
**Pull request by nijel**
## Description

Use importlib instead of discouraged pkg_resources. This avoids runtime dependency on setuptools (which caused problems because of pinning see for example #7214) and adds importlib backport dependency on Python 3.7.

From https://setuptools.pypa.io/en/latest/pkg_resources.html:

> Use of pkg_resources is discouraged in favor of importlib.resources, importlib.metadata, and their backports (resources, metadata). Please consider using those libraries instead of pkg_resources.

### CODE REVIEW

**Comment by clokep** [comment]
Duplicate of #7217, I think?

**Comment by auvipy** [comment]
But it has some extra changes

**Comment by nijel** [comment]
> Duplicate of #7217, I think?

Yes, it is nearly the same. I did search pull requests when starting work on that, not when submitting the PR :-).

**Comment by auvipy** [comment]
@thedrow I think we should consider this one

**Review by sim1234 — APPROVED** [review]

**Review by thedrow — APPROVED** [review]

**Review by auvipy — APPROVED** [review]

**Comment by thedrow** [comment]
FYI this is released in 5.2.5 :)
Thanks!

**Comment by jensenbox** [comment]
@thedrow 

This release is causing an issue with django and the django-db backend.

Here is a stacktrace of a sample error. I would be happy to file an issue if you prefer:

```
File "/app/orbik/notifications/base.py", line 125, in _send
    tasks.send_email.delay(
  File "/usr/local/lib/python3.10/site-packages/celery/app/task.py", line 425, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/task.py", line 572, in apply_async
    return self.apply(args, kwargs, task_id=task_id or uuid(),
  File "/usr/local/lib/python3.10/site-packages/celery/app/task.py", line 793, in apply
    ret = tracer(task_id, args, kwargs, request)
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 518, in trace_task
    task.backend.mark_as_done(
  File "/usr/local/lib/python3.10/site-packages/celery/app/task.py", line 1091, in backend
    return self.app.backend
  File "/usr/local/lib/python3.10/site-packages/celery/app/base.py", line 1252, in backend
    self._local.backend = new_backend = self._get_backend()
  File "/usr/local/lib/python3.10/site-packages/celery/app/base.py", line 955, in _get_backend
    backend, url = backends.by_url(
  File "/usr/local/lib/python3.10/site-packages/celery/app/backends.py", line 69, in by_url
    return by_name(backend, loader), url
  File "/usr/local/lib/python3.10/site-packages/celery/app/backends.py", line 47, in by_name
    aliases.update(load_extension_class_names(extension_namespace))
  File "/usr/local/lib/python3.10/site-packages/celery/utils/imports.py", line 146, in load_extension_class_names
    yield ep.name, ':'.join([ep.module_name, ep.attrs[0]])
AttributeError: 'EntryPoint' object has no attribute 'module_name'
```

**If I pin the version to 5.2.4 everything works as expected.**

**Comment by thedrow** [comment]
Hi @jensenbox .

Please do, we'll address this shortly if you provide a reproducible test case.

**Comment by auvipy** [comment]
we got a PR without test though https://github.com/celery/celery/pull/7406

**Pull request merged**
