### PR TITLE
WIP: Fix some tests

### PR DESCRIPTION
**Pull request by SharpEdgeMarshall**
## Description

@auvipy Fix #5592 and other tests

### CODE REVIEW

**Comment by SharpEdgeMarshall** [comment]
@auvipy so I'm doing some local tests.
- integration-rabbitmq doesn't pass because that test should be disabled if there is rpc as a backend result and i've fixed it.
- integration-<others> don't pass because when you use `redis` as broker `inspect` commands don't works but I still don't know why.

**Comment by auvipy** [comment]
same error as my PR AttributeError: 'NoneType' object has no attribute 'values'  you can push on my branch as well

**Comment by SharpEdgeMarshall** [comment]
this commit was working https://github.com/celery/celery/tree/65a73be071befe1ac58e909fefa4e93747b1ea2c

**Comment by auvipy** [comment]
can't see the codes. anyway, better push on my branch with git co-author.

**Comment by SharpEdgeMarshall** [comment]
@auvipy please could you reopen this? I've done all the work on this branch and now all tests are fixed.

**Comment by SharpEdgeMarshall** [comment]
I reverted kombu to 4.5.0 because 4.6.1 broke `inspect` commands with `redis`

**Pull request closed without merging**
