### PR TITLE
Use Cherami as a broker

### PR DESCRIPTION
**Pull request by bluestann**
Hi, 

I have added support for celery to use [Cherami](https://eng.uber.com/cherami/) as a broker.

### CODE REVIEW

**Comment by datoug** [comment]
@auvipy @atombrella @georgepsarakis Do you mind take a look at this PR?

**Comment by bluestann** [comment]
The changes to Kombu to support Cherami is: [here](https://github.com/celery/kombu/pull/782).

**Comment by thedrow** [comment]
I have to say I'm very reluctant to add more maintenance burden on the project.
Let me think about it.

**Comment by auvipy** [comment]
I would be glad to add this though it will add more maintenance burden. but It might open door for more contributions from user engineering team?

**Comment by thedrow** [comment]
Thank you for your contribution but the project is now discontinued.

**Pull request closed without merging**
