### PR TITLE
Add encode to meta task in base.py

### PR DESCRIPTION
**Pull request by Anakael**
Fix bug with impossibility to load None from task meta.

### CODE REVIEW

**Comment by Anakael** [comment]
Yes, I can.
O think I'll do that today.

**Comment by Anakael** [comment]
`File "/home/shchemeldmitry/Documents/ivy_tools_microservice/env/lib/python3.7/site-packages/celery/result.py", line 473, in state
    return self._get_task_meta()['status']
  File "/home/shchemeldmitry/Documents/ivy_tools_microservice/env/lib/python3.7/site-packages/celery/result.py", line 412, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/home/shchemeldmitry/Documents/ivy_tools_microservice/env/lib/python3.7/site-packages/celery/backends/base.py", line 386, in get_task_meta
    meta = self._get_task_meta_for(task_id)
  File "/home/shchemeldmitry/Documents/ivy_tools_microservice/env/lib/python3.7/site-packages/celery/backends/mongodb.py", line 211, in _get_task_meta_for
    'result': self.decode(obj['result']),
  File "/home/shchemeldmitry/Documents/ivy_tools_microservice/env/lib/python3.7/site-packages/celery/backends/mongodb.py", line 179, in decode
    return super(MongoBackend, self).decode(data)
  File "/home/shchemeldmitry/Documents/ivy_tools_microservice/env/lib/python3.7/site-packages/celery/backends/base.py", line 312, in decode
    accept=self.accept)
  File "/home/shchemeldmitry/Documents/ivy_tools_microservice/env/lib/python3.7/site-packages/kombu/serialization.py", line 263, in loads
    return decode(data)
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/shchemeldmitry/Documents/ivy_tools_microservice/env/lib/python3.7/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/home/shchemeldmitry/Documents/ivy_tools_microservice/env/lib/python3.7/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/home/shchemeldmitry/Documents/ivy_tools_microservice/env/lib/python3.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/home/shchemeldmitry/Documents/ivy_tools_microservice/env/lib/python3.7/site-packages/kombu/serialization.py", line 263, in loads
    return decode(data)
  File "/home/shchemeldmitry/Documents/ivy_tools_microservice/env/lib/python3.7/site-packages/kombu/utils/json.py", line 91, in loads
    return _loads(s)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
kombu.exceptions.DecodeError: Expecting value: line 1 column 1 (char 0)`

I can't reproduce this behavior by tests. I got that traceback when i had None in meta['result'] in mongodb backend. By the code its allright.

**Comment by georgepsarakis** [comment]
Thanks for your contribution! I am not sure whether this is the right fix. Result should already be encoded from here: https://github.com/celery/celery/blob/984fb5f9daf338406823956e3d553096b6448c17/celery/backends/base.py#L405

Can you please provide any sample code to reproduce the error?

**Comment by Anakael** [comment]
Yeah, I'll try today.
Maybe is there some breaking changes from 4.3.0 to 4.4.0?

**Comment by Anakael** [comment]
tasks.py:
```
from celery import Celery
import time

app = Celery('tasks,', broker='mongodb://', backend='mongodb://')


@app.task
def task():
	time.sleep(10)
	print('lol')
```

main.py:
```
from tasks import task

def main():
	result = task.delay()
	print(result.state) # Fine
	result.get()
	print(result.state) # Trace


if __name__ == "__main__":
	main()
```

**Comment by Anakael** [comment]
I added some debug print:
`print(f'isinstance(payload, str) = {isinstance(payload, str)}')`
in *base.py:decode(str 326)*
returns True. It means that encoding works right.
How about such solution:
```
    def decode(self, payload):
        if not payload:
            return payload
        payload = PY3 or str(payload)
        return loads(payload,
                     content_type=self.content_type,
                     content_encoding=self.content_encoding,
                     accept=self.accept)
```
?

**Comment by Anakael** [comment]
```
loads(None,content_type='application/json', content_encoding='utf-8') # Fine
loads('None',content_type='application/json', content_encoding='utf-8') # Trace
```
The root of problem is here.

**Comment by georgepsarakis** [comment]
Have you perhaps found how the `None` object is passed as payload? Because normally the payload should be the serialized (encoded) object. Unfortunately I could not locate the reason for the conversion to string: https://github.com/celery/celery/blob/77099b876814ec0008fd8da18f35de70deccbe03/celery/backends/base.py#L325

To summarize the problem parameters:
- JSON serializer
- MongoDB results backend
- task returns `None` as a result

I will debug a bit more with [your sample](https://github.com/celery/celery/pull/5894#issuecomment-570672658).

**Comment by Anakael** [comment]
obj['result'] contains None. Are we really need to encode None?

The for conversion is compatibility with python 2, I think.

**Comment by Anakael** [comment]
See the last commit in mongodb: 
File: mongodb.py
Line: 191
Encoding result was lost.
So, we can just add serialization result after get meta in mongodb.py
I'll commit it today.

**Comment by Anakael** [comment]
I can't find way where `mark_as_done` is called. It function, that call store_result.

**Comment by auvipy** [comment]
the patch coverage needs to be increased!

**Pull request merged**
