### PR TITLE
Adding 'shadow' property to as_task_v2

### PR DESCRIPTION
**Pull request by jmdacruz**
Attempt at fixing #4347

### CODE REVIEW

**Comment by jmdacruz** [comment]
I can confirm this PR fixes issue #4347  (in monitoring tools such as flower):

image

Logs are also "partially" fixed (the "received" log entries show the shadow name, but the "succeeded" log entries show the real name):

```
[2017-10-28 17:39:17,760: INFO/MainProcess] Received task: foo[fcfbb11e-f565-4630-8aa6-eac3434226c1]
[2017-10-28 17:39:17,762: INFO/MainProcess] Received task: bar[f1ac07ad-bc60-4ec2-a6b5-b246dec4ce01]
[2017-10-28 17:39:17,771: INFO/ForkPoolWorker-4] Task tasks.add[fcfbb11e-f565-4630-8aa6-eac3434226c1] succeeded in 0.00656166800763s: 4
[2017-10-28 17:39:17,771: INFO/ForkPoolWorker-5] Task tasks.add[f1ac07ad-bc60-4ec2-a6b5-b246dec4ce01] succeeded in 0.00663297998835s: 6
```

**Comment by hclihn** [comment]
The single-line commit in `celery/app/amqp.py` did not fix the issue entirely as it was pointed out in the earlier comment. To fix this issue in the "received" log entries, you need to fix the following places in `celery/celery/app/trace.py`:

1. In the `TraceInfo` class, add a static method `get_name()` at line 154:
```python
     def __init__(self, state, retval=None):
          ....

+    @staticmethod
+    def get_name(task, req):
+        return req.shadow if hasattr(req, 'shadow') else task.name

     def handle_error_state(self, task, req,
         ...
```
2. In the `handle_retry` method, modify `name` in `info(LOG_RETRY, {...` to:
```python
            ....
             info(LOG_RETRY, {
                 'id': req.id,
-                'name': task.name,
+                'name': self.get_name(task, req),
                 'exc': text_t(reason),
             })
            ...
```
3. In the `_log_error` method, modify `name` in `context = {...` to:
```python
         ...
         context = {
             'hostname': req.hostname,
             'id': req.id,
-            'name': task.name,
+            'name': self.get_name(task, req),
             'exc': exception,
             'traceback': traceback,
             'args': sargs,
             'kwargs': skwargs,
             'description': policy.description,
             'internal': einfo.internal,
         }
         ...
```
4. In `trace_task()` inside `build_tracer()`:
  * Add `the_name` variable at line 363 as:
```python
     root_id = task_request.root_id or uuid
+    the_name = request['shadow'] if 'shadow' in request else name
     push_request(task_request)
```

* Modify `name` in `info(LOG_SUCCESS, {...` at line 451 to:
```python
                         ...
                         if _does_info:
                             info(LOG_SUCCESS, {
-                                'id': uuid, 'name': name,
+                                'id': uuid, 'name': the_name,
                                 'return_value': Rstr, 'runtime': T,
                             })
                         ...
```

These will fix the "received" log/trace entries. On the other hand, the `shadow_name` option in the `@app.task()` decorator (which overrides the `shadow_name` method in the `Task` class) and the `shadow` keyword argument of `Task.apply_async()` don't work as advertised. One way to fix it is to modify line 528 in the `apply_async` method of the `Task` class in `celery/celery/app/task.py` to:
```python
         ...
         # add 'self' if this is a "task_method".
         if self.__self__ is not None:
             args = args if isinstance(args, tuple) else tuple(args or ())
             args = (self.__self__,) + args
-            shadow = shadow or self.shadow_name(args, kwargs, options)
+        shadow = shadow or self.shadow_name(args, kwargs, options)
         ...
``` 
This moves the `shadow=...` out of the `if self.__self__ is not None:` block and allows `shadow` to be set by the `shadow` keyword argument of `Task.apply_async()` or the `shadow_name` method in the `Task` class (via, say, the `shadow_name` option in the `@app.task()` decorator).

**Comment by jmdacruz** [comment]
@hclihn Looks good to me. You may want to provide a different PR, since I don't think merged PRs can be modified or re-opened (is this corrrect, @georgepsarakis ?)

**Comment by hclihn** [comment]
New PRs (#4379 and #4381) have been created per suggestion. :-)

**Pull request merged**
