### PR TITLE
support redis 5.x

### PR DESCRIPTION
**Pull request by dulmandakh**
## Description

support redis-py 5.x, as there is no breaking change except dropping Python 3.7 support, https://github.com/redis/redis-py/releases/tag/v5.0.0

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
we need to ensure it works with kombu well ffirst

**Comment by auvipy** [comment]
depends on https://github.com/celery/kombu/pull/1790

**Review by auvipy — APPROVED** [review]
it is also passing in kombu so approving

**Comment by dulmandakh** [comment]
@auvipy could you please release a new version with the change.

**Comment by auvipy** [comment]
Not before sept 30

**Comment by Nusnus** [comment]
> Not before sept 30

@auvipy if you don't have any objections I can take care of that over the weekend.

Redis 5 can be a nice upgrade indeed!

P.S
Also relevant for Kombu

**Comment by Nusnus** [comment]
> > Not before sept 30
> 
> @auvipy if you don't have any objections I can take care of that over the weekend.
> 
> Redis 5 can be a nice upgrade indeed!
> 
> P.S
> Also relevant for Kombu 

We can also finish the new patch release policy and try it out already to see if it works as expected, I'm eager to get it done so I can find time to handle the release soon if you're ok with that bro @auvipy

**Comment by auvipy** [comment]
let us first complete the release process template then we could go for it

**Comment by Nusnus** [comment]
@auvipy 
> let us first complete the release process template then we could go for it

See new updates on the PR.



> also we might need to revert another PR. Let me handle the next release first, but if i can't manage enough time, I will ping you to do so instead of me

Sure np!
Take notes as you follow the new checklist so we can have a detailed feedback and know what works/comfrotable and what still requires refining. Your experience would be very valuable!

**Pull request merged**
