### PR TITLE
Fix a race condition when publishing a very large chord header

### PR DESCRIPTION
**Pull request by thedrow**
*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

Sometimes when publishing a chord with a large header a race condition occurs
when the group result isn't saved before one of the tasks of the header completes.

This regression was introduced in #4443 when the saving of the group result was moved after
publishing the chord's header.

Even after rearranging the code so that `header_result.save()` would come first
there was a problem since the code that freezes the group didn't use the same task_id
as the one that the group was published with.
This is now also fixed.

### CODE REVIEW

**Comment by thedrow** [comment]
@AlexHill Any change that you'll take a look here since you're the one who introduced this regression?
@auvipy Waiting for your LGTM...

**Comment by auvipy** [comment]
sadly all the integration tests are failing! can you check that?

**Comment by thedrow** [comment]
> sadly all the integration tests are failing! can you check that?

Sure.

**Comment by auvipy** [comment]
if you can fix it I can release another RC today or tomorrow and final version of 4.4 on November 7.

**Pull request merged**
