### PR TITLE
Use hub.remove_writer instead of hub.remove for write fds (#4185)

### PR DESCRIPTION
**Pull request by IdanHaim**
- fix main process Unrecoverable error: AssertionError() when read fd is deleted
- see https://github.com/celery/celery/issues/4185#issuecomment-2139390090
- tests:
    - change hub.remove to hub.remove_writer in test_poll_write_generator and test_poll_write_generator_stopped
    - add 2 more tests for schedule_writes to assert only hub.writers is removed when hub.readers have the same fd id

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
the change seems to be reasonable. would you mind to add/adjust some relevant tests for this to verify this?

**Comment by IdanHaim** [comment]
@auvipy, what do you have in mind?

**Review by auvipy — CHANGES_REQUESTED** [review]
thanks for the tests. can you please check the test failures?

**Comment by auvipy** [comment]
are the CI failures due to network issues? or due to code changes? I'm bit confused

**Comment by IdanHaim** [comment]
@auvipy I fixed the issue.

**Comment by IdanHaim** [comment]
@auvipy One test failed with a timeout for RUN tox
```
  3.12-smoke: 309355 I exit 0 (258.67 seconds) /home/runner/work/celery/celery> pytest -xsvv t/smoke --dist=loadscope --reruns 10 --reruns-delay 60 --rerun-except AssertionError -n auto -k test_canvas.py pid=3280 [tox/execute/api.py:286]
.pkg: 309356 D delete package /home/runner/work/celery/celery/.tox/.tmp/package/1/celery-5.4.0-0.editable-py3-none-any.whl [tox/tox_env/python/virtual_env/package/pyproject.py:224]
  3.12-smoke: OK (308.68=setup[50.00]+cmd[258.67] seconds)
  congratulations :) (309.22 seconds)
Error: The action 'Run tox for "3.12-smoke"' has timed out after 5 minutes.
```
I didn't touch this area and don't see how this can be related to what I added
can you help me here? do we need to rerun this?

**Comment by Nusnus** [comment]
The smoke tests failures are flakey situations, don't worry.

That being said, I think the API change of this PR needs to be updated in the docs too if I'm not mistaken. 

Let me see if I can find it quickly..

P.S
There's a reference for the remove() function, which probably just needs to be updated accordingly. Feel free to search for these references as well 🙂

**Comment by IdanHaim** [comment]
@Nusnus thanks for the response, I added another test for the missing coverage.
you mentioned There's a reference for the remove() function you mean in the tests or the code?
not all the needs to be changed, some calls are OK.

about the doc if something needs to be changed here I will see what I can do, point me to the right place.

**Comment by IdanHaim** [comment]
@auvipy @Nusnus I am done with code changes.
Everything I changed is covered by the tests. 
If anything else is needed please tell me.
The smoke test failure on timeout again, if this is fault failure we can merge if you approve.

**Comment by Nusnus** [comment]
> @Nusnus thanks for the response, I added another test for the missing coverage. you mentioned There's a reference for the remove() function you mean in the tests or the code? not all the needs to be changed, some calls are OK.
> 
> about the doc if something needs to be changed here I will see what I can do, point me to the right place.

Thank you!
I meant these docs - https://docs.celeryq.dev/en/stable/userguide/extending.html#worker-api
CleanShot 2024-06-15 at 13 58 40@2x

I’m not 100% sure it’s related to your changes but I wanted to give you the reference to check it out.



> @auvipy @Nusnus I am done with code changes. Everything I changed is covered by the tests. If anything else is needed please tell me. The smoke test failed on timeout again, if this is fault failure we can merge if you approve.

The smoke tests have some false negatives due to issues with Redis. This is something that we have to live with at the moment (e.g., restarting the CI) until the fix is released (https://github.com/celery/kombu/pull/2007).

**Comment by auvipy** [comment]
@Nusnus @IdanHaim  checking the docs and codes, my understanding is that, this PR is changing the usage of a Hub class attributes mostly and not removing anything from the original Hub implementation. so most likely the doc do not need to be changed here as it is mostly a change in implementation details. let me know if my analysis is right or not.

**Comment by IdanHaim** [comment]
@auvipy You are correct,
 the docs dont need to be changed.

**Pull request merged**
