### PR TITLE
Route chord_unlock task to the same queue as chord body

### PR DESCRIPTION
**Pull request by MelnykR**
*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

Fixes https://github.com/celery/celery/issues/6888

### CODE REVIEW

**Review by thedrow — CHANGES_REQUESTED** [review]
This was just the fix I had in mind so well done!
Could you please include a unit test in this patch to verify that this works as expected?

**Comment by thedrow** [comment]
The relevant test fails as the expected outcome has changed.
We need to adjust it before we merge this PR.

**Comment by MelnykR** [comment]
> This was just the fix I had in mind so well done!

Glad to hear that! That was the intention of creating issue and PR -- get feedback whether I am on the right path.


> The relevant test fails as the expected outcome has changed.
We need to adjust it before we merge this PR.

I guess I fixed existing tests. But I think new test should be also added. I will try to work on this on the weekend.

Thanks for the feedback!

**Review by auvipy — APPROVED** [review]

**Comment by auvipy** [comment]
thanks!

**Pull request merged**
