### PR TITLE
Proposed Documentation Updates related to task naming and beat schedules

### PR DESCRIPTION
**Pull request by idahogray**
*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

These are some suggestions for updating the documentation around task names and celery beat. I spent some time trying to get a task working in celery beat and it was because I incorrectly associated the task name with its import path. I was finally able to fix my issue by running `inspect registered`. Maybe these documentation updates will save others from my same confusion.

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
please fix the merge conflicts first

**Comment by auvipy** [comment]
please create a new branch on your fork and then contribute. you are doing work on your master branch which is not a good idea

**Comment by idahogray** [comment]
I originally made these changes in the Github web UI. I only intend to make these changes and then delete my fork. I can create a separate branch but I am not concerned about it being a problem on my end.

**Comment by auvipy** [comment]
your pr is not reviewable

**Comment by idahogray** [comment]
I don't understand why its not reviewable. I would appreciate any pointers to help me understand why for future reference. I closing this in favor of PR #7222.

**Comment by thedrow** [comment]
> I don't understand why its not reviewable. I would appreciate any pointers to help me understand why for future reference. I closing this in favor of PR #7222.

The changes you made are for the entire document. Your editor probably did something.

**Comment by idahogray** [comment]
> > I don't understand why its not reviewable. I would appreciate any pointers to help me understand why for future reference. I closing this in favor of PR #7222.
> 
> The changes you made are for the entire document. Your editor probably did something.

I wonder if maybe my problem was that I didn't notice I was on the wrong branch in the Github when I started editing in the web UI. I thought I was on Master, but I realize now that maybe I wasn't. Thanks for the help.

**Pull request closed without merging**
