### PR TITLE
Added autoretry decorator

### PR DESCRIPTION
**Pull request by malinoff**
Refs #1608

### CODE REVIEW

**Comment by JocelynDelalande** [comment]
@malinoff great proposal, is that still relevant, what do you think about @lukmdo  remark ?

**Comment by JocelynDelalande** [comment]
Suggestion : allow to retry on all exceptions (excluding celery's, otherwise, it would mask retries, reject and so on...), maybe with a special arg value, or via another kw argument ?

That approach is maybe related to #2643 approach.

**Comment by thedrow** [comment]
@malinoff Since you're a maintainer now can you please take a look at this PR again?

**Comment by malinoff** [comment]
@thedrow I don't have time right now, but I'll try to review this again on the next week

**Comment by JocelynDelalande** [comment]
bump ?

**Comment by joshowen** [comment]
+1

**Comment by joshowen** [comment]
@malinoff any thoughts on including this?  I've been using it monkey patched for a month now, and it is great.

**Comment by thedrow** [comment]
@joshowen Merged. Thanks.

**Pull request merged**
