### PR TITLE
Control pattern matching

### PR DESCRIPTION
**Pull request by jheld**
*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

work based off #2123 with some rebasing. most work is implemented on the kombu side (and which will need to be merged first!) https://github.com/celery/kombu/pull/997

### CODE REVIEW

**Comment by jheld** [comment]
The build is partially failing due to kombu. The kombu branch was merged, so I'm a bit confused why it would still fail.

**Comment by auvipy** [comment]
this pr is not using kombu master :)

**Comment by thedrow** [comment]
@jheld I can't rebase this.
Please allow me to collaborate on this branch.

**Comment by thedrow** [comment]
Nevermind, looks like this is good to go.

**Pull request merged**
