### PR TITLE
Revert "Revert "Add Semgrep to CI""

### PR DESCRIPTION
**Pull request by auvipy**
Reverts celery/celery#8477

### CODE REVIEW

**Comment by auvipy** [comment]
I'm not sure where it is being used? is it used in your company?

**Comment by auvipy** [comment]
image
 says it needs configuration. if you use it privately I suggest configure it to your company fork, but let me know what we got from this so far from a open source points of view

**Review by Nusnus — APPROVED** [review]

**Comment by Nusnus** [comment]
We were indeed checking it out via a fork to assess the value it has from an open source point of view as you mentioned, which unfortunately did not come to completion due to the events of the recent months in our team.

My complaint was removing it without discussion. Not that there is no legitimate case for removing it.
You declined their offer but we didn't for the sake of checking if it brings actual value which gave us access to their dashboard which I do watch weekly for High/Critical security findings in Celery and Kombu.

@auvipy

**Comment by auvipy** [comment]
I see. i thought it was not actually working. care to invite me on the dashboard please?

**Pull request merged**
