### PR TITLE
Adding redis sentinel backend

### PR DESCRIPTION
**Pull request by geoffreybauduin**
## Description

A pull request was opened a few months ago (#4053), but it seems to me that the code is a bit violating the scheme in place, bypassing result_backend_url and result_backend_transport_options configurations.

I'm testing this code on a dev environment atm.

### CODE REVIEW

**Comment by geoffreybauduin** [comment]
@thedrow I just addressed those issues.

I am not sure how I can fix the appveyor build though, I haven't found why it would not be able to find the "sentinel" module. Any hints?

**Comment by thedrow** [comment]
@geoffreybauduin I don't see any import errors in the build. There's some pydocstyle failures though.

**Comment by geoffreybauduin** [comment]
@thedrow sorry for the delay, this is coming up as a priority at work so I should be able to work on this faster this time.

Here's the result on appveyor:

```
=================================== ERRORS ====================================
_____________ ERROR at setup of test_SentinelBackend.test_reduce ______________
self = <t.unit.backends.test_redis.test_SentinelBackend instance at 0x06C6FD78>
>   ???
t\unit\backends\test_redis.py:449: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <t.unit.backends.test_redis._SentinelBackend object at 0x0702EDD0>
args = (), kwargs = {'app': <Celery celery.tests at 0x705db90>}
>   ???
E   ImportError: Cannot import module sentinel
celery\backends\redis.py:359: ImportError
____________ ERROR at setup of test_SentinelBackend.test_no_redis _____________
self = <t.unit.backends.test_redis.test_SentinelBackend instance at 0x067ED760>
    def setup(self):
        self.Backend = self.get_backend()
        self.E_LOST = self.get_E_LOST()
>       self.b = self.Backend(app=self.app)
t\unit\backends\test_redis.py:449: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <t.unit.backends.test_redis._SentinelBackend object at 0x0705D110>
args = (), kwargs = {'app': <Celery celery.tests at 0x70400b0>}
>   ???
E   ImportError: Cannot import module sentinel
celery\backends\redis.py:359: ImportError
_______________ ERROR at setup of test_SentinelBackend.test_url _______________
self = <t.unit.backends.test_redis.test_SentinelBackend instance at 0x06FFD8F0>
    def setup(self):
        self.Backend = self.get_backend()
        self.E_LOST = self.get_E_LOST()
>       self.b = self.Backend(app=self.app)
t\unit\backends\test_redis.py:449: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <t.unit.backends.test_redis._SentinelBackend object at 0x0705D6B0>
args = (), kwargs = {'app': <Celery celery.tests at 0x6c733f0>}
    def __init__(self, *args, **kwargs):
        if not sentinel:
>           raise ImportError("Cannot import module sentinel")
E           ImportError: Cannot import module sentinel
celery\backends\redis.py:359: ImportError
____________ ERROR at setup of test_SentinelBackend.test_get_pool _____________
self = <t.unit.backends.test_redis.test_SentinelBackend instance at 0x06881B20>
    def setup(self):
        self.Backend = self.get_backend()
        self.E_LOST = self.get_E_LOST()
>       self.b = self.Backend(app=self.app)
t\unit\backends\test_redis.py:449: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <t.unit.backends.test_redis._SentinelBackend object at 0x070641D0>
args = (), kwargs = {'app': <Celery celery.tests at 0x6b6d930>}
    def __init__(self, *args, **kwargs):
        if not sentinel:
>           raise ImportError("Cannot import module sentinel")
E           ImportError: Cannot import module sentinel
celery\backends\redis.py:359: ImportError
```

(https://ci.appveyor.com/project/ask/celery/build/1.0.1663/job/kodp1ku17ng0u6r0)

**Comment by thedrow** [comment]
I guess that the redis package is not installed on windows.
See https://github.com/celery/celery/blob/master/extra/appveyor/install.ps1

**Comment by geoffreybauduin** [comment]
@thedrow the issue was located inside the unit tests, I patched the `SentinelBackend` class to behave like `RedisBackend` does, storing the module inside the class to have it overridden inside the unit test.

I still have to test things out live, but the theory seems ok now.

**Comment by thedrow** [comment]
Let me know when this is ready for merge.

**Comment by geoffreybauduin** [comment]
@thedrow I rebased on master, and documented the feature (as well as renaming the transport_option configuration name, from `result_transport_options` to `result_backend_transport_options` to match the naming convention setup for result backend settings.

I also documented the feature inside the Getting Started / Redis / Broker page, as well as the global configuration page (inside the Task result backend category)

**Comment by geoffreybauduin** [comment]
@thedrow the PR looks functional.

```
[2017-09-20 16:09:39,978: INFO/MainProcess] Connected to sentinel://127.0.0.1:32770/0
[2017-09-20 16:09:42,359: DEBUG/MainProcess] celery@worker.eb1753ab7782 joined the party
[2017-09-20 16:09:46,479: INFO/MainProcess] Received task: task[8c7a5c71-a302-4a73-aac0-5691933aa738]  
[2017-09-20 16:09:46,480: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7f493e64bc80> (args:(u'task', u'8c7a5c71-a302-4a73-aac0-5691933aa738', {u'origin': u'gen22@6174eea4542a', u'lang': u'py', u'task': u'task', u'group': None, u'root_id': u'8c7a5c71-a302-4a73-aac0-5691933aa738', u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': u'celery', u'exchange': u''}, u'expires': None, u'correlation_id': u'8c7a5c71-a302-4a73-aac0-5691933aa738', u'retries': 0, u'timelimit': [None, None], u'argsrepr': u'()', u'eta': None, u'parent_id': None, u'reply_to': u'85cf9b26-bc9d-3d0f-8a0b-f0cab47a37ad', u'id': u'8c7a5c71-a302-4a73-aac0-5691933aa738', u'kwargsrepr': u'{}'}, '[[], {}, {"chord": null, "callbacks": null, "errbacks": null, "chain": null}]', u'application/json', u'utf-8') kwargs:{})
[2017-09-20 16:09:46,482: WARNING/ForkPoolWorker-1] Hey
[2017-09-20 16:09:46,483: DEBUG/MainProcess] Task accepted: task[8c7a5c71-a302-4a73-aac0-5691933aa738] pid:12
[2017-09-20 16:09:46,491: INFO/ForkPoolWorker-1] Task task[8c7a5c71-a302-4a73-aac0-5691933aa738] succeeded in 0.0091449432075s: 'This is ok'
```

```
127.0.0.1:6379> select 1
OK
127.0.0.1:6379[1]> keys *
1) "celery-task-meta-8c7a5c71-a302-4a73-aac0-5691933aa738"
```

Sorry for the commit mess, I believe it should be squashed during the merge.

**Comment by thedrow** [comment]
Can you please address the build failures again?

**Comment by geoffreybauduin** [comment]
@thedrow done, it was flake8 issues.

**Comment by geoffreybauduin** [comment]
@thedrow it seems the build is still failing, but it looks more like a network issue than an issue with this PR (https://travis-ci.org/celery/celery/jobs/278127092 -> TOXENV=integration-dynamodb -> E: Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/main/j/java-common/default-jre_1.7-51_amd64.deb  503  Service Unavailable [IP: 104.154.33.93 80]).

Are you able to restart the build or should I push another commit / close - reopen this PR to trigger the build again?

**Comment by thedrow** [comment]
Thanks!

**Pull request merged**
