### PR TITLE
Propagate arguments to chains inside groups

### PR DESCRIPTION
**Pull request by Chris7**
This addresses issue #4430 that may be a duplicate of #3968. 

Arguments were not propagated to chains within groups because in the `apply_async` method of `group`, `self._prepared` is called without partial arguments (as shown)
```
    options, group_id, root_id = self._freeze_gid(options)
    tasks = self._prepared(self.tasks, [], group_id, root_id, app)
    p = barrier()
    results = list(self._apply_tasks(tasks, producer, app, p,
                                         args=args, kwargs=kwargs, **options))
```

Consequentially, in `self._prepared`, when the task is frozen and no arguments have been passed, the task becomes frozen without any arguments.

```
    if partial_args and not task.immutable:
        task.args = tuple(partial_args) + tuple(task.args)
    yield task, task.freeze(group_id=group_id, root_id=root_id
```

Thus, a frozen chain has been created with no input arguments. It seems this is done because the subsequent call to `apply_tasks` is supposed to parameterize the tasks with arguments. However, in the `run` method of `_chain`, if a task is frozen, the arguments are not updated and it is run as follows:
```
        if self._frozen:
            tasks, results = self._frozen
        else:
            tasks, results = self.prepare_steps(
                args, self.tasks, root_id, parent_id, link_error, app,
                task_id, group_id, chord,
            )
```

Thus, because the frozen tasks and results were not provided the input arguments, they are ignored. To fix this, I simply removed the condition on `self._frozen`. 

I did this without knowing exactly the reason for frozen and hoping the unit tests would prove if this was a bad idea. This is a very important issue to me, so I'd love additional feedback if this is an unsuitable fix and how it should be implemented.

### CODE REVIEW

**Comment by Chris7** [comment]
Another fix to this is passing args in `self._prepared` and not passing args in `self._apply_tasks`.

**Comment by Chris7** [comment]
I think it might be a bad cache on travis, as it's passing locally. Going to close/reopen to force a rebuild.

**Comment by Chris7** [comment]
Just needed to rebase, I'll check it out. Thanks for your quick response

**Comment by auvipy** [comment]
looks like unit test is failing now, however I have restarted the build

**Comment by auvipy** [comment]
@AlexHill do you have time to share some insight?

**Comment by Chris7** [comment]
@auvipy It failed because of my second commit that removed the `_frozen` attribute, as I thought it was confusing to leave it around if it was unused. I see the test cases are referencing it though to extract tasks to perform. I'm curious why the cache is needed for _chain but not other methods.

**Comment by Chris7** [comment]
Here is the commit introducing `_frozen`: https://github.com/celery/celery/commit/1e3fcaa969de6ad32b52a3ed8e74281e5e5360e6

Without _frozen, the special case of `group(A.s() | group(B.s(), C.s()))` is still supported. I added in an additional test to confirm this as there were no unit tests added in that commit.

**Comment by auvipy** [comment]
thanks for digging it

**Comment by Chris7** [comment]
Thanks for the quick turnaround!

**Pull request merged**
