### PR TITLE
mongodb default options removed.

### LINKED ISSUE #2579: pymongo refuses backend/mongodb.py default settings
`self.options.setdefault('max_pool_size', self.max_pool_size)`
`self.options.setdefault('auto_start_request', False)`

These lines are refusing from `pymongo` and gives `ConfigurationError` exception. By the way pymongo version is 3.0 and for use mongodb as backend i have to remove that lines from mongodb.py.

### PR DESCRIPTION
**Pull request by fatihsucu**
Fixes #2579

### CODE REVIEW

**Comment by thedrow** [comment]
I think that this code should branch based on PyMongo's version.
If it's version 3 and above don't set the defaults.

**Comment by PMickael** [comment]
I think, It would be better to treat the exception !

**Comment by ionelmc** [comment]
Turns out `max_pool_size` was renamed to `maxPoolSize`. The other option is removed in 3.0 (it had something to do with read-after-write preference, see https://github.com/mongodb/mongo-python-driver/blob/master/doc/changelog.rst#classpymongomongo_clientmongoclient-changes )

@fatihsucu will you update the PR to have version check and only set `maxPoolSize` on 3.0 ?

**Comment by fatihsucu** [comment]
Yes, i will @ionelmc

**Comment by PMickael** [comment]
Great thanks.
Add you're name to contributor if you want.

**Comment by fatihsucu** [comment]
Thanks for comments and advice. It would be great.

**Comment by ask** [comment]
Wow, these mongo folks sure love pointless and backward incompatible changes ;)

**Comment by ask** [comment]
Also applied to 3.1

**Pull request merged**
