### PR TITLE
relaxed click version

### PR DESCRIPTION
**Pull request by auvipy**

### CODE REVIEW

**Comment by thedrow** [comment]
Please hold off merging this as we're going to release 5.1.1 first once I finish up with a few patches.

**Comment by auvipy** [comment]
ok

**Comment by mweinelt** [comment]
Calling the CLI with no args results in the following traceback with these relaxed dependencies on 5.1.1.

```pytb
Traceback (most recent call last):
  File "/nix/store/2k70q69lvbhs1bmjvjgxj2paaxrqdwmi-python3.8-celery-5.1.1/bin/.celery-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/2k70q69lvbhs1bmjvjgxj2paaxrqdwmi-python3.8-celery-5.1.1/lib/python3.8/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "/nix/store/2k70q69lvbhs1bmjvjgxj2paaxrqdwmi-python3.8-celery-5.1.1/lib/python3.8/site-packages/celery/bin/celery.py", line 213, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/nix/store/s6a73ssai10wpz50nnk2cy3k48wydl05-python3.8-click-8.0.1/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/s6a73ssai10wpz50nnk2cy3k48wydl05-python3.8-click-8.0.1/lib/python3.8/site-packages/click/core.py", line 1061, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/nix/store/s6a73ssai10wpz50nnk2cy3k48wydl05-python3.8-click-8.0.1/lib/python3.8/site-packages/click/core.py", line 923, in make_context
    self.parse_args(ctx, args)
  File "/nix/store/s6a73ssai10wpz50nnk2cy3k48wydl05-python3.8-click-8.0.1/lib/python3.8/site-packages/click/core.py", line 1624, in parse_args
    rest = super().parse_args(ctx, args)
  File "/nix/store/s6a73ssai10wpz50nnk2cy3k48wydl05-python3.8-click-8.0.1/lib/python3.8/site-packages/click/core.py", line 1379, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/nix/store/s6a73ssai10wpz50nnk2cy3k48wydl05-python3.8-click-8.0.1/lib/python3.8/site-packages/click/core.py", line 2364, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/nix/store/s6a73ssai10wpz50nnk2cy3k48wydl05-python3.8-click-8.0.1/lib/python3.8/site-packages/click/core.py", line 2326, in process_value
    value = self.callback(ctx, self, value)
  File "/nix/store/s6a73ssai10wpz50nnk2cy3k48wydl05-python3.8-click-8.0.1/lib/python3.8/site-packages/click/core.py", line 1279, in show_help
    echo(ctx.get_help(), color=ctx.color)
  File "/nix/store/s6a73ssai10wpz50nnk2cy3k48wydl05-python3.8-click-8.0.1/lib/python3.8/site-packages/click/core.py", line 704, in get_help
    return self.command.get_help(self)
  File "/nix/store/s6a73ssai10wpz50nnk2cy3k48wydl05-python3.8-click-8.0.1/lib/python3.8/site-packages/click/core.py", line 1304, in get_help
    self.format_help(ctx, formatter)
  File "/nix/store/s6a73ssai10wpz50nnk2cy3k48wydl05-python3.8-click-8.0.1/lib/python3.8/site-packages/click/core.py", line 1335, in format_help
    self.format_options(ctx, formatter)
  File "/nix/store/s6a73ssai10wpz50nnk2cy3k48wydl05-python3.8-click-8.0.1/lib/python3.8/site-packages/click/core.py", line 1532, in format_options
    super().format_options(ctx, formatter)
  File "/nix/store/s6a73ssai10wpz50nnk2cy3k48wydl05-python3.8-click-8.0.1/lib/python3.8/site-packages/click/core.py", line 1355, in format_options
    rv = param.get_help_record(ctx)
  File "/nix/store/s6a73ssai10wpz50nnk2cy3k48wydl05-python3.8-click-8.0.1/lib/python3.8/site-packages/click/core.py", line 2727, in get_help_record
    default_value = self.get_default(ctx, call=False)
TypeError: get_default() got an unexpected keyword argument 'call'
```

**Comment by thedrow** [comment]
@mweinelt Thanks for the heads up!
I'll investigate.

**Comment by frenzymadness** [comment]
I've tried to fix the issue. It seems that the `get_default` method in click now accepts also `call` keyword argument which the method in `CeleryOption` does not expect.
https://github.com/celery/celery/blob/82fe649d8aed5145c5f05d3aabb88ea9721143d4/celery/bin/base.py#L141-L144
When I change it to:
```python
    def get_default(self, ctx, **kwargs):
        if self.default_value_from_context:
            self.default = ctx.obj[self.default_value_from_context]
        return super().get_default(ctx, **kwargs)
```
It works fine. Could anybody try it or should I open a new PR?

**Comment by thedrow** [comment]
I'll try it.

**Comment by ddevault** [comment]
It also seems that even correct usage causes apparently click-related issues:

```
[1:28:59] taiga ~/s/lists.sr.ht $ celery -A listssrht.process worker --loglevel INFO
Usage: celery worker [OPTIONS]
Try 'celery worker --help' for help.

Error: Invalid value for '-P' / '--pool': <class 'celery.concurrency.prefork.TaskPool'> is not one of 'prefork', 'eventlet', 'gevent', 'solo', 'processes', 'threads'.
```

Is anyone working on this? When celery gets out of sync with its dependencies, it makes it much harder to package it downstream.

**Comment by auvipy** [comment]
> I've tried to fix the issue. It seems that the `get_default` method in click now accepts also `call` keyword argument which the method in `CeleryOption` does not expect.
> 
> https://github.com/celery/celery/blob/82fe649d8aed5145c5f05d3aabb88ea9721143d4/celery/bin/base.py#L141-L144
> 
> When I change it to:
> 
> ```python
>     def get_default(self, ctx, **kwargs):
>         if self.default_value_from_context:
>             self.default = ctx.obj[self.default_value_from_context]
>         return super().get_default(ctx, **kwargs)
> ```
> 
> It works fine. Could anybody try it or should I open a new PR?

you can come with a PR

**Comment by graingert** [comment]
> It also seems that even correct usage causes apparently click-related issues:
> 
> ```
> [1:28:59] taiga ~/s/lists.sr.ht $ celery -A listssrht.process worker --loglevel INFO
> Usage: celery worker [OPTIONS]
> Try 'celery worker --help' for help.
> 
> Error: Invalid value for '-P' / '--pool': <class 'celery.concurrency.prefork.TaskPool'> is not one of 'prefork', 'eventlet', 'gevent', 'solo', 'processes', 'threads'.
> ```
> 
> Is anyone working on this? When celery gets out of sync with its dependencies, it makes it much harder to package it downstream.

I'm looking at it now, here's the traceback for that:
```
Traceback (most recent call last):
  File "/home/graingert/.virtualenvs/celery3/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/graingert/.virtualenvs/celery3/lib/python3.8/site-packages/click/core.py", line 1666, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/home/graingert/.virtualenvs/celery3/lib/python3.8/site-packages/click/core.py", line 923, in make_context
    self.parse_args(ctx, args)
  File "/home/graingert/.virtualenvs/celery3/lib/python3.8/site-packages/click/core.py", line 1379, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/graingert/.virtualenvs/celery3/lib/python3.8/site-packages/click/core.py", line 2364, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/home/graingert/.virtualenvs/celery3/lib/python3.8/site-packages/click/core.py", line 2320, in process_value
    value = self.type_cast_value(ctx, value)
  File "/home/graingert/.virtualenvs/celery3/lib/python3.8/site-packages/click/core.py", line 2307, in type_cast_value
    return convert(value)
  File "/home/graingert/.virtualenvs/celery3/lib/python3.8/site-packages/click/types.py", line 75, in __call__
    return self.convert(value, param, ctx)
  File "/home/graingert/projects/celery/celery/bin/worker.py", line 48, in convert
    value = super().convert(value, param, ctx)
  File "/home/graingert/.virtualenvs/celery3/lib/python3.8/site-packages/click/types.py", line 288, in convert
    self.fail(
  File "/home/graingert/.virtualenvs/celery3/lib/python3.8/site-packages/click/types.py", line 128, in fail
    raise BadParameter(message, ctx=ctx, param=param)
click.exceptions.BadParameter: <class 'celery.concurrency.prefork.TaskPool'> is not one of 'prefork', 'eventlet', 'gevent', 'solo', 'processes', 'threads'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/graingert/projects/celery/celery/bin/celery.py", line 214, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/home/graingert/.virtualenvs/celery3/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/graingert/.virtualenvs/celery3/lib/python3.8/site-packages/click/core.py", line 1080, in main
    sys.exit(e.exit_code)
SystemExit: 2
(Pdb) 
```

**Comment by graingert** [comment]
looks related to this change https://github.com/pallets/click/commit/0c108f22c7f87f6ea4657ffa2a54516dcd3548f6

**Comment by thedrow** [comment]
I'm closing this as this was superseded by #6861.

**Pull request closed without merging**
