### PR TITLE
Move pytest configuration from setup.cfg to pyproject.toml

### PR DESCRIPTION
**Pull request by matusvalo**
Pytest documentation does not recommend to use setup.cfg as pytest
confguration - see warning here:

https://docs.pytest.org/en/6.2.x/customize.html#setup-cfg

### CODE REVIEW

**Comment by matusvalo** [comment]
This PR is requirement for another PR fixing #6958. After merging this PR I will add final PR fixing #6958.

**Comment by auvipy** [comment]
I have one question, if there is anything in case that need to updated and save us fro copy pasting case utils then we should update that as well, I can take care of it.

**Review by auvipy — APPROVED** [review]

**Review by auvipy — COMMENTED** [review]
btw can our CI parse toml file?

**Comment by auvipy** [comment]
https://github.com/celery/celery/pull/7060/files

**Comment by auvipy** [comment]
can u just pull from master

**Comment by matusvalo** [comment]
done

**Review by auvipy — APPROVED** [review]

**Pull request merged**
