### PR TITLE
Run the windows build using tox

### PR DESCRIPTION
**Pull request by thedrow**
*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

Since the release of vine 5.0.0a1, the Windows build failed because it wasn't using pip to install it's dependencies.

It now uses tox which uses pip to install dependencies.

### CODE REVIEW

**Comment by auvipy** [comment]
any idea why still failing?

**Comment by thedrow** [comment]
Yes. I'm working on it.

**Comment by thedrow** [comment]
It seems like pytest is not recognizing our plugin so our marks don't work.
I'll figure it out...

**Comment by thedrow** [comment]
Ok so we need to release the latest kombu to fix this.

**Pull request closed without merging**
