### PR TITLE
Fix integration test

### PR DESCRIPTION
**Pull request by youtux**
Fix regression introduced in https://github.com/celery/celery/pull/8149 after disabling the `xfail` marker

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
can you please check the failing CI's please? what is causing them

**Comment by youtux** [comment]
Well, I think it was broken before my changes, since the test was marked with `xfail`, I just removed the marker in my previous PR. I'm not sure why it fails on CI, locally I can run it just fine.

**Comment by auvipy** [comment]
are they network issue?

**Comment by Nusnus** [comment]
Maybe use `@flaky` decorator?

**Comment by Nusnus** [comment]
Maybe try reverting the sleep back to `1` from `0.1`?

**Comment by youtux** [comment]
Raising the sleep interval to 1 sec didn't make any difference. My guess is that the worker is busy with some leftover jobs from previous tests, so maybe increasing the timeout here can make the test fail.

I'll try to see if this is the case.

**Comment by Nusnus** [comment]
Also checkout the `@flaky` decorator, it will allow automatic retries on the test so it might help here

**Comment by youtux** [comment]
At the moment I'm trying [detect-test-pollution](https://github.com/asottile/detect-test-pollution) locally, let's see if it shows anything.

```
detect-test-polllution \
    --failing-test t/integration/test_tasks.py::test_tasks::test_retry \
    --tests ./t/integration
```

**Comment by auvipy** [comment]
yeah https://github.com/celery/celery/pull/8149/files#diff-54d4be18ee565efaa7df051a720187dd5a35ff127d8ce23b34bc122ea9d420ddL330 removal of this is causing the issues

**Review by auvipy — APPROVED** [review]

**Pull request merged**
