### PR TITLE
daemonizing: If unsure choose "systemd".

### PR DESCRIPTION
**Pull request by guettli**
Most servers use systemd these days.

PR for #5315

### CODE REVIEW

**Comment by guettli** [comment]
Could you please do it? I just used the web interface of github, I don't have the git repo checked out.

**Comment by auvipy** [comment]
OK!!! could you allow maintainers to edit your pr settings?

**Comment by guettli** [comment]
"Allow edits from maintainers. " is activated.

**Comment by othalla** [comment]
@auvipy @guettli any news about it?

**Comment by guettli** [comment]
I think I have done everything I can do. I think only a maintainer can merge it now. I am not a maintainer.

**Comment by thedrow** [comment]
I still doesn't have push access to this fork...

**Comment by guettli** [comment]
since I don't know  how I can help, I have no clue. Maybe you just use copy+paste to get the changes.

**Comment by thedrow** [comment]
Thanks for the contribution and the heads up.

**Pull request closed without merging**
