### PR TITLE
Fixx the integration test erros

### PR DESCRIPTION
**Pull request by auvipy**
1. Release Kombu 4.6.2
2. Explicit assertions of Ping [Mostly by Fabio Tadaro]
3. Fixed test hang [Pulled from Fabio Tadaro's PR ]

### CODE REVIEW

**Comment by auvipy** [comment]
@nicoddemus can you suggest the proper fix?

**Comment by nicoddemus** [comment]
Is this to remove the warning about `assert None`?

**Comment by SharpEdgeMarshall** [comment]
Guys I was going crazy fixing this test failing in my PR!!!! Why are you merging broken things?

**Comment by devilicecream** [comment]
```
@flaky
    def test_parent_ids(self, manager, num=10):
>       assert manager.inspect().ping() is None
E       AssertionError: assert {'gen8927@travis-job-25ae7652-9bbf-4555-8791-dc4aa02f5827': {'ok': 'pong'}} is None
E        +  where {'gen8927@travis-job-25ae7652-9bbf-4555-8791-dc4aa02f5827': {'ok': 'pong'}} = <bound method Inspect.ping of <celery.app.control.Inspect object at 0x7f63baff2828>>()
E        +    where <bound method Inspect.ping of <celery.app.control.Inspect object at 0x7f63baff2828>> = <celery.app.control.Inspect object at 0x7f63baff2828>.ping
E        +      where <celery.app.control.Inspect object at 0x7f63baff2828> = <bound method ManagerMixin.inspect of <celery.contrib.testing.manager.Manager object at 0x7f63bb02f748>>()
E        +        where <bound method ManagerMixin.inspect of <celery.contrib.testing.manager.Manager object at 0x7f63bb02f748>> = <celery.contrib.testing.manager.Manager object at 0x7f63bb02f748>.inspect
```
This is what's happening. The fix would be to just reverse it to what it was before, namely:
```py
@flaky
def test_parent_ids(self, manager, num=10):
        assert manager.inspect().ping()
        ...
```
or, if you want to be more explicit:
```py
...
ping_result = manager.inspect().ping()
assert ping_result[ping_result.keys()[0]] == {"ok": "pong"}
...
```

**Comment by nicoddemus** [comment]
I'm guessing one of the reasons I (one of the pytest maintainers) was pinged is that pytest issues a warning on expressions that are evaluated as `assert None` because this is a common error with mocking being misused: `assert m.assert_called()`, which should be just `m.assert_called()` without the `assert`; somebody then changed some asserts incorrectly based on that warning.

**Comment by SharpEdgeMarshall** [comment]
@auvipy could you please revert the change and leave `assert manager.inspect().ping()` because it was working?

**Comment by nicoddemus** [comment]
It seems https://github.com/celery/celery/pull/5589/files was the culprit

**Comment by auvipy** [comment]
> Is this to remove the warning about `assert None`?

Yes, and also fix the failure...

**Comment by auvipy** [comment]
reverted and rebased

**Comment by auvipy** [comment]
what should be the actual fix for assertion?

**Comment by auvipy** [comment]
now?

**Comment by SharpEdgeMarshall** [comment]
@auvipy Man, I'm not understanding, what are you doing?
Why are you "taking" my commit when my PR is GREEN?
I've solved all the issues on the CI, required me an entire day, and now you are taking credits of my commits?
Please explain what are you doing, thank you.

**Comment by auvipy** [comment]
> @auvipy Man, I'm not understanding, what are you doing?
> Why are you "taking" my commit when my PR is GREEN?
> I've solved all the issues on the CI, required me an entire day, and now you are taking credits of my commits?
> Please explain what are you doing, thank you.

I am giving you proper credits, I told you to send on my branch. And your PR has some unrelated changes. which is why the related parts of your PR are pulled here.

**Comment by SharpEdgeMarshall** [comment]
@ask @thedrow Could you explain what's happening here?

**Pull request merged**
