### PR TITLE
Task name doc updates

### PR DESCRIPTION
**Pull request by idahogray**
*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

These are some suggestions for updating the documentation around task names and celery beat. I spent some time trying to get a task working in celery beat and it was because I incorrectly associated the task name with its import path. I was finally able to fix my issue by running `inspect registered`. Maybe these documentation updates will save others from my same confusion.

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
again, fetch/pull from master to your master branch, then try to contribute from a new local branch.

**Comment by idahogray** [comment]
I guess I still don't understand what you want. I have pulled from master to my local repo. I created a new branch in my fork for this pull request. I tried to merge master into the feature branch and it says its already up to date. I can't create a new branch in this upstream repo. 

I am not trying to be difficult or disrespectful, if you can point me to some instructions I will gladly follow them. However, I am not sure what else I can do so feel free to close this PR if you want.

**Comment by auvipy** [comment]
check this file  and tell me how should this be reviewed https://github.com/celery/celery/pull/7222/files

**Comment by idahogray** [comment]
This is what I see:
image

It only contains the changes I made to the one small part of the code. Again, I am sorry if I am doing something wrong, I just don't see it.

**Comment by auvipy** [comment]
this is what I see :D you have two file changed, check commits  and the 2nd file please ;)
image

**Comment by idahogray** [comment]
Okay, I see it now, sorry for this. I am closing this one and will create yet another one.

**Pull request closed without merging**
