### PR TITLE
WIP: Issue dates datetime

### PR DESCRIPTION
**Pull request by mvaled**
## Description

Provides a way to reproduce issue #7754

### CODE REVIEW

**Review by auvipy — COMMENTED** [review]
did you identified which part of celery could be causing the problem?

**Comment by mvaled** [comment]
Hi @auvipy,

This PR is merely a way to reproduce #7754; I don't really expect it to be merged like this.  The checklist of the issue is quite extensive.

I rather have a test case for this issue, but I need to remember how to introduce the tests that reproduce the issue.

**Comment by mvaled** [comment]
> did you identified which part of celery could be causing the problem?

I tried to reproduce the issue in `kombu` itself.  But when I modify kombu's simple task queue example I get the right behavior: i.e receiving a `date` in the consumer.

**Comment by mvaled** [comment]
@auvipy 

I pushed a commit with a WIP for test.  But I see that integration tests are not being run in the Github workflow.

I tried to run them myself like this:

```
TEST_BROKER=redis://localhost tox -e 3.10-integration-redis -- -k test_regression_issue7754
```

But I'm getting a timeout error:

```

t/integration/test_tasks.py::test_tasks::test_regression_issue7754 RERUN
t/integration/test_tasks.py::test_tasks::test_regression_issue7754 RERUN
t/integration/test_tasks.py::test_tasks::test_regression_issue7754 RERUN
t/integration/test_tasks.py::test_tasks::test_regression_issue7754 RERUN
t/integration/test_tasks.py::test_tasks::test_regression_issue7754 RERUN
t/integration/test_tasks.py::test_tasks::test_regression_issue7754 FAILED

==================================================================================================== FAILURES =====================================================================================================
______________________________________________________________________________________ test_tasks.test_regression_issue7754 _______________________________________________________________________________________

self = <celery.backends.redis.ResultConsumer object at 0x7f99ee5f7010>, result = <AsyncResult: 02844af6-cd8f-43d0-94e4-322059b25835>, timeout = 10, on_interval = <promise@0x7f99ee6c8790>, on_message = None
kwargs = {'interval': 0.5, 'no_ack': True}, prev_on_m = None, _ = None

    def _wait_for_pending(self, result,
                          timeout=None, on_interval=None, on_message=None,
                          **kwargs):
        self.on_wait_for_pending(result, timeout=timeout, **kwargs)
        prev_on_m, self.on_message = self.on_message, on_message
        try:
>           for _ in self.drain_events_until(
                    result.on_ready, timeout=timeout,
                    on_interval=on_interval):

celery/backends/asynchronous.py:287: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <celery.backends.asynchronous.Drainer object at 0x7f99ee5f7670>, p = <promise@0x7f99ee610ee0 --> <weakref at 0x7f99ee7bab20; to 'AsyncResult' at 0x7f99ee6482e0>>, timeout = 10, interval = 1
on_interval = <promise@0x7f99ee6c8790>, wait = <bound method ResultConsumer.drain_events of <celery.backends.redis.ResultConsumer object at 0x7f99ee5f7010>>

    def drain_events_until(self, p, timeout=None, interval=1, on_interval=None, wait=None):
        wait = wait or self.result_consumer.drain_events
        time_start = time.monotonic()
    
        while 1:
            # Total time spent may exceed a single call to wait()
            if timeout and time.monotonic() - time_start >= timeout:
>               raise socket.timeout()
E               TimeoutError

celery/backends/asynchronous.py:52: TimeoutError

During handling of the above exception, another exception occurred:
```

I tried to use the `docker-compose` environment but the build fails with a `pip` version resolution issue:

```
$ docker-compose run --rm celery tox -e 3.10-integration-redis -- -k test_regression_issue7754

...
#0 40.58 ERROR: Cannot install -r requirements/dev.txt (line 2), -r requirements/dev.txt (line 3), billiard 4.0.2 (from git+https://github.com/celery/billiard.git), kombu 5.3.0b1 (from git+https://github.com/celery/kombu.git), pytest-celery and vine>=5.0.0 because these package versions have conflicting dependencies.
#0 40.59 
#0 40.59 The conflict is caused by:
#0 40.59     The user requested billiard 4.0.2 (from git+https://github.com/celery/billiard.git)
#0 40.59     celery 5.2.7 depends on billiard<4.0 and >=3.6.4.0
#0 40.59     The user requested billiard 4.0.2 (from git+https://github.com/celery/billiard.git)
#0 40.59     celery 5.2.6 depends on billiard<4.0 and >=3.6.4.0
#0 40.59     The user requested billiard 4.0.2 (from git+https://github.com/celery/billiard.git)
#0 40.59     celery 5.2.4 depends on billiard<4.0 and >=3.6.4.0
#0 40.59     The user requested billiard 4.0.2 (from git+https://github.com/celery/billiard.git)
#0 40.59     celery 5.2.3 depends on billiard<4.0 and >=3.6.4.0
#0 40.59     The user requested billiard 4.0.2 (from git+https://github.com/celery/billiard.git)
#0 40.59     celery 5.2.2 depends on billiard<4.0 and >=3.6.4.0
#0 40.59     The user requested billiard 4.0.2 (from git+https://github.com/celery/billiard.git)
#0 40.59     celery 5.2.1 depends on billiard<4.0 and >=3.6.4.0
#0 40.59     The user requested billiard 4.0.2 (from git+https://github.com/celery/billiard.git)
#0 40.59     celery 5.2.0 depends on billiard<4.0 and >=3.6.4.0
#0 40.59     The user requested billiard 4.0.2 (from git+https://github.com/celery/billiard.git)
#0 40.59     celery 5.1.2 depends on billiard<4.0 and >=3.6.4.0
#0 40.59     The user requested billiard 4.0.2 (from git+https://github.com/celery/billiard.git)
#0 40.59     celery 5.1.1 depends on billiard<4.0 and >=3.6.4.0
#0 40.59     The user requested billiard 4.0.2 (from git+https://github.com/celery/billiard.git)
#0 40.59     celery 5.1.0 depends on billiard<4.0 and >=3.6.4.0
#0 40.59     The user requested billiard 4.0.2 (from git+https://github.com/celery/billiard.git)
#0 40.59     celery 5.0.5 depends on billiard<4.0 and >=3.6.3.0
#0 40.59     The user requested billiard 4.0.2 (from git+https://github.com/celery/billiard.git)
#0 40.59     celery 5.0.4 depends on billiard<4.0 and >=3.6.3.0
#0 40.59     The user requested billiard 4.0.2 (from git+https://github.com/celery/billiard.git)
#0 40.59     celery 5.0.3 depends on billiard<4.0 and >=3.6.3.0
#0 40.59     The user requested billiard 4.0.2 (from git+https://github.com/celery/billiard.git)
#0 40.59     celery 5.0.2 depends on billiard<4.0 and >=3.6.3.0
#0 40.59     The user requested billiard 4.0.2 (from git+https://github.com/celery/billiard.git)
#0 40.59     celery 5.0.1 depends on billiard<4.0 and >=3.6.3.0
#0 40.59     The user requested billiard 4.0.2 (from git+https://github.com/celery/billiard.git)
#0 40.59     celery 5.0.0 depends on billiard<4.0 and >=3.6.3.0
#0 40.59     The user requested vine>=5.0.0
#0 40.59     amqp 5.1.1 depends on vine>=5.0.0
#0 40.59     kombu 5.3.0b1 depends on vine
#0 40.59     celery 4.4.7 depends on vine==1.3.0
#0 40.59     The user requested billiard 4.0.2 (from git+https://github.com/celery/billiard.git)
#0 40.59     celery 4.4.6 depends on billiard<4.0 and >=3.6.3.0
#0 40.59     The user requested billiard 4.0.2 (from git+https://github.com/celery/billiard.git)
#0 40.59     celery 4.4.5 depends on billiard<4.0 and >=3.6.3.0
#0 40.59     The user requested vine>=5.0.0
#0 40.59     amqp 5.1.1 depends on vine>=5.0.0
#0 40.59     kombu 5.3.0b1 depends on vine
#0 40.59     celery 4.4.4 depends on vine==1.3.0
#0 40.59     The user requested kombu 5.3.0b1 (from git+https://github.com/celery/kombu.git)
#0 40.59     The user requested kombu 5.3.0b1 (from git+https://github.com/celery/kombu.git)
#0 40.59     The user requested kombu 5.3.0b1 (from git+https://github.com/celery/kombu.git)
#0 40.59     celery 4.4.3 depends on kombu<4.7 and >=4.6.9
#0 40.59     The user requested kombu 5.3.0b1 (from git+https://github.com/celery/kombu.git)
#0 40.59     The user requested kombu 5.3.0b1 (from git+https://github.com/celery/kombu.git)
#0 40.59     The user requested kombu 5.3.0b1 (from git+https://github.com/celery/kombu.git)
#0 40.59     celery 4.4.2 depends on kombu<4.7 and >=4.6.8
#0 40.59     The user requested kombu 5.3.0b1 (from git+https://github.com/celery/kombu.git)
#0 40.59     The user requested kombu 5.3.0b1 (from git+https://github.com/celery/kombu.git)
#0 40.59     The user requested kombu 5.3.0b1 (from git+https://github.com/celery/kombu.git)
#0 40.59     celery 4.4.1 depends on kombu<4.7 and >=4.6.8
#0 40.59     The user requested kombu 5.3.0b1 (from git+https://github.com/celery/kombu.git)
#0 40.59     The user requested kombu 5.3.0b1 (from git+https://github.com/celery/kombu.git)
#0 40.59     The user requested kombu 5.3.0b1 (from git+https://github.com/celery/kombu.git)
#0 40.59     celery 4.4.0 depends on kombu<4.7 and >=4.6.7
#0 40.59 
#0 40.59 To fix this you could try to:
#0 40.59 1. loosen the range of package versions you've specified
#0 40.59 2. remove package versions to allow pip attempt to solve the dependency conflict
#0 40.59 
#0 40.59 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
------
failed to solve: executor failed running [/bin/sh -c pyenv exec python3.9 -m pip install   -r requirements/dev.txt   -r requirements/test.txt   -r requirements/test-ci-default.txt   -r requirements/docs.txt   -r requirements/test-integration.txt   -r requirements/pkgutils.txt &&   pyenv exec python3.8 -m pip install   -r requirements/dev.txt   -r requirements/test.txt   -r requirements/test-ci-default.txt   -r requirements/docs.txt   -r requirements/test-integration.txt   -r requirements/pkgutils.txt &&   pyenv exec python3.7 -m pip install   -r requirements/dev.txt   -r requirements/test.txt   -r requirements/test-ci-default.txt   -r requirements/docs.txt   -r requirements/test-integration.txt   -r requirements/pkgutils.txt &&   pyenv exec python3.10 -m pip install   -r requirements/dev.txt   -r requirements/test.txt   -r requirements/test-ci-default.txt   -r requirements/docs.txt   -r requirements/test-integration.txt   -r requirements/pkgutils.txt]: exit code: 1
```

Any suggestions to move forward?

**Comment by mvaled** [comment]
Oh... Now I see integrations test are running in Github. I'm going to check them.

**Comment by mvaled** [comment]
PR https://github.com/celery/kombu/pull/1598 should solve the issue.  Closing.

**Pull request closed without merging**
