### PR TITLE
Fix Time Drift Calculation

### PR DESCRIPTION
**Pull request by max-muoto**
*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryq.dev/en/main/contributing.html).

## Description

Fix bug discussed in https://github.com/celery/celery/issues/8207 but doing the time drift calculation in events in UTC as opposed to local times.

### CODE REVIEW

**Comment by max-muoto** [comment]
@auvipy Still working on resolving some things here, but will ping you once it's ready.

**Comment by auvipy** [comment]
I still can't see any fix except the introduction of a newly introduced variable

**Comment by max-muoto** [comment]
@auvipy Not totally done (also need to add test coverages), but the idea is that `non_adjusted_timestamp` is the `timestamp` except it never gets localized with `utcoffset`.

`body['timestamp'] = adjust_timestamp(timestamp, offset)` adjusts the `timestamp` with the provided `utcoffset`.

**Comment by max-muoto** [comment]
@auvipy Basic implementation is done, let me know if what I said makes sense. Will add unit tests tomorrow if you think it looks good.

**Review by auvipy — COMMENTED** [review]
were you able to fix it?

**Pull request closed without merging**
