### PR TITLE
Fix eager tasks does not populate name field

### LINKED ISSUE #7715: EagerResult doesn't seem to poplate name
Sometimes I run my tasks with `CELERY_TASK_ALWAYS_EAGER` to aid debugging, it seems like the `name` property of EagerResult isn't populated, which makes this sort of investigation more tricky.

I have some code I use to list my tasks in a django app, and part of this is to grab the task name.

When running eagerly, the EagerResult task status is SUCCESS, so I would have expected `name` to be available at this point.

### LINKED ISSUE #8472: 5.3.2/3 has BREAKING change on EagerResult
# Checklist

- [x] I have verified that the issue exists against the `main` branch of Celery.
- [ ] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [ ] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/main/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `main` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 5.3.3

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

- **Minimal Python Version**: N/A or Unknown
- **Minimal Celery Version**: N/A or Unknown
- **Minimal Kombu Version**: N/A or Unknown
- **Minimal Broker Version**: N/A or Unknown
- **Minimal Result Backend Version**: N/A or Unknown
- **Minimal OS and/or Kernel Version**: N/A or Unknown
- **Minimal Broker Client Version**: N/A or Unknown
- **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

a patch release to not have a breaking change

# Actual Behavior

https://github.com/celery/celery/commit/1c363876147325a196c474e757e355c451a0cdff#diff-05689f277021b9af9d8314849c9d938db0f5a42e932169a116463ef91ae9af78R986

```
TypeError
EagerResult.__init__() missing 1 required positional argument: 'state'
```

### PR DESCRIPTION
**Pull request by KOliver94**
*Note*: Before submitting this pull request, please review our [contributing guidelines](https://docs.celeryq.dev/en/main/contributing.html).

## Description

My previous attempt (#8383) introduced a breaking change. This PR however should only contain the bear minimum to fix the issue without interfering with the current behaviour.

Fixes #7715, fixes #8472

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
I can see the difference here from the previous PR. but shouldn't the newer approach also got proper test coverage? You can see my comment of Integration test on the previous PR and we ignored and caught with the regression, right? so It would be better to have as much test case as possible. thanks for handling this again!

**Comment by KOliver94** [comment]
I'll try to add some tests but I think essentially the problem with the first approach was that it introduced a constructor change with a new required variable. As I understand the functionality did no cause any issues it only broke custom code parts for users which was an unexpected change in a patch version and it was not documented in the release notes as I did not expect that either. I think this approach can be refactored later to be similar to the first one, which is more consistent coding style wise, in a bigger version bump.

**Comment by auvipy** [comment]
OK will be waiting for the missing/additional tests

**Comment by auvipy** [comment]
it would be really great if we can add some test and merge this PR ASAP :)

**Comment by KOliver94** [comment]
Sorry I didn't have time, I'll try to do it as soon as possible. :)

**Comment by KOliver94** [comment]
Hey @auvipy,

Sorry it took me so long but I added some tests. As all other tests pass without modification, I think it should be a safe change now.

Let me know what you think. Thanks!

**Review by auvipy — APPROVED** [review]
Looks better

**Comment by auvipy** [comment]
should we consider the OLD test https://github.com/celery/celery/pull/8383/files#diff-c63df79f676057328c4244cd9d26001610598b4bc772d503e5120a89291e46fc as well in the chord test? what about integration test to check nothing breaks? these are not mandatory but nice to have

**Comment by KOliver94** [comment]
The modification in the chord test was only necessary because the change was mandatory. Now I think it's better not to change it because it validates that it is now not a breaking change. The functions inside celery populates the attribute so only custom functions made by users need to be adjusted. I added one more check to make sure the name field is still populated inside EagerResults even when they are called through a normal task flow. I don't think an integration test is necessary as most aspects are covered through the unit tests and I only see a really few patterns to integration test eager tasks.

**Comment by auvipy** [comment]
yeah the new extra line looks great. thanks a lot

**Review by auvipy — APPROVED** [review]

**Pull request merged**
