### PR TITLE
Update the version of redis required to match what kombu 4.4.0 requires

### PR DESCRIPTION
**Pull request by dbaxa**
*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

Please describe your pull request.

NOTE: All patches should be made against master, not a maintenance branch like
3.1, 2.5, etc.  That is unless the bug is already fixed in master, but not in
that version series.

If it fixes a bug or resolves a feature request,
be sure to link to that issue via (Fixes #4412) for example.

### CODE REVIEW

**Comment by idobrodushniy** [comment]
Got the same issue! Why the new release with the changed version of kombu is under tag 4.1.1? 
Can I still use the old version of kombu(4.3.0) with celery 4.1.1?
Please fix this issue, or put the celery with a new version of kombu into the new tag like 4.1.2 .

**Comment by dbaxa** [comment]
@auvipy why did you close this pr?

**Comment by thedrow** [comment]
This was targeting the wrong branch.
I already updated the minimum Kombu version on master.

Thanks for the contribution.

**Comment by dbaxa** [comment]
@thedrow okay. However, isn't it a problem that the 4.2 branch still has the troublesome redis version pinning ?

**Comment by thedrow** [comment]
No, not really since we don't support Redis 3 in 4.2 at all.

**Comment by dbaxa** [comment]
@thedrow I am confused. Because of the dependencies of Celery 4.2.x are declared, pip can select kombu 4.4.0 as a dependency ... which requires redis >= 3.2.0. (related: https://github.com/celery/kombu/issues/1016)

**Comment by thedrow** [comment]
I'll release a new 4.2 version limiting the support of Kombu to 4.3.

**Comment by reupen** [comment]
> No, not really since we don't support Redis 3 in 4.2 at all.

The redis<3 restriction was added in Celery 4.2.2:

https://github.com/celery/celery/compare/v4.2.1...v4.2.2

I, and I expect others, had been using redis-py 3.x with Celery 4.2.1 and kombu 4.3 for some time.

**Comment by thedrow** [comment]
Yes but there was a problem with Redis 3 and it's API changes...

**Comment by reupen** [comment]
Which problem was there that wasn't fixed in Kombu 4.2.2? I think downgrading the project I am working on to redis-py 2.x after using 3.x for a while is risky; the least risky thing (for my project) would be to leave everything as it is until Celery 4.3 is released.

**Comment by thedrow** [comment]
Search the issues in Kombu and Celery and read the changelogs. You'll find them.

**Pull request closed without merging**
