### PR TITLE
Update CONTRIBUTORS.txt

### PR DESCRIPTION
**Pull request by alekibango**
adding myself to contributors

### CODE REVIEW

**Comment by alekibango** [comment]
> did you contributed to celery earlier?
see:  https://github.com/celery/celery/pulls?q=is%3Apr+author%3Aalekibango

**Comment by alekibango** [comment]
i see, maybe previous data would be better, I updated a line in docs  at Oct 10, 2012. should i change it to this date?

**Comment by alekibango** [comment]
> can't find out the commit messages! https://github.com/celery/celery/commits?author=alekibango the pr you sent were not merged as you as contributor!

please read comments:  https://github.com/celery/celery/pull/3102#issuecomment-195640684 
and https://github.com/celery/celery/pull/3102#issuecomment-204624341

**Review by auvipy — APPROVED** [review]

**Comment by auvipy** [comment]
more contributions are welcome

**Pull request merged**
