### PR TITLE
relaxed click version

### PR DESCRIPTION
**Pull request by graingert**
*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

### CODE REVIEW

**Comment by graingert** [comment]
remake of https://github.com/celery/celery/pull/6801 with extra fixes for click 8

**Comment by graingert** [comment]
@auvipy

**Review by auvipy — DISMISSED** [review]

**Comment by auvipy** [comment]
can you please check the lint error?

**Comment by graingert** [comment]
> can you please check the lint error?

if you accept my request for pre-commit.ci it will push the lint fix

**Comment by auvipy** [comment]
where will I get the notif of that?

**Comment by graingert** [comment]
> where will I get the notif of that?

hmm I'm not sure, it might be easier for you to enable pre-commit.ci instead: https://pre-commit.ci/

**Comment by auvipy** [comment]
done

**Review by auvipy — APPROVED** [review]

**Review by thedrow — APPROVED** [review]

**Pull request merged**
