### PR TITLE
apply pre-commit

### PR DESCRIPTION
**Pull request by graingert**
run pre-commit in ci.

when making another PR I ran `pipx run pre-commit run --all-files` and it reformatted most of the files in the repo. So it seems pre-commit was configured then not run.

This PR updates pre-commit to some reasonable defaults (copied from Twisted), applies it and configures it in CI and tox

### CODE REVIEW

**Comment by auvipy** [comment]
this type of massive change will disrupt the git

**Comment by auvipy** [comment]
yes thats accaptable

**Review by auvipy — CHANGES_REQUESTED** [review]
just undo the black stuff for now

**Comment by graingert** [comment]
> just undo the black stuff for now

I'm going to redo the PR with black omitted

**Review by auvipy — APPROVED** [review]

**Comment by graingert** [comment]
@auvipy I requested to add pre-commit.ci to this repo, it should help keep these hooks updated

**Comment by auvipy** [comment]
OK

**Pull request merged**
