### PR TITLE
redis: Support Sentinel with SSL

### PR DESCRIPTION
**Pull request by auvipy**
Use the SentinelManagedSSLConnection when SSL is enabled for the
transport.

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

### CODE REVIEW

**Comment by AbdealiJK** [comment]
@auvipy Just saw that you created this - Thanks :)
I've modified the PR to create the `SentinelManagedSSLConnection` class directly in Celery for now - until https://github.com/andymccurdy/redis-py/pull/1419 gets merged

**Comment by auvipy** [comment]
> @auvipy Just saw that you created this - Thanks :)
> I've modified the PR to create the `SentinelManagedSSLConnection` class directly in Celery for now - until [andymccurdy/redis-py#1419](https://github.com/andymccurdy/redis-py/pull/1419) gets merged
> 
> This PR relates to: #6455

yup on behalf of you O:)

**Comment by AbdealiJK** [comment]
@auvipy Could we get this merged ?

**Comment by thedrow** [comment]
Wait this is a new feature. It requires a new Kombu release as well.
Master is currently at 5.0.3.
So what do we do here? Release 5.1?

**Comment by xirdneh** [comment]
If we need to do a new Kombu release and the work hasn't been done yet we cannot merge this

Also, we have to plan for new features. It would be nice to have it in prod right away but without consistency the project becomes less stable

**Comment by thedrow** [comment]
@AbdealiJK After discussing this with @xirdneh, we decided to revert this as this belongs in 5.1.0.
We'll re-create this PR and merge it after we release 5.0.3.

**Comment by auvipy** [comment]
I missed this thread

**Comment by thedrow** [comment]
Yeh we need to revert the revert.

**Pull request merged**
