### PR TITLE
Fix chord arguments

### PR DESCRIPTION
**Pull request by tayfun**
This would fix https://github.com/celery/celery/issues/2546

### CODE REVIEW

**Comment by thedrow** [comment]
I wonder why the tests passed before? Is this covered?

**Comment by tayfun** [comment]
@thedrow it wasn't covered before. I have added one test which has a chord providing an argument to its header tasks. That should cover this part.

**Comment by thedrow** [comment]
LGTM.

**Comment by ask** [comment]
I had to revert this as it broke #3504 :(

We cannot add new arguments to an existing API in a backward incompatible manner
such as this:

```
apply(args, kwargs, ...) -> apply(partial_args, args, kwargs)
```

New arguments must always be added as keyword arguments, and be added at the end of
the signature.

**Comment by thedrow** [comment]
@ask I think it's safe to break API compatibility for Celery 4.x since it's a new major version.

**Comment by tayfun** [comment]
@thedrow , the bug report is for 3.1.24. I thought 3.1.23 was the last 3.x version. Would https://github.com/celery/celery/pull/3269#r68267544 have fixed this @ask ?

**Pull request merged**
