### PR TITLE
Fixed a possible memory leak in worker

### PR DESCRIPTION
**Pull request by auvipy**

### CODE REVIEW

**Comment by yevhen-m** [comment]
According to https://github.com/celery/celery/issues/4843#issuecomment-464370923 only eventlet/gevent workers have this issue. I don't understand this comment, but it looks like your change does not fix the root cause:
```
            ...
            # we currently only buffer events when the event loop is enabled
            # XXX This excludes eventlet/gevent, which should actually buffer.
```

**Comment by auvipy** [comment]
this is just a copy of your proposed fix in your fork

**Comment by yevhen-m** [comment]
@auvipy I see, and it's good for me ;). I'm not 100% sure that it's good for everyone else.

**Comment by auvipy** [comment]
I opened the pr for more consensus actually

**Comment by thedrow** [comment]
I'm not comfortable with merging this without knowing why or how this solves our issue or partly solves it.
If we do merge this, I need a full analysis.
I'm super busy with Celery 5 and the upcoming 4.4.0 release (which I haven't even began to deal with).
Someone needs to grab this.

**Comment by auvipy** [comment]
OK let's postpone this for a while!

**Comment by thedrow** [comment]
> OK let's postpone this for a while!

This is pretty critical for our users.
Someone needs to take this head on. Please try your best.

**Comment by jezdez** [comment]
@auvipy @thedrow Forgive me if I'm wrong, but I'm confused why the technical board team was requested to review this pull request (and others).

https://github.com/celery/ceps/issues/13 and [CEP 1](https://github.com/celery/ceps/blob/master/final/0001-cep-process.rst) described the technical board as solely for high-level (read: CEP-level) decision making to support the core developers, not day-to-day development. This may have been a mistake only, but please let me know it the CEP isn't up-to-date anymore.

**Comment by auvipy** [comment]
the CEP is alright. I am the culprit to request the review here!!

**Comment by matteius** [comment]
TEST?

**Comment by matteius** [comment]
What is the outcome when the connection is offline and it will now raise from within publish?  What is expected happens next in the exception handling by default?

**Comment by spidernello** [comment]
Team, is there any update about this issue? Was this addressed and fixed in celery 4.4.0?

**Comment by auvipy** [comment]
can you check this https://github.com/celery/celery/pull/5870 ?

**Comment by spidernello** [comment]
I see , so it seems it is still waiting for a test to be executed and it is still not merged in, I can see the PR is open , correct?

**Comment by auvipy** [comment]
you should try that patch on your staging env

**Comment by spidernello** [comment]
@auvipy thanks for your answer. To be precise this is the type of exception we found, I looked at the solution proposed in the PR and would like to understand if its applicable also to our problem based on the error log or its unrelated issue

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/lib/python3.6/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/usr/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/usr/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/usr/lib/python3.6/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/usr/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 293, in create_loop
    poll_timeout = fire_timers(propagate=propagate) if scheduled else 1
  File "/usr/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 136, in fire_timers
    entry()
  File "/usr/lib/python3.6/site-packages/kombu/asynchronous/timer.py", line 68, in __call__
    return self.fun(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/kombu/asynchronous/timer.py", line 127, in _reschedules
    return fun(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/billiard/pool.py", line 1316, in maintain_pool
    sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/billiard/five.py", line 126, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/billiard/pool.py", line 1307, in maintain_pool
    self._maintain_pool()
  File "/usr/lib/python3.6/site-packages/billiard/pool.py", line 1299, in _maintain_pool
    self._repopulate_pool(joined)
  File "/usr/lib/python3.6/site-packages/billiard/pool.py", line 1284, in _repopulate_pool
    self._create_worker_process(self._avail_index())
  File "/usr/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 449, in _create_worker_process
    return super(AsynPool, self)._create_worker_process(i)
  File "/usr/lib/python3.6/site-packages/billiard/pool.py", line 1116, in _create_worker_process
    w.start()
  File "/usr/lib/python3.6/site-packages/billiard/process.py", line 124, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/site-packages/billiard/context.py", line 333, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/site-packages/billiard/popen_fork.py", line 24, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/site-packages/billiard/popen_fork.py", line 72, in _launch
    self.pid = os.fork()
MemoryError: [Errno 12] Cannot allocate memory
```

**Pull request closed without merging**
