### PR TITLE
Fix worker crash on un-pickleable exceptions

### PR DESCRIPTION
**Pull request by youtux**
## Description

Fix celery worker crash when a retry is issued with an unpickleable exception.

Fixes https://github.com/celery/celery/issues/6185 and https://github.com/celery/celery/issues/6990.

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
we need test to verify this changes

**Comment by alessio-b2c2** [comment]
would you be able to guide me through that? Or maybe can you take over from here? I wouldn't really know where to start from

**Comment by youtux** [comment]
would you be able to guide me through that? Or maybe can you take over from here? I wouldn't really know where to start from

**Comment by youtux** [comment]
@auvipy can you approve the workflow run?

**Review by auvipy — APPROVED** [review]

**Comment by youtux** [comment]
I'm actually trying to add an integration test that reproduces the failure, let's hold on

**Comment by auvipy** [comment]
you should have mention that earlier, anyway ping me with Integration test as well

**Comment by youtux** [comment]
👍

**Comment by youtux** [comment]
Adding my tests in https://github.com/celery/celery/pull/8149

**Pull request merged**
