### PR TITLE
Revert "store children with database backend"

### PR DESCRIPTION
**Pull request by auvipy**
Reverts celery/celery#8338

@Nusnus we might revert this for now and reintroduce in future with a proper migration support. for migration support I can work

### CODE REVIEW

**Review by Nusnus — APPROVED** [review]
Agreed. This was a good change but unfortunately not complete. Once we have the remaining changes we can welcome this back.

**Comment by Nusnus** [comment]
@aaronst we're reverting the change in `main` as we need to release an urgent patch version and we'd be happy to welcome this back once completed.

Ping me if you need any help/review and I'll prioritize it for me due to this situation.

**Comment by aaronst** [comment]
@Nusnus @auvipy I suggest updating the documentation so that users are aware the database backends are not feature complete. The parent/child relationship between tasks is important and currently broken for any database backend.

**Comment by Nusnus** [comment]
> @Nusnus @auvipy I suggest updating the documentation so that users are aware the database backends are not feature complete. The parent/child relationship between tasks is important and currently broken for any database backend.

@aaronst Is it reasonable to ask you please for the remaining changes (the migration) so we can complete it instead of documenting the gap?

**Comment by aaronst** [comment]
@Nusnus I’m happy to help with the migration, but this bug still needs to be documented if the fix is being reverted.

**Comment by auvipy** [comment]
I will be happy to accept a 

> @Nusnus I’m happy to help with the migration, but this bug still needs to be documented if the fix is being reverted.

I'm still open to a doc fix, until the code is fixed

**Pull request merged**
