### PR TITLE
Fixes issue #2453

### PR DESCRIPTION
**Pull request by lukeburden**
Please see issue #2453 for a description of the problem.

### CODE REVIEW

**Comment by ionelmc** [comment]
For posterity, this is an issue only when [CONN_MAX_AGE](https://docs.djangoproject.com/en/1.7/ref/settings/#conn-max-age) is used.

**Comment by ionelmc** [comment]
Thanks for this and the bug report.

**Comment by ionelmc** [comment]
Can you also make a PR adding yourself to CONTRIBUTORS.txt ?

**Comment by ionelmc** [comment]
Actually I already made the change, make a PR if I misspelled your name.

**Comment by lukeburden** [comment]
Looks good, thanks for that and you're very welcome.

**Pull request merged**
