### PR TITLE
Fix redis connection leakage

### LINKED ISSUE #6819: Redis result backend connections leak
# Checklist

* [x] I have verified that the issue exists against the `master` branch of Celery.
* [x] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
* [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
* [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
* [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
* [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
* [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information
* [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
* [x] I have verified that the issue exists against the `master` branch of Celery.
* [x] I have included the contents of ``pip freeze`` in the issue.
* [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

* [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
* [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
* [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
* [ ] I have tried reproducing the issue on more than one operating system.
* [ ] I have tried reproducing the issue on more than one workers pool.
* [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
* [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Possible Duplicates
* None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:5.1.0 (sun-harmonics) kombu:5.1.0 py:3.8.8
            billiard:3.6.4.0 redis:3.5.3
platform -> system:Darwin arch:64bit
            kernel version:20.4.0 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis:///

broker_url: 'redis://localhost:6379//'
result_backend: 'redis:///'
task_queue_max_priority: 10
deprecated_settings: None
```

</p>
</details>

# Steps to Reproduce
## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==5.0.6
billiard==3.6.4.0
celery==5.1.0
certifi==2021.5.30
chardet==4.0.0
click==7.1.2
click-didyoumean==0.0.3
click-plugins==1.1.1
click-repl==0.2.0
dnspython==1.16.0
eventlet==0.31.0
Flask==2.0.1
greenlet==1.1.0
idna==2.10
itsdangerous==2.0.1
Jinja2==3.0.1
kombu==5.1.0
MarkupSafe==2.0.1
prompt-toolkit==3.0.18
pytz==2021.1
redis==3.5.3
requests==2.25.1
six==1.16.0
urllib3==1.26.5
vine==5.0.0
wcwidth==0.2.5
Werkzeug==2.0.1
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

tasks.py

```
import time
from celery import Celery

app = Celery('tasks', backend='redis://', broker='redis://', task_queue_max_priority=10)


@app.task
def sleep():
    time.sleep(1)
```

web.py

```
from flask import Flask
from tasks import sleep
app = Flask(__name__)

@app.route('/')
def hello_world():
    result = sleep.apply_async()
    result.wait()
    return '', 200

if __name__ == '__main__':
    app.run(port=4444)
```

simulate.py

```
import requests
for i in range(20):
    requests.get("http://localhost:4444")
```

1. `pip install celery[redis] requests flask`
1. Start redis
`docker run -p 6379:6379 --name redis redis`
1. Run celery `celery -A tasks worker --loglevel=INFO`
1. Run web server `python web.py`
1. connect to redis

```
docker exec -it redis /bin/bash
redis-cli
info Clients
```

Note the `connected_clients` number

1. simulate requests `python simulate.py`
1. Run `info Clients` again in redis-cli. 
Note the `connected_clients` number which is now a lot higher
</p>
</details>

# Expected Behavior

Connections close after getting/waiting for a result

# Actual Behavior

I'm experiencing a very strange problem with redis connections staying open after each request (after each result.wait() or result.get()).

Help will be super appreciated.
Running flask with `threaded=False` solves the issue.
Obviously this is a simplified reproduction code. Our real environment is gunicorn, eventlet, flask, redis, celery.
In production we are getting 60k open connections to redis quite fast and we had to restart our server a few times to reset the leaks.

### PR DESCRIPTION
**Pull request by hiimdoublej-swag**
*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryq.dev/en/master/contributing.html).

## Description

This PR is picked from #6985 since it has gone stale. (One of the maintainers asked for a rebase and that's all she wrote.)
This tries to resolve #6819 by ensuring there's only 1 redis connection pool across all the gevent concurrencies.

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
would you mind adding some test for this change?

**Comment by auvipy** [comment]
redis integration tests are failing

**Comment by hiimdoublej-swag** [comment]
> redis integration tests are failing

I take a look, thanks

**Comment by hiimdoublej-swag** [comment]
@auvipy How did you manage to run tests locally ? The build in `/docker` doesn't seem to work.
Complains about dependency conflicts.

**Comment by hiimdoublej-swag** [comment]
Well, I managed to get the tests running, but I think this fix introduced another problem with threading.

**Comment by auvipy** [comment]
yeah if you can fix that please push and let me know

**Comment by hiimdoublej-swag** [comment]
It seemed to stuck on result retrieval under threaded environments, not sure why.

**Comment by hiimdoublej-swag** [comment]
I'm starting to think that maybe this approach wasn't the correct fix, I'll close for now until I discover otherwise or found another fix.

**Pull request closed without merging**
