### PR TITLE
Restrict redis dependency to v2

### PR DESCRIPTION
**Pull request by simonschmidt**
Version 3 of the redis package is backwards incompatible and
causes a bunch of breakage, limit to version 2.

### CODE REVIEW

**Comment by simonschmidt** [comment]
Not sure if this should be targeting master branch or the 4.2 branch, so I made one PR for each.

**Comment by auvipy** [comment]
master should be the target for now.

**Comment by thedrow** [comment]
This should be reverted since https://github.com/sarugaku/pythonfinder/issues/48#issuecomment-440573215 was merged.

**Comment by auvipy** [comment]
reverted

**Pull request merged**
