### PR TITLE
Fix windows build

### PR DESCRIPTION
**Pull request by mchataigner**
those libraries depends on native libraries libcouchbase and libmemcached
that are not installed on Appveyor.
As only unit tests runs on Appveyor, it should be fine

### CODE REVIEW

**Comment by mchataigner** [comment]
Only python 2.7 on windows left to fix.
It fails due to an error when installing pycurl. It requires curl-dir option from pip.
For some reason it works on python 3+.

**Comment by auvipy** [comment]
we can drop python 2.7 from win build :)

**Comment by mchataigner** [comment]
I don't know why codecov is reporting 0%…

**Comment by auvipy** [comment]
probably not related to this PR

**Pull request merged**
