### PR TITLE
Port latest changes from master to v5-dev

### PR DESCRIPTION
**Pull request by thedrow**
*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

This PR contains the latest changes from master with conflicts resolved on v5-dev.

### CODE REVIEW

**Comment by thedrow** [comment]
@celery/core-developers Please review and merge since I have other incoming changes.

**Comment by thedrow** [comment]
I just noticed that the merge target was master instead of v5-dev.

**Comment by auvipy** [comment]
I restarted the build

**Comment by thedrow** [comment]
So we have a different failure than master?

**Pull request merged**
