### PR TITLE
Adding name to CONTRIBUTORS.txt

### PR DESCRIPTION
**Pull request by willtrking**
Adding name to CONTRIBUTORS.txt as per https://github.com/celery/celery/pull/2384#issuecomment-64059702

### CODE REVIEW

**Comment by malinoff** [comment]
@willtrking sorry, I'm unable to merge this. Could you please fast-forward the latest master and commit that again?

**Comment by thedrow** [comment]
@malinoff It will be faster to merge this manually, don't you think?

**Comment by malinoff** [comment]
@thedrow sure, just want to follow the usual process.

**Comment by malinoff** [comment]
Added via 15c00792

**Pull request closed without merging**
