### PR TITLE
Fix TypeError raised in logging (validate_models)

### PR DESCRIPTION
**Pull request by aalebedev**
Fix TypeError raised in logging (validate_models)
celery -A proj worker -l info
Windows 8
celery 3.1.17, django 1.6.10

### CODE REVIEW

**Comment by aalebedev** [comment]
Sorry, I have forgotten about python version - 2.7.8

**Comment by aalebedev** [comment]
Is it an error, caused by my commits? May be I should replace "StringIO" to 'io" without any checkings ("reverting" of my changes) and I will get this error again?

test_safe_to_remove_while_iteritems (celery.tests.utils.test_functional.test_LRUCache) ... ERROR
======================================================================
ERROR: test_safe_to_remove_while_iteritems (celery.tests.utils.test_functional.test_LRUCache)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/travis/build/celery/celery/celery/tests/utils/test_functional.py", line 101, in test_safe_to_remove_while_iteritems
self.assertSafeIter('iteritems')
File "/home/travis/build/celery/celery/celery/tests/utils/test_functional.py", line 95, in assertSafeIter
for _ in getattr(x, method)():
File "/home/travis/build/celery/celery/celery/utils/functional.py", line 94, in _iterate_items
for k in self:
RuntimeError: dictionary changed size during iteration

**Comment by ask** [comment]
Thanks merged into master and 3.1!  Do you have your name in https://github.com/celery/celery/edit/master/CONTRIBUTORS.txt yet?

**Comment by aalebedev** [comment]
Thanks! No, I haven't. Should I add my name into this file and create another pull-request?

**Comment by thedrow** [comment]
@aalebedev Yup :)

**Comment by aalebedev** [comment]
Okay, I have done it :)

**Pull request closed without merging**
