### PR TITLE
Cross process tracebacks improvement [celery]

### PR DESCRIPTION
**Pull request by ionelmc**
Improvements to allow traceback frames to be pickled and raised cross processes.

### CODE REVIEW

**Comment by auvipy** [comment]
This branch has conflicts that must be resolved

**Comment by thedrow** [comment]
@ionelmc It looks good.
Can you please resolve the conflicts?

**Comment by ionelmc** [comment]
Do I understand correctly that the exception raising was moved to `celery/result.py`?

**Comment by ionelmc** [comment]
I've remade a simpler pr for this in https://github.com/celery/celery/pull/3099

**Pull request closed without merging**
