### PR TITLE
Migrate to Poetry

### PR DESCRIPTION
**Pull request by thedrow**
*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

We want to migrate to Poetry so that we'll be able to use pyproject.toml and get rid of most of our requirement files.

### CODE REVIEW

**Comment by thedrow** [comment]
@auvipy FYI

**Comment by graingert** [comment]
@thedrow can I take this over?

**Comment by auvipy** [comment]
you can push on his branch

**Comment by graingert** [comment]
@thedrow it looks like it's not currently possible to migrate to poetry see https://github.com/python-poetry/poetry/discussions/4313

**Pull request closed without merging**
