### PR TITLE
update docs docker image

### PR DESCRIPTION
**Pull request by auvipy**
this might need CI update as well

### CODE REVIEW

**Comment by Nusnus** [comment]
Not sure - let me check

**Comment by auvipy** [comment]
you can run locally as well. also we can consider adding Dockerfile path

**Review by Nusnus — APPROVED** [review]
Just noticed this is `docker/docs/Dockerfile` (**docs**), so np!
I thought it conflicts with something else but it's alright in that regard.

**Comment by Nusnus** [comment]
I'll let you do the merging @auvipy

**Comment by auvipy** [comment]
Thanks a lot man!

**Pull request merged**
