### PR TITLE
Fixed #3586 made celery respect exception types when using serializers

### LINKED ISSUE #3586: Celery does not respect exceptions types when using a serializer different than pickle.
## Checklist
```
~ : celery -A analystick report
software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:3.5.2
            billiard:3.5.0.2 redis:2.10.5
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://127.0.0.1:6379/1
```

## Steps to reproduce
(See example code below)

## Expected behavior

__When using a result serializer different than pickle__, exceptions types should be the same as the raised exception.

## Actual behavior
Celery does not respect the exception type but create _a new type_ instead.

The main problem is that instead of using the actual type of the exception, celery will [reconstruct a type](https://github.com/celery/celery/blob/0f87321df385c5f3dca717ec2a4a9c0d25f88054/celery/utils/serialization.py#L43-L45) on the fly, but without respecting the original exception module.

For example, using the `yaml` result serializer (I believe it will be the same for `json`): 
- if a task raises a `ValueError`, the caller will receive a `celery.backends.base.ValueError`
- if a task raises a `custom.module.CustomError`, the caller will receive a `celery.backends.base.CustomError`

This ends with wrongs behaviour when raising a exception from a task and trying to catch it from the caller.

### Minimal reproductible test
As an example, I've setup a minimal reproductible test, using a redis backend :

celery config (I can provide a full config if needed):
```python
CELERY_TASK_SERIALIZER = 'yaml'
CELERY_RESULT_SERIALIZER='yaml'
```

Tasks : 

```python
# module myapp.tasks
from myapp import celery_app
@celery_app.task
def raises_valueerror():
    raise ValueError('Builtin exception')

class CustomError(Exception):
    pass

@celery_app.task
def raises_customerror():
    raise CustomError('Custom exception', {'a':1})
```

Unittest : 
```python
from myapp import tasks
from myapp.tasks import CustomError

def test_builtin_exception():
    t = tasks.raises_valueerror.s()
    r = t.apply_async()

    exc = None
    try:
        r.get(propagate=True)
    except Exception as e:
        exc = e

    # with celery bug, the actual class of exc will be  `celery.backends.base.ValueError` instead of builtin ValueError
    assert isinstance(exc, ValueError), "Actual class %s}" % (exc.__class__)

def test_custom_exception():
    t = tasks.raises_customerror.s()
    r = t.apply_async()

    exc = None
    try:
        r.get(propagate=True)
    except Exception as e:
        exc = e

    # with celery bug, the actual class of exc will be  `celery.backends.base.CustomError` instead of builtin CustomError
    assert isinstance(exc, CustomError), "1/2 Actual class is %s" % (exc.__class__)
    assert isinstance(exc, tasks.CustomError), "2/2 Actual class is %s" % (exc.__class__)

```

Theses tests will fail with the following errors : 

```
# ...
AssertionError: Actual class <class 'celery.backends.base.ValueError'>
# ...
AssertionError: 1/2 Actual class is <class 'celery.backends.base.CustomError'>
```

Another side effect for this problem will be that a code like the one below won't work if a subtask raise a `ValueError`, as the propagated exception won't be of the builtin type `ValueError` but `celery.backends.base.ValueError`:

```python
try:
    r.get(propagate=True)
except ValueError as e:
    # do something        
```

This problem will be the same also for any custom exceptions.

While I'm not sure about the possible side-effects, [I have a fix for this](https://github.com/jcsaaddupuy/celery/commit/8d4e613e24f6561fdaafd4e6ede582ceac882804) and I will gladly create a PR for this problem as it seems pretty critical.

What do you think ?

### PR DESCRIPTION
**Pull request by auvipy**
rebased version of https://github.com/celery/celery/pull/3592

### CODE REVIEW

**Comment by auvipy** [comment]
@johnarnold

**Comment by auvipy** [comment]
this is weird! isort is giving different errors in local and CI!

**Comment by auvipy** [comment]
seems an isort issue! should we move to black formatter?

**Comment by auvipy** [comment]
decided to disable isort from travis https://github.com/celery/celery/pull/5082

**Comment by thedrow** [comment]
I'm sorry I missed this.
Last important change in this area was done in #4864 which resolves #4860.
Are we sure all the tests pass and exceptions with arguments that are not JSON-serializable are still serialized correctly?
Do we still need `ensure_serializable()` since that was added in #4864?

**Comment by auvipy** [comment]
I have some confusion in mind, I probably mixed up. let me investigate and get to you soon.

**Comment by auvipy** [comment]
investigating properly it seems I totally overlooked the recent changes

**Comment by cscetbon** [comment]
Hey @auvipy, any progress on that ?

**Comment by auvipy** [comment]
no, actually I was busy with so many other issues of celery

**Pull request merged**
