### PR TITLE
Revert "Add auto expiry for DynamoDB backend"

### PR DESCRIPTION
**Pull request by auvipy**
Reverts celery/celery#5805

### CODE REVIEW

**Comment by georgepsarakis** [comment]
@auvipy can you please add a Travis CI build link, so that we can inspect the errors or test failures? We could also notify the author for help.

**Comment by auvipy** [comment]
yes please check this PR and build https://github.com/celery/celery/pull/5857

**Comment by auvipy** [comment]
i think @thedrow didn't notice the integration tests failures when he merged it.

**Comment by georgepsarakis** [comment]
I suppose you mean this [error](https://travis-ci.org/celery/celery/jobs/619332616#L814) ? This seems totally unrelated, most likely is a tox / package installation issue. I would suggest that we add again the expiration changes, since the failures seem unrelated. @thedrow what do you think?

**Comment by auvipy** [comment]
I am not against the feature

**Comment by thedrow** [comment]
I really don't see a reason to revert this PR.
I'm working on CI right now.

**Pull request merged**
