### PR TITLE
Fix CELERY_TASK_ settings docs

### PR DESCRIPTION
**Pull request by alukach**
I've noticed that settings `CELERY_QUEUES` or `CELERY_DEFAULT_QUEUE` don't seem to apply to the configuration as described in the documentation.

I don't fully understand the configuration logic, but it appears that the logic for loading settings via `app.config_from_object` is something along the lines of `conf[setting_name] = getattr(config_obj, namespace + '_' + setting_name.upper(), defaults[setting_name])`.  This means that if a setting is named `task_queues`, the relevant old-style setting should be `CELERY_TASK_QUEUES`, not `CELERY_QUEUES` as written.  I believe that #4061 attempted to resolve this but stopped a bit short.

Here are some quick tests that confirm this for just two of the settings:

```python
from celery import Celery
from kombu import Queue
app = Celery()

class ConfigGood:
    CELERY_TASK_DEFAULT_QUEUE = 'my-default-queue'
    CELERY_TASK_QUEUES = [Queue('a'), Queue('b')]

app.config_from_object(ConfigGood, namespace='CELERY')
assert app.conf.task_default_queue == 'my-default-queue'
assert list(app.amqp.queues.keys()) == ['a', 'b']

app = Celery()

class ConfigBad:
    CELERY_DEFAULT_QUEUE = 'my-default-queue'
    CELERY_QUEUES = [Queue('a'), Queue('b')]

app.config_from_object(ConfigBad, namespace='CELERY')
try:
    assert app.conf.task_default_queue == 'my-default-queue'
except AssertionError:
    print("Misconfigured")
try:
    assert list(app.amqp.queues.keys()) == ['a', 'b']
except AssertionError:
    print("Misconfigured")
```

I've taken a bit of a leap in assuming that all other `task_*` settings follow the same logic. I did not attempt to update any other settings so I may be mistaken here.  I would appreciate another set of eyes/tests on these changes.  Perhaps more config validations should be rolled into the unit tests.

It's possible that I'm misinterpretting the documentation by assuming that any of the "Setting name" values mentioned in the documentation should work with the `app.config_from_object` method.  If so, then I will close this PR and attempt to clarify the docs.

### CODE REVIEW

**Comment by alukach** [comment]
Should resolve #3772

**Comment by georgepsarakis** [comment]
@alukach nice work. I believe the option names along with their default values can be found [here](https://github.com/celery/celery/blob/master/celery/app/defaults.py#L76), so it would be a good place to cross-check everything. I will have a look later too.

**Comment by georgepsarakis** [comment]
@auvipy this contains documentation changes only, can I merge? Are we still waiting for a release or can I merge approved pull requests?

**Comment by auvipy** [comment]
sorry I was on my vacations

**Pull request merged**
