### PR TITLE
try newer bumped versions

### PR DESCRIPTION
**Pull request by auvipy**

### CODE REVIEW

**Review by auvipy — COMMENTED** [review]
merging

**Comment by DmytroLitvinov** [comment]
Hi @auvipy ,
We have a failing build at our GitLab CI/CD with next phrase:
> $ pip check
celery 5.2.3 has requirement setuptools<59.7.0,>=59.1.1, but you have setuptools 58.3.0.

Here is how we create virtualenv(Python 3.8) with setuptools:
> $ virtualenv --python=python3.8 venv
created virtual environment CPython3.8.12.final.0-64 in 372ms
  creator CPython3Posix(dest=/home/gitlab-runner/builds/hi3SfEg7/1/NephilaAG/gryps-project/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/gitlab-runner/.local/share/virtualenv)

Why do we have strict requirements for `setuptools`? Tried to read [commit ](https://github.com/celery/celery/pull/7194/commits/90c214fb3c57055947c19b6e295c18cab045fb99) but there is no additional information in description of commit or links to some problem.
Also, I am using `pip-tools` for generating reproducible build for the project and `pip-tools` has next reason for not including `setuptools` into `requirements.txt` file. Here is [link to it](https://github.com/jazzband/pip-tools/issues/522)

There is also a mention about it at [Changelog](https://github.com/celery/celery/commit/9532c73badd627457d4e543ba85fbfb9f6720de2#diff-7dbd87db46611f834c9feb91cb72889f18efe45b25041829fed54d99492f6000R24)

P.S. Thank you personally for supporting Python ecosystem. :raised_hands:

**Comment by edouardruiz** [comment]
Hi,

Exact same issue here using `pip-tools` to generate our `requirements.txt`, the `setuptools` isn't pinned.

**Comment by auvipy** [comment]
this was the reason https://github.com/celery/kombu/pull/1466/files and https://github.com/pypa/setuptools/issues/2936

**Comment by ddevault** [comment]
Did you consider fixing the hack instead?

**Comment by auvipy** [comment]
in next version release hopefully

**Comment by ddevault** [comment]
Pinning setuptools to such a new and narrow range of versions makes it much harder to package it downstream. It's pretty frustrating to see this done for the sake of a bad hack instead of fixing the real problem. I had to revert both this and the kombu change in my downstream tree.

**Comment by auvipy** [comment]
https://github.com/celery/celery/discussions/7202#discussioncomment-1913601

**Comment by ddevault** [comment]
Thanks!

**Pull request merged**
