### PR TITLE
Revert "Broker connection uses the heartbeat setting from app config unless set otherwise"

### PR DESCRIPTION
**Pull request by auvipy**
Reverts celery/celery#4148

### CODE REVIEW

**Comment by palvarezcordoba** [comment]
This PR is useful in cases like #5464

**Comment by auvipy** [comment]
so this should be merged?

**Comment by auvipy** [comment]
what about this one https://github.com/celery/celery/issues/4876?

**Comment by auvipy** [comment]
@matteius

**Pull request merged**
