### PR TITLE
Use 'property' with 'abstractmethod' instead 'abstractproperty'

### PR DESCRIPTION
**Pull request by tothegump**
'@abc.abstractproperty' has deprecated since Python 3.3 
It is now possible to use property, property.getter(), property.setter() and property.deleter() with abstractmethod(), making this decorator redundant. 
[Python doc](https://docs.python.org/3/library/abc.html#abc.abstractproperty)

### CODE REVIEW

**Comment by thedrow** [comment]
What about 2.7?

**Comment by tothegump** [comment]
You are right, Python 2.7 can not use 'property' with 'abstractmethod'.
What should I do then? Which one is better choice:
1. close this PR
2. Waiting for Celery 5. (p.s. The branch 5.0-devel latest commit date is Feb 17, 2017, does it is in progress?)
3. write extra compatible code for Python 2.7

**Comment by auvipy** [comment]
> You are right, Python 2.7 cannot use 'property' with 'abstractmethod'.
> What should I do then? Which one is a better choice:
> 
> 1. close this PR
> 2. Waiting for Celery 5. (p.s. The branch 5.0-devel latest commit date is Feb 17, 2017, does it is in progress?)
> 3. write an extra compatible code for Python 2.7

wait for c5

**Comment by thedrow** [comment]
I've rebased this to be merged on Celery 5.
This should be merged to that branch.

**Comment by auvipy** [comment]
great

**Comment by thedrow** [comment]
Which tests do you have in mind?

**Pull request merged**
