### PR TITLE
fix: `node_format()` logfile before detaching

### LINKED ISSUE #6426: `celery multi`creates xxx_%I.log files
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:5.0.1 (singularity) kombu:5.0.2 py:3.8.3
            billiard:3.6.3.0 redis:3.5.3
platform -> system:Linux arch:64bit, ELF
            kernel version:5.4.0-48-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: 5.0.1
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```shell
$ celery multi start normal low --app=service.celery:app --logfile=/tmp/celery/celery-%n%I.log --queues:normal=normal --queues:low=low --concurrency:normal=2 --concurrency:low=1 --pidfile=/tmp/celery/celeryd-%n.pid
celery multi v5.0.1 (singularity)
> Starting nodes...
	> normal@dell: OK
	> low@dell: OK
```

</p>
</details>

# Expected Behavior

Celery 4.4.7 behavior
```shell
$ ls -l /tmp/celery
-rw-r--r-- 1 www-data www-data   6 Oct 19 14:39 celeryd-low.pid
-rw-r--r-- 1 www-data www-data   6 Oct 19 14:39 celeryd-normal.pid
-rw-rw-r-- 1 www-data www-data  80 Oct 19 14:39 celery-low-1.log
-rw-rw-r-- 1 www-data www-data 316 Oct 19 14:39 celery-low.log
-rw-rw-r-- 1 www-data www-data  80 Oct 19 14:39 celery-normal-1.log
-rw-rw-r-- 1 www-data www-data  80 Oct 19 14:39 celery-normal-2.log
-rw-rw-r-- 1 www-data www-data 316 Oct 19 14:39 celery-normal.log
```

# Actual Behavior

```shell
$ ls -l /tmp/celery
-rw-r--r-- 1 www-data www-data   6 Oct 19 14:39 celeryd-low.pid
-rw-r--r-- 1 www-data www-data   6 Oct 19 14:39 celeryd-normal.pid
-rw-rw-r-- 1 www-data www-data  80 Oct 19 14:39 celery-low-1.log
-rw-rw-r-- 1 www-data www-data   0 Oct 19 14:39 celery-low%I.log
-rw-rw-r-- 1 www-data www-data 316 Oct 19 14:39 celery-low.log
-rw-rw-r-- 1 www-data www-data  80 Oct 19 14:39 celery-normal-1.log
-rw-rw-r-- 1 www-data www-data  80 Oct 19 14:39 celery-normal-2.log
-rw-rw-r-- 1 www-data www-data   0 Oct 19 14:39 celery-normal%I.log
-rw-rw-r-- 1 www-data www-data 316 Oct 19 14:39 celery-normal.log
```

### PR DESCRIPTION
**Pull request by maybe-sybr**
Fixes #6426

### CODE REVIEW

**Comment by maybe-sybr** [comment]
As an interesting note, we don't `node_format(pidfile)` when we detach vs when we remain attached. But pidfile names seem to work as expected anyway so presumably that formatting is happening somewhere. A `%n` in the pidfile argument gets handled by the multi runner, but then if I add a `%I`, it gets mysteriously handled somewhere on the way to being used to drop the actual pidfile once the multiple workers get started. Probably not an issue.

**Review by auvipy — CHANGES_REQUESTED** [review]
can you check why pypy tests are failing?

**Comment by thedrow** [comment]
> can you check why pypy tests are failing?

That failure is unrelated.
@auvipy @maybe-sybr Can you please open an issue so we'll eventually investigate this?

**Comment by maybe-sybr** [comment]
> > can you check why pypy tests are failing?
> 
> That failure is unrelated.
> @auvipy @maybe-sybr Can you please open an issue so we'll eventually investigate this?

#6489 @thedrow

**Review by auvipy — APPROVED** [review]

**Pull request merged**
