### PR TITLE
Support Redis Sentinel as result backend

### PR DESCRIPTION
**Pull request by tristan0x**
Hi there,

We (at Cogniteev) recently switched to Redis as result backend that provides a very efficient implementation of chords. Yet we missed high-availability to use it on production.

Here is a patch in Redis result backend that provide support to Sentinel.

### CODE REVIEW

**Comment by tristan0x** [comment]
Travis fails here:
```
ERROR: test_safe_to_remove_while_iteritems (celery.tests.utils.test_functional.test_LRUCache)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/celery/celery/celery/tests/utils/test_functional.py", line 101, in test_safe_to_remove_while_iteritems
    self.assertSafeIter('iteritems')
  File "/home/travis/build/celery/celery/celery/tests/utils/test_functional.py", line 95, in assertSafeIter
    for _ in getattr(x, method)():
  File "/home/travis/build/celery/celery/celery/utils/functional.py", line 71, in _iterate_items
    for k in self:
RuntimeError: dictionary changed size during iteration
```

I guess the failed test is not related to the PR, is it?

**Comment by thedrow** [comment]
Nope. PyPy has changed how dicts behave a bit.

**Comment by thedrow** [comment]
Can you please rebase?

**Comment by tristan0x** [comment]
Hey @thedrow 
I have rebased as asked.

**Comment by auvipy** [comment]
@tristan0x could you please rebase your work against master and check if its working right?

**Comment by ask** [comment]
Looking good, but It would be helpful if this  was applied to the master branch, as we cannot merge this into 3.1

**Comment by berkerpeksag** [comment]
Wouldn't it be better to implement this as a subclass of `RedisBackend` so we can avoid adding `if self.sentinel:` checks in the class?

**Comment by thedrow** [comment]
Thanks for the contribution. #4144 supersedes this PR.

**Pull request closed without merging**
