### PR TITLE
integration test: cleanup worker after test case

### PR DESCRIPTION
**Pull request by zhu**
*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryq.dev/en/main/contributing.html).

## Description

Avoid tests interference from each others.

### CODE REVIEW

**Comment by zhu** [comment]
`rabbitmq_redis` integration test, before:
```
193 passed, 2 skipped, 10 xfailed, 5 xpassed, 39 warnings, 210 subtests passed, 4 rerun in 1053.75s (0:17:33)
```
after:
```
195 passed, 2 skipped, 8 xfailed, 5 xpassed, 39 warnings, 210 subtests passed in 947.91s (0:15:47)
```

**Review by auvipy — COMMENTED** [review]
except the more test coverage, or can we ignore that?

**Review by Nusnus — APPROVED** [review]
Great PR ! Thank you @zhu 
I only wonder if `wait_until_idle` is the best name - or maybe adding a short doc could do the trick?
Either way, approved by me.

**Comment by Nusnus** [comment]
> except the more test coverage, or can we ignore that?

We can ignore the test cov here, yeah

**Review by auvipy — APPROVED** [review]
we can improve the naming later i guess

**Pull request merged**
