### PR TITLE
How to execute a batches worker with prefetch_multiplier override

### PR DESCRIPTION
**Pull request by mverrilli**
This information seems almost required to use Batches effectively along with other tasks in your application.

### CODE REVIEW

**Comment by thedrow** [comment]
English is correct but I'm not familiar with the mechanism.
@ask @malinoff What do you think?

**Comment by malinoff** [comment]
@thedrow I can't say anything useful about batches, @ask we need your opinion here :)

**Comment by thedrow** [comment]
@malinoff When you need @ask just assign the issue to him.
That way he'll have a list of issues he needs to attend to.

**Comment by PMickael** [comment]
Hi,

I added a custom args some month ago : prefetch-multiplier
So the good syntax to use is

```
celery worker -l info --prefetch-multiplier=1000
@app.task(base=Batches, flush_every=200, flush_interval=2, ignore_result=True, compression='zlib')
```
then it will prefetch 1000 execute every 200 or every 2 sec

**Comment by mverrilli** [comment]
@PaulMcMillan  I didn't realize this was added, very good! I'll close this out and if I don't see any documentation for this I'll add a reference to your new parameter.  Thanks!!

**Pull request closed without merging**
