### PR TITLE
install deps with 2020-resolver and fast-deps

### PR DESCRIPTION
**Pull request by graingert**
*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

### CODE REVIEW

**Comment by thedrow** [comment]
Please include a description and avoid assuming we all know what this is about.
Thank you. :heart:

**Comment by graingert** [comment]
@thedrow ah I wasn't expecting this to work, so I didn't bother. Will do that now

**Comment by graingert** [comment]
This PR opts in to the pip 20.3 default configuration so we know if anything is broken in the deps we have

 https://pythoninsider.blogspot.com/2020/07/upgrade-pip-20-2-changes-20-3.html

**Comment by thedrow** [comment]
> @thedrow ah I wasn't expecting this to work, so I didn't bother. Will do that now

In that case, please mark the PR as a draft. I won't review it :)

**Comment by thedrow** [comment]
> This PR opts in to the pip 20.3 default configuration so we know if anything is broken in the deps we have
> 
> https://pythoninsider.blogspot.com/2020/07/upgrade-pip-20-2-changes-20-3.html
> 
> also when running tests locally I saw a warning about botocore and docutils incompatibility which this PR is supposed to resolve. I'll paste the error message here when I'm back at a keyboard

When you do, please edit the original post. We try to be organized here so there's documentation for every change.

**Comment by graingert** [comment]
@thedrow I was expecting this run to fail and force me to rearrange some requirement ranges to get it to work, however, because this PR passes I think it would be cleaner to just sit on the v20.2 defaults and wait until v20.3

**Pull request closed without merging**
