### PR TITLE
Parallel doc lints

### PR DESCRIPTION
**Pull request by thedrow**
This will enable us to run our doc lints faster. We do need to install the newest version of sphinx_celery though.
See https://github.com/celery/sphinx_celery/issues/4 & https://github.com/celery/sphinx_celery/pull/5.

### CODE REVIEW

**Comment by auvipy** [comment]
should the windows 2.7 failure ignored?

**Comment by thedrow** [comment]
It's a network error on their part.
I'm gonna wait for @georgepsarakis to approve this for a bit before merging this.

**Comment by georgepsarakis** [comment]
@thedrow I am adding the Sphinx [documentation link](http://www.sphinx-doc.org/en/stable/extdev/#extension-metadata) as a reference. So, this only means that files are being parsed by Sphinx in parallel? I compared the completion times of build jobs with another PR and the speed improvement is in the order of 5-10% perhaps.

**Comment by thedrow** [comment]
Yes, files are read in parallel.
5%-10% was worth the time I spent on this.

**Pull request merged**
