### PR TITLE
Fix issue #2225

### PR DESCRIPTION
**Pull request by aneilbaboo**
Creating a chord no longer results in "TypeError: group object got
multiple values for keyword argument 'task_id'".  Chords now
complete without hanging.

https://github.com/celery/celery/issues/2225

### CODE REVIEW

**Comment by thedrow** [comment]
Can you please rebase?

**Comment by thedrow** [comment]
@aneilbaboo Ping?

**Comment by thedrow** [comment]
Can you please rebase this so we can merge?

**Comment by aneilbaboo** [comment]
@thedrow Done now, I think.  NB: I haven't worked on this stuff in a long, long time.  I stopped using celery almost a year ago when I didn't get responses from the maintainer for my pull requests.

**Comment by thedrow** [comment]
@aneilbaboo I'm really sorry. The maintainer has been really busy so we teamed up to help maintain this project.

**Comment by thedrow** [comment]
@ask @malinoff What do you guys think?

**Comment by aneilbaboo** [comment]
There was one merge conflict.  Please check that my resolution makes
sense.  I don't really understand this code now -- I merely accepted my
lines over the conflict in the master.

**Comment by thedrow** [comment]
Where exactly is the conflict?

**Comment by aarcro** [comment]
I think the failing test is related to [1e3fcaa969de6ad32b52a3ed8e74281e5e5360e6]
I'd love to see this PR get merged.

**Comment by aneilbaboo** [comment]
The changes are in base.py, 360-366:

<<<<<<< HEAD
        options['task_id'] = group_id
        result = header(*partial_args, **options or {})
=======
        fixed_options = dict((k,v) for k,v in options.items() if
k!='task_id')
        result = header(*partial_args, task_id=group_id, **fixed_options or
{})
>>>>>>> Fix additional issue #2225

My branch is below, the master branch is above.

Looks like there's another commit to master.  I will rebase again.

**Comment by thedrow** [comment]
FYI you're merging instead of rebasing. I'm not gonna be pedant about it but rebases are better when it comes to pull requests because the history is cleaner.
Read https://www.atlassian.com/git/tutorials/merging-vs-rebasing/ if you want to learn more.

**Comment by aneilbaboo** [comment]
I'd be very cautious with these commits.  They are a ducktape and wire fix.


Honestly, after spending days tracing through this code, I came to the
conclusion that the workflow system might benefit from a complete rewrite.

First, I'd start with a set of tests and then work on a module that cleanly
serializes/deserializes workflow.  Currently, it's impossible to test
because the code for serializing the workflow is intermingled in many
places with the code which runs the workflow.  It would also be REALLY
useful if someone would formalize & document the data structures produced
by this system.  There's some ambiguity & duplication of data which I think
contributes to confusion.

Glad someone is taking a crack at this.  The workflow system is a great
idea.  Good luck with it!



On Mon, Jul 13, 2015 at 7:35 AM, Aneil Mallavarapu <aneil.mallavar@gmail.com

**Comment by aneilbaboo** [comment]
I thought I was rebasing.  Sorry, I'm a bit rusty --- I haven't been coding
for a year.

**Comment by thedrow** [comment]
Thanks a lot. The build was fixed so I'm merging this.

**Comment by thedrow** [comment]
@aneilbaboo The build is failing on Python 3. Can you please take a look? https://travis-ci.org/celery/celery/jobs/70858903#L283

**Comment by aneilbaboo** [comment]
Hi Omer, Apologies, I don't have time, and it's been ages since I looked at
this stuff.

**Comment by aarcro** [comment]
I was going to look at fixing this, but tox doesn't fail the same way in master for me locally

**Comment by thedrow** [comment]
@aarcro That's concerning. How does it fail for you? Which OS are you on?

**Comment by ginoledesma** [comment]
I can replicate this on the following OS environments:

Mac OS X with python 3.4.3 and the python:3.4.3-wheezy docker image.

Specifically:

```test_group_to_chord (celery.tests.app.test_builtins.test_chain) ... ERROR
```

From what I can tell, it fails here:

```
def maybe_unroll_group(g):
    """Unroll group with only one member."""
    # Issue #1656
    try:
        size = len(g.tasks)
    except TypeError as err:
        print('TypeError', err, type(g.tasks))
        try:
            size = g.tasks.__length_hint__()
        except (AttributeError, TypeError) as err:
            pass
        else:
            return list(g.tasks)[0] if size == 1 else g
    else:
        return g.tasks[0] if size == 1 else g
```

The map class object doesn't support both `len()` and `__length_hint__()`

**Comment by ginoledesma** [comment]
Ok, after digging it a little bit deeper, the problem is actually introduced in https://github.com/celery/celery/blob/master/celery/canvas.py#L606 by https://github.com/celery/celery/commit/05f84b34b1c7dc6ec1024b12cf32e266736375bc:

```python
def _maybe_group(tasks):
    if isinstance(tasks, group):
        tasks = list(tasks.tasks)
    elif isinstance(tasks, Signature):
        tasks = [tasks]
    else:
        tasks = map(signature, regen(tasks))
    return tasks
```

This can be fixed by replacing it with:
```python
tasks = list(map(signature, regen(tasks))
```

**Comment by ask** [comment]
That will copy the list twice though, for Python 3 compatibility I prefer just using:

    tasks = [signature(task) for task in regen(tasks)]

There's actually another bug here: the app is not passed to the signature.
I tried to find all of the cases where the app is not passed, but probably I did a `ack 'signature\('`, the list comprehension would've avoided that.

**Comment by ask** [comment]
Oh, I didn't realize the `map(signature`, is part of this patch.

The point of using regen in the first place here is to avoid consuming the iterator/generator: this should
only happen as the last step of sending the task messages.

`regen` is a simple wrapper to allow for caching the evaluation so that calling the tasks does not fail
with StopIteration if you `repr` the signature before calling.

**Comment by thedrow** [comment]
@ask I'm not sure I'm following.
What's the fix here?

**Pull request merged**
