### PR TITLE
debug: test suite hanging

### PR DESCRIPTION
**Pull request by graingert**
*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

### CODE REVIEW

**Comment by graingert** [comment]
```
Jul 29 08:33:26 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]:   ##  ##      RabbitMQ 3.8.5

Jul 29 08:33:26 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]:   ##  ##

Jul 29 08:33:26 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]:   ##########  Copyright (c) 2007-2020 VMware, Inc. or its affiliates.

Jul 29 08:33:26 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]:   ######  ##

Jul 29 08:33:26 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]:   ##########  Licensed under the MPL 1.1. Website: https://rabbitmq.com

Jul 29 08:33:26 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]:   Doc guides: https://rabbitmq.com/documentation.html

Jul 29 08:33:26 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]:   Support:    https://rabbitmq.com/contact.html

Jul 29 08:33:26 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]:   Tutorials:  https://rabbitmq.com/getstarted.html

Jul 29 08:33:26 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]:   Monitoring: https://rabbitmq.com/monitoring.html

Jul 29 08:33:26 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]:   Logs: /var/log/rabbitmq/rabbit@travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46.log

Jul 29 08:33:26 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]:         /var/log/rabbitmq/rabbit@travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46_upgrade.log

Jul 29 08:33:26 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]:   Config file(s): (none)

Jul 29 08:33:28 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]:   Starting broker...

Jul 29 08:33:28 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]: BOOT FAILED

Jul 29 08:33:28 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]: ===========

Jul 29 08:33:28 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]: Exception during startup:

Jul 29 08:33:28 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]:     application_master:start_it_old/4 line 277

Jul 29 08:33:28 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]:     rabbit:start/2 line 883

Jul 29 08:33:28 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]:     rabbit_boot_steps:run_boot_steps/1 line 29

Jul 29 08:33:28 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]:     rabbit_boot_steps:'-run_boot_steps/1-lc$^0/1-0-'/1 line 28

Jul 29 08:33:28 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]:     rabbit_boot_steps:run_step/2 line 55

Jul 29 08:33:28 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]:     rabbit_boot_steps:'-run_step/2-lc$^0/1-0-'/2 line 50

Jul 29 08:33:28 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]:     rabbit_networking:boot/0 line 81

Jul 29 08:33:28 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]:     rabbit_networking:record_distribution_listener/0 line 295

Jul 29 08:33:28 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]: error:{badmatch,noport}

Jul 29 08:33:31 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]: {"Kernel pid terminated",application_controller,"{application_start_failure,rabbit,{{badmatch,noport},{rabbit,start,[normal,[]]}}}"}

Jul 29 08:33:31 travis-job-9ec76d7a-edc6-4fe8-ac6d-fe44b7d12e46 rabbitmq-server[10590]: Kernel pid terminated (application_controller) ({application_start_failure,rabbit,{{badmatch,noport},{rabbit,start,[normal,[]]}}})
```

**Comment by graingert** [comment]
@auvipy I'm testing a theory that there's a race between the travis buildin rabbitmq and the newly installed rabbitmq, and they both claim the same port.

**Comment by auvipy** [comment]
No worries. keep trying. I am following your work silently

**Comment by graingert** [comment]
@auvipy ok yep that fixed it!

Now it's just hanging - gonna backport the fix to #6253

**Comment by graingert** [comment]
@auvipy bah, it was a fluke! https://travis-ci.org/github/celery/celery/builds/712861630 failed on install with the travis service disabled.

**Comment by graingert** [comment]
@auvipy hmmm you think we need?:

```
    - sudo mkdir -p /var/log/celery /var/run/celery /var/run/rabbitmq
    - sudo chown travis /var/log/celery /var/run/celery /var/run/rabbitmq
```

**Comment by graingert** [comment]
related: https://github.com/celery/celery/pull/6255

**Comment by graingert** [comment]
related: https://github.com/celery/celery/pull/6270

**Pull request closed without merging**
