### PR TITLE
Populate heap when periodic tasks are changed

### PR DESCRIPTION
**Pull request by wzywno**
## Description

Checks if the heap is valid. If there are changes in scheduled tasks the heap is populated again.

Fixes [7](https://github.com/celery/django-celery-beat/issues/7)

### CODE REVIEW

**Comment by oortega** [comment]
Hello, someone please be the heroe to merge the pull requests?. I tried pip install --upgrade celery but the version is 4.0.2.

Thanks.

**Comment by brianmay** [comment]
I believe this pull request now superseded by #3890.

**Comment by brianmay** [comment]
Merged in #3958, this issue can be closed.

**Comment by thedrow** [comment]
@wzywno Thanks for the contribution. It has been used in #3958. Feel free to add yourself to the AUTHORS file.

**Pull request closed without merging**
