### PR TITLE
Typo in the example systemd service

### PR DESCRIPTION
**Pull request by palewire**

### CODE REVIEW

**Comment by lafrech** [comment]
I believe the dash/minus sign here is intended. It means "ignore errors if file does not exist".

See https://lists.freedesktop.org/archives/systemd-devel/2013-February/009227.html for instance.

**Comment by palewire** [comment]
Fair, though in the context of the page this example recommends the creation of that file. Without it there, the script would fail unless the environment variables were set via another means. No other means are suggested in the page.

My view is that the example deployment options should be tightly packaged together.

**Comment by lafrech** [comment]
> Fair, though in the context of the page this example recommends the creation of the environment variables file. Without it there, the systemd script would fail unless the variables are set by another means. No other means are suggested in that section.

Yes, you're right. I think the fact that you called it a "typo" made me suspect you might not know about that specific syntax and then I didn't think any further. But you're right that it is not consistent.

> My view is that the example deployment options should be packaged together as tightly as possible. This is beyond the scope of this ticket, but I also think this section of the documentation could be improved by helping readers understand it's important their code be present in working directory path and that the recommended /var/run/celery and /var/log/celery directories will likely need to be created with the proper permissions.

As someone who just spent days trying to deamonize his celery/flask application, I can only confirm this. I wish I could be more constructive by providing helpful comments and ideally a PR, but people before me with much greater knowledge about systemd have been arguing about those sample files already and here we are (search systemd in issues, or just look at this one: https://github.com/celery/celery/issues/2131). I'm afraid there are many different cases and it is difficult to provide a plug and play example.

**Comment by georgepsarakis** [comment]
@lafrech thanks a lot for sharing that information! I thought it might have been intentional, but I couldn't find  proper documentation.

**Comment by georgepsarakis** [comment]
@palewire I am closing this, as from our discussion so far, it seems that it is better to silently ignore the absence of the `/etc/conf.d/` settings file.

**Comment by lafrech** [comment]
@palewire has a good point and since those variables are not defined anywhere else, the service will crash if `/etc/conf.d/celery` does not exist so we'd rather stop with an explicit error as soon as this file is found missing. In other words, this PR should be merged IMHO: it is slightly better with than without it. Not a big deal anyway.

**Comment by georgepsarakis** [comment]
@lafrech you are right.

**Pull request merged**
