### PR TITLE
pypy and python2 re added

### PR DESCRIPTION
**Pull request by auvipy**

### CODE REVIEW

**Comment by thedrow** [comment]
Why is PyPy unit in the lint stage?
Also, it's maybe because we removed the encoding headers.

**Comment by auvipy** [comment]
will be back to this soon

**Comment by thedrow** [comment]
Now I'm getting an error with the Python 2.7 build.

**Comment by auvipy** [comment]
ops

**Comment by auvipy** [comment]
I will resume this work

**Pull request closed without merging**
