### PR TITLE
Bytes/unicode treated differently by Shelve bysed on Python version

### PR DESCRIPTION
**Pull request by fridex**
relates: #3346

Fixes:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/kombu/utils/objects.py", line 40, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'scheduler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.5/shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: b'entries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/celery/apps/beat.py", line 107, in start_scheduler
    service.start()
  File "/usr/lib/python3.5/site-packages/celery/beat.py", line 522, in start
    humanize_seconds(self.scheduler.max_interval))
  File "/usr/lib/python3.5/site-packages/kombu/utils/objects.py", line 42, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/lib/python3.5/site-packages/celery/beat.py", line 566, in scheduler
    return self.get_scheduler()
  File "/usr/lib/python3.5/site-packages/celery/beat.py", line 561, in get_scheduler
    lazy=lazy,
  File "/usr/lib/python3.5/site-packages/celery/beat.py", line 406, in __init__
    Scheduler.__init__(self, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/celery/beat.py", line 205, in __init__
    self.setup_schedule()
  File "/usr/lib/python3.5/site-packages/celery/beat.py", line 436, in setup_schedule
    self._store[b'entries']
  File "/usr/lib64/python3.5/shelve.py", line 113, in __getitem__
    f = BytesIO(self.dict[key.encode(self.keyencoding)])
AttributeError: 'bytes' object has no attribute 'encode'

```

Additional info:
As stated in Python3 docs [1]: "The keys are ordinary strings."
```
software -> celery:4.0.0rc4 (0today8) kombu:4.0.0rc4 py:3.5.1
            billiard:3.5.0.1 py-amqp:2.1.0
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.default.Loader
```

[1] https://docs.python.org/3.4/library/shelve.html

### CODE REVIEW

**Comment by fridex** [comment]
Ping? Any progress with this?

**Comment by auvipy** [comment]
you should make travis happy

**Comment by ncoghlan** [comment]
The test failures from Travis appear to relate to the Django worker tests.

There are a couple of small typos in the commit messages:

Adopt -> Adapt
bysed -> based

**Comment by ncoghlan** [comment]
Checking https://github.com/celery/celery/pull/3463 shows that is seeing the same failure as this PR in `test_DjangoWorkerFixup.test_validate_models` (under both Python 2.x and 3.x)

**Comment by fridex** [comment]
Ask fixed build failures in 5fcb338, I will check remaining failures.

**Comment by fridex** [comment]
All tests passed.

**Comment by fridex** [comment]
Already solved by #3481

**Pull request closed without merging**
