### PR TITLE
[wip]: start chord header tasks as soon as they are yielded from the generator

### LINKED ISSUE #3021: group and chord: subtasks are not executed until entire generator is consumed
When passing a generator to `group` or `chord`, sub-tasks are not submitted to the broker for execution until the entire generator is consumed.  The expected result is that subtasks are submitted during iteration, as soon as they are visited.

Here is the test code I'm using:

``` python
from celery import Celery, group
from celery.utils.log import get_task_logger

app = Celery(__name__, broker='redis://localhost:6379/0',
             backend='redis://localhost:6379/0')

logger = get_task_logger(__name__)

def longyield():
    import time
    for i in xrange(5):
        time.sleep(2)
        print "yielding", i
        yield add.s(i, i)

@app.task
def add(x, y):
    logger.info("adding {} + {}".format(x, y))
    return x + y

def itertest():
    it = longyield()
    g = group(it)
    result = g.delay()
    print result.get()
```

I'm testing with 4.0rc1.

### PR DESCRIPTION
**Pull request by mjhoffman65**
Will fix #3021

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

### CODE REVIEW

**Comment by auvipy** [comment]
thanks for handling this. can you link the related issue?

**Comment by mjhoffman65** [comment]
> thanks for handling this. can you link the related issue?

Thanks for your quick reply earlier!  Linked the issue.  This is still a work in progress, but going well so far.

**Comment by auvipy** [comment]
thank you and please carry this on!

**Comment by auvipy** [comment]
rabbit integration test is failing

**Comment by mjhoffman65** [comment]
> rabbit integration test is failing

working on the integration tests.  i'm thinking the problem is with `vine.synchronization.barrier` is having trouble with`_regen`

**Comment by auvipy** [comment]
timeout error in the integration tests

**Comment by thedrow** [comment]
Since this PR is still in progress I converted it to a draft just so we won't merge it by accident.
Please convert it back once it is ready.

**Comment by mjhoffman65** [comment]
> Since this PR is still in progress I converted it to a draft just so we won't merge it by accident.
> Please convert it back once it is ready.

Thanks!  I should be able to get back to this a bit today and later in the week

**Comment by auvipy** [comment]
> > Since this PR is still in progress I converted it to a draft just so we won't merge it by accident.
> > Please convert it back once it is ready.
> 
> Thanks! I should be able to get back to this a bit today and later in the week

looking forward to it.

**Comment by maybe-sybr** [comment]
@mjhoffman65 - any chance you would have the time to revisit this? IIUC there were some integration test failures which need to be addressed. Perhaps @auvipy can refresh us?

**Comment by auvipy** [comment]
> @mjhoffman65 - any chance you would have the time to revisit this? IIUC there were some integration test failures which need to be addressed. Perhaps @auvipy can refresh us?
> 
> _Edit:_ I intend to take the diff relating to `function.regen` and merge it separately since it should be a fairly trivial change to merge and test independently.

splitting the trivial part separately would be great. then this needs to rebase & some code cleanup as well. the original author was @chardik

**Comment by auvipy** [comment]
you can also check the comments here https://github.com/celery/celery/issues/3021 @chadrik do you still use celery?

**Comment by chadrik** [comment]
Nope, sorry.  I made this change as an investigation into stream processing
tools for python and ultimately settled on Apache Beam. I recommend
checking it out.  Production-grade deployment of Beam is challenging
(unless you’re willing to use a hosted solution) but it’s incredibly
powerful.

**Comment by thedrow** [comment]
@chadrik Celery is not a solution for streaming data. It's simply not designed to deal with this use case.

**Comment by chadrik** [comment]
Yup, that’s why I didn’t choose it.

**Comment by mjhoffman65** [comment]
> > @mjhoffman65 - any chance you would have the time to revisit this? IIUC there were some integration test failures which need to be addressed. Perhaps @auvipy can refresh us?
> > _Edit:_ I intend to take the diff relating to `function.regen` and merge it separately since it should be a fairly trivial change to merge and test independently.
> 
> splitting the trivial part separately would be great. then this needs to rebase & some code cleanup as well.

@auvipy and @maybe-sybr,  working on getting this rebased now.

**Comment by mjhoffman65** [comment]
The force push closed this PR, but I am still working on this.  Going well so far.  Will open a new PR once it's ready.

**Pull request closed without merging**
