### PR TITLE
added missing kwargs arguments in some cli cmd

### PR DESCRIPTION
**Pull request by auvipy**
based on comment https://github.com/celery/celery/issues/7683#issuecomment-1372179683

### CODE REVIEW

**Comment by Nusnus** [comment]
Hey @auvipy , any updates on this PR?

**Comment by auvipy** [comment]
I need manual verification from you or Omer

**Comment by Nusnus** [comment]
> I need manual verification from you or Omer

Ok so I've been reading a bit about this change, and about the original discussion, and I'm not sure this will fix the issue.
Adding the `**kwargs` will only absorb those errors but if the actual `kwargs` isn't being used as well, then for example where they used `--template`, it will not be honored as we don't do anything else in this change beside accepting the new arguments.

The original use-case needs to be tested (manually would be fine too) before we can merge this change, in case I am missing something and the `kwargs` does get used somehow or that everything works if we just "ignore" this exception by absorbing the extra parameters into `kwargs`.

Do you have a way to validate this change indeed fixes the issue? @auvipy

**Comment by Nusnus** [comment]
@thedrow Hey can you give it a quick look please?
You might be able to judge quickly if we can push/block for testing (as it might not be required).

Thanks!

**Review by auvipy — COMMENTED** [review]
merging as temporary solution and it is used as convention in other parts of CLI

**Pull request merged**
