### PR TITLE
Add auth options to Cassandra backend

### PR DESCRIPTION
**Pull request by davidharrigan**
This PR adds the ability to configure authentication options for Cassandra backend, per documentation described in DataStax Cassandra python-driver: https://datastax.github.io/python-driver/api/cassandra/auth.html

### CODE REVIEW

**Comment by thedrow** [comment]
Looks great. Can you please cover your changes with tests?

**Comment by davidharrigan** [comment]
Sure thing, I'll add some test cases.

**Comment by davidharrigan** [comment]
@thedrow I've added test to cover my changes.  `.coveragerc` has `celery.backends.cassandra` disabled, but I've enabled it in my local copy to ensure the changes are covered.

**Comment by thedrow** [comment]
I think that it's safe to enable coverage for Cassandra.

**Comment by thedrow** [comment]
Done.

**Pull request merged**
