### PR TITLE
Added two new unit tests to callback stamping

### PR DESCRIPTION
**Pull request by Nusnus**
- test_callback_stamping
- test_callback_stamping_on_replace

### CODE REVIEW

**Review by auvipy — APPROVED** [review]

**Comment by Nusnus** [comment]
Thanks 💪 @auvipy

**Comment by auvipy** [comment]
thanks for the additional tests!

**Comment by auvipy** [comment]
the CI wass green when this was merged, but after push why the CI are red? can you please check?

**Comment by auvipy** [comment]
I just keep you in touch no worries. new PR's are passing.

**Pull request merged**
