### PR TITLE
[WIP] - Work in progress PR for Celery version 5

### PR DESCRIPTION
**Pull request by auvipy**
Will merge into master before the release of Celery 5.0.0 stable.

### CODE REVIEW

**Comment by thedrow** [comment]
We should regularly merge from master to avoid conflicts if we decide at some point we've reached to a place where we can start releasing alphas.

**Comment by auvipy** [comment]
we should do that in all upcoming PR to be merged in v5-dev. in that way, this PR remain clean with separate PR commits. so let us merge from master on the working PR's open against v5-dev[me with the removal of py2] and you with the click one. when we squash merge the commits in v5-dev branch, fresh relevant commits will be here cleanly :)

**Comment by thedrow** [comment]
Are we using black or autopep8 for formatting code now?

**Comment by auvipy** [comment]
no

**Comment by thedrow** [comment]
> no

That does not answer the question.
pyproject.toml contains configuration for black for some reason.
Have we moved from using autopep8 to black?

**Comment by thedrow** [comment]
> > no
> 
> That does not answer the question.
> pyproject.toml contains configuration for black for some reason.
> Have we moved from using autopep8 to black?

@auvipy ???

**Comment by auvipy** [comment]
we haven't moved to black yet. We have to modify the pyproject.toml conf file.

**Comment by matteius** [comment]
Seems like we need a celery5-master branch that we merge to separate from master -- it should still be possible to patch Celery 4.x bugs in a master branch for patching it in the future without requiring an upgrade to 5.x to get a bug fix.  Or we could move it to celery4-master and make master about celery5 would work too.

**Comment by auvipy** [comment]
that's not needed. we will create a 4.5/4.6 maintenance branch before merging this to master.

**Comment by thedrow** [comment]
> that's not needed. we will create a 4.5/4.6 maintenance branch before merging this to master.

Agreed.

**Comment by auvipy** [comment]
needs rebase on top of master

**Comment by auvipy** [comment]
before merging this to master we must have to create a 4.x branch for maintenace/backport/upgradation shim related releases on 4.4.x/4.5.x  releases.

**Pull request merged**
