### PR TITLE
3.1

### PR DESCRIPTION
**Pull request by AkharazOmar**
Correction of bug.

add parent for group when previous task exist in chain.

link chain with last task of group or chord...

### CODE REVIEW

**Comment by AkharazOmar** [comment]
aborted...

**Comment by thedrow** [comment]
@AkharazOmar I'm not sure what you meant to do here.
If you can please describe the bug or problem you were trying to solve.
I'm closing this PR until it's actionable.

**Comment by AkharazOmar** [comment]
Hello,

Sorry but i don't have good leve lin english. Then i will give example of
bug:

1 example:

@app.task
def test_custom_task(result, sleep_time: float, text_begin: str,
text_end: str, return_value=None):
    logger.info("Previous result: {}".format(result))

    logger.info(text_begin)
    if sleep_time > 0:
        time.sleep(sleep_time)
    logger.info(text_end)

    if isinstance(return_value, Exception):
        logger.error("Error: Exception detected")
        raise return_value
    logger.info('Success: No exception detected.')
    return return_value


task_1 = test_custom_task.subtask((2, 'Start', 'End', 'OK1'))
task_2 = test_custom_task.subtask((2, 'Start 2', 'End 2', TypeError('Oups')))
task_3 = test_custom_task.subtask((2, 'Start 3', 'End 3', 'OK3'))
workflow = chain(group(task_1, task_2), task_3)

if you run workflow:
res = workflow.delay(None)

Never you will finish task. Because res lisen the last task "task_3".
(This is in case where one task raise exception)

2 example:

One bug of celery is when you run workflow is group in group and
finish we task, you will never finish too. For this reason, you make
chain.

I solve this. Now you can do all workflow you want, it's ok.

Thank you.


2015-06-15 9:19 GMT+02:00 Omer Katz <notifications@github.com>:

**Comment by AkharazOmar** [comment]
Hello,

I told you long ago, but you never need me back.
So I come to you to explain the problem.
When creating a Chord with several tasks, there is a purpose that the last
task is never performed. But change creates a workflow with the same group
of channels you want celery always come to his end.

Thanks
Omar Akharaz

**Pull request closed without merging**
