### PR TITLE
Add delay parameter function to beat_schedule (#5466)

### PR DESCRIPTION
**Pull request by vallee11**
Signed-off-by: vallee11 <xph_wangly10@163.com>

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

### CODE REVIEW

**Comment by auvipy** [comment]
seems the test failing is unrelated. could you try to fix this issue differently https://github.com/celery/celery/issues/5555 ?

**Comment by vallee11** [comment]
Removed dangerous default mutable arguments from function definitions… (

#1040)

def disable_insecure_serializers(allowed=['json']):
      pass

Not equivalent

def disable_insecure_serializers(allowed=None):
      allowed = ['json'] if not allowed else allowed

**Comment by auvipy** [comment]
OK

**Comment by auvipy** [comment]
https://github.com/celery/celery/pull/5559 check the PR

**Comment by browniebroke** [comment]
Hoping to fix the build with https://github.com/celery/kombu/pull/1055

**Comment by auvipy** [comment]
@browniebroke I really appreciate your time and effort.

**Pull request merged**
