### PR TITLE
Initial support for a filesystem based result backend.

### PR DESCRIPTION
**Pull request by moshevds**
This is an implementation of a filesystem based result backend, as discussed earlier in #1780.
I ran the unittests on python 2.6, 2.7, 3.3 and pypy, as well as tested the backend locally and with multiple nodes on GlusterFS.

### CODE REVIEW

**Comment by thedrow** [comment]
The build is failing for Python 3. https://travis-ci.org/celery/celery/jobs/45052922#L657
Let's fix that and it will be merged.

**Comment by moshevds** [comment]
Hi @thedrow,

The backend was created more than a year ago, and I have rebased a few times to get it merged. It seems I have rebased over a change in the way values are serialized, without checking if everything still works.

It is a small fix to convert the parameter for set() from a string to a buffer, but will that parameter always be a string (in the current codebase)? I think that makes more sense than the old behavior actually, so perhaps you can confirm this?

If not, then I think I need to add more tests, any suggestions on what tests are needed?

Greetings,
Môshe van der Sterre

**Comment by thedrow** [comment]
I think that's probably valid because you are either passing pickled objects or json or msgpack.
@ask @malinoff Any thoughts?

**Comment by moshevds** [comment]
Actually, pickle and msgpack are bytes, only json is str. I just checked, and reverting 8d4354a "Default serializer is now json" makes the tests pass.

In conclusion, for now, I'll add the following:
```
 if not isinstance(value, bytes):
    value = value.encode('utf-8')
```
So it works with both str and bytes (and is also correct for python 2.6+).

But this also means my unit tests are incomplete when only checking the default serializer. I'm not sure how to best fix that.

**Comment by moshevds** [comment]
I looked at this some more, and I found that I can use kombu.utils.encoding.ensure_bytes.

Another thing that I was worried about is the decoding, because get() will always return bytes, not str. I found that this is actually handled in kombu.utils.json.loads, so that is not a problem.

**Comment by auvipy** [comment]
This branch has conflicts that must be resolved

**Comment by thedrow** [comment]
Thanks!

**Pull request merged**
