### PR TITLE
added 2  debian package for better stability in Docker

### PR DESCRIPTION
**Pull request by auvipy**

### CODE REVIEW

**Comment by Nusnus** [comment]
@auvipy Did you notice the build CI job wasn't triggered?

**Comment by auvipy** [comment]
Yes, i think it is sane to add dockerfile path. Will try that now

**Comment by auvipy** [comment]
yes it triggered!

**Comment by Nusnus** [comment]
Good job!

**Comment by auvipy** [comment]
thanks do me one last favor before the release bro!! can you have a look at https://github.com/celery/celery/pull/7901 and share your thoughts? tests are passing there.

**Pull request merged**
