### PR TITLE
[Don't Merge] Encode schedule filename with filesystem encoding

### LINKED ISSUE #4533: [pypy] Beat errors on startup with "TypeError: expected string"
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.

```
software -> celery:4.1.0 (latentcall) kombu:4.1.0 py:2.7.13
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Darwin arch:64bit imp:PyPy
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled
```

- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

Celery is passing the beat schedule file name as unicode (`u'celerybeat-schedule'`) to the shelve module, which [expects a `str`](https://bitbucket.org/pypy/pypy/src/0e7ea4fe15e82d5124e805e2e4a37cae1a402d4b/lib_pypy/dbm.py?at=release-pypy2.7-v5.10.0&fileviewer=file-view-default#dbm.py-159):

```
Removing corrupted schedule file u'celerybeat-schedule': TypeError('expected string',)
Traceback (most recent call last):
  File "/Users/josh/.venv/site-packages/celery/beat.py", line 425, in setup_schedule
    self._store = self._open_schedule()
  File "/Users/josh/.venv/site-packages/celery/beat.py", line 415, in _open_schedule
    return self.persistence.open(self.schedule_filename, writeback=True)
  File "/Users/josh/.pyenv/versions/pypy2.7-5.8.0/lib-python/2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/Users/josh/.pyenv/versions/pypy2.7-5.8.0/lib-python/2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/Users/josh/.pyenv/versions/pypy2.7-5.8.0/lib-python/2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
  File "/Users/josh/.pyenv/versions/pypy2.7-5.8.0/lib_pypy/dbm.py", line 160, in open
    raise TypeError("expected string")
TypeError: expected string
```

Downgrading to 3.1.25 fixes the issue. No 4.x release that I tried (or master) will work.

### PR DESCRIPTION
**Pull request by joshfriend**
# WIP

* Runs tests on OSX
* Fixes schedule filename encoding bug with pypy

Fixes #4533

Might take me a few tries to get the build matrix down to an acceptable size :P

### CODE REVIEW

**Comment by joshfriend** [comment]
CI was a disaster, but the test passes under pypy2.7-5.8.0 when I run it on my mac.

**Comment by joshfriend** [comment]
Oh man, I totally forgot about this PR, sorry 😬

**Comment by joshfriend** [comment]
I removed the travis yml changes, figured it's not worth adding a whole new set of tests on a new OS to the matrix just for this one change

**Comment by auvipy** [comment]
ping

**Comment by joshfriend** [comment]
I've realized that I just don't have the time required to fix this for all supported python versions. Also, the versions of python that have this issue are pretty old at this point and I don't think it is really worth any effort supporting this super rare case for them.

**Pull request closed without merging**
